### ISSUE TITLE
Home Assistant OS 5.9

### ISSUE THREAD

**Issue by simonlock** [ReneNulschDE/mbapi2020#1]
Host System
Hostname
homeassistant
IP Address
Operating System
Home Assistant OS 5.9
Deployment
production

Hi Rene
I've just installed this and can't see a way to login/authenticate. I appreciate it's still early days.  Is this only supported on a raspberry PI as I believe was your previous version? I'm running the latest version homeassistant in a vm (Home Assistant OS 5.9). Thanks.

**Comment by ReneNulschDE** [comment]
Hi, what happens whenyou try to add the integration "MercedesME 2020" via the HA integration page config/integrations?

**Comment by simonlock** [comment]
Hi Rene

 

Thanks for your reply. The pointer to config/integrations was the step that I was missing. It’s working now. Thank you for this integration.

 

Regards

 

Simon

**Comment by xraver** [comment]
Dear
it works also in italian market! tested with w176 (a200d)
regards

Il giorno gio 31 dic 2020 alle ore 19:59 simonlock <notifications@github.com>
ha scritto:
