### ISSUE TITLE
climate control doesn't work anymore

### ISSUE THREAD

**Issue by m4tze-smart** [ReneNulschDE/mbapi2020#100]
Hi,

after the last few updates my aux.heat entity is out of order.

Entität nicht verfügbar: switch.XXX_auxheat
I have only 32 entities and this entity is still missing, also after new install and PIN entry.

**Comment by ReneNulschDE** [comment]
Hi,

please go to the integration page, click on the 3 dots at the MB Integration and download the diagnostic data. Share it via email (mbdev.issue-100 @ nulsch . de)

**Comment by ReneNulschDE** [comment]
Solved via email. The car has no aux-heat. The preclimate can be controlled via the HA-Service preheat_start.

**Comment by B0rax** [comment]
Is it planned to add a switch for preheat like there is for aux heat?
