### ISSUE TITLE
Car Windows Closures

### ISSUE THREAD

**Issue by leovj** [ReneNulschDE/mbapi2020#101]
Good morning and thank you for your wonderful work! I updated to version 0.8, and as reported the window closures no longer work. However, I can't find them because the integration doesn't create the sensor windowStatusOverall (windowsClosed)...

Thanks

**Comment by ReneNulschDE** [comment]
In general this is working. At least I have multiple cars who reporting the correct status (2=closed, 0=moving, 1=open). Could you please:
1. Check if the status is available (and accurate) in the mobile app
2. Check if your licenses to get this data are still valid (Services in the MBme portal)
3. Download the diagnostic information from the component and send it to mbdev.issue.101 (at) nulsch . de (click on the three dots in the integration in the "devices & services" overview )

**Comment by leovj** [comment]
Thanks for yoy replay! I attach what is required.

![IMG_9561](https://user-images.githubusercontent.com/6884242/212110559-60efaf83-5251-428a-9391-99e1eab90b96.PNG)
<img width="1384" alt="Screenshot 2023-01-12 alle 16 33 31" src="https://user-images.githubusercontent.com/6884242/212110630-b260a852-7b92-4f5a-b2de-76cbda88833f.png">
[config_entry-mbapi2020-b887d8f9ec192ae20c836d9c35772f85.json.txt](https://github.com/ReneNulschDE/mbapi2020/files/10403219/config_entry-mbapi2020-b887d8f9ec192ae20c836d9c35772f85.json.txt)

**Comment by ReneNulschDE** [comment]
based on your diagnostic-log your the window status is available, only the open/closing is not supported. I would propose that first restart and check if the sensor is available again. Sometimes not all values are available at startup and I create the sensor only at the beginning.

**Comment by leovj** [comment]
Good morning and thanks for your answer, last night I tried to restart but it didn't work, so I tried to open and close the windows to see if it worked on the app. Everything was working and when I went back to HA I saw that the Windows Closed sensor appeared! Everything seemed to work until today I noticed that the sensor worked for about 2 hours and then came back unavailable..
<img width="555" alt="Screenshot 2023-01-13 alle 07 35 42" src="https://user-images.githubusercontent.com/6884242/212254370-d34a846f-8e7a-4041-bb70-3f3c013b9a2d.png">

**Comment by ReneNulschDE** [comment]
OK, I assume the API sends unexpected values. Could you please enable the option "DEBUG ONLY: Enable save server messages to the messages folder" in Configure dialog of this integration. Make the same check (try to reproduce). Send me zip with all files out of the folder "your_HA_config_folder/custome_components/mbapi2020/messages".

Disable the option afterwards and delete the files.

Thx

**Comment by leovj** [comment]
This is the sensor created by the integration. Now it seems to work again what seems strange to me that it stops working i don't know why. I'll keep an eye on the situation and update you.
<img width="550" alt="Screenshot 2023-01-13 alle 10 50 59" src="https://user-images.githubusercontent.com/6884242/212290579-50e71761-23a1-41e7-ab3a-0b1a08902e97.png">
<img width="534" alt="Screenshot 2023-01-13 alle 10 50 53" src="https://user-images.githubusercontent.com/6884242/212290587-0c731e4d-8ffd-4d2c-b1fc-2c8a26ac432d.png">
Now work

**Comment by ReneNulschDE** [comment]
Thx, I have such symptoms with my GLA when the starter battery state falls to yellow state. Just reopen the issue when you have further input.
