### ISSUE TITLE
No Engine Start?

### ISSUE THREAD

**Issue by alikhodrali** [ReneNulschDE/mbapi2020#102]
Hi there,
For some odd reason, I only have the option to unlock and lock the car in HASS. That works fine, but for some reason, I don't see the option to start the car or see its location, etc. Just lock/unlock. This is despite having all features available in app and having Mercedes Me Connect+ until 2024. Additionally, I am able to start the car using my pin with the Mercedes Me Alexa skill, so theoretically, I should be able to in HASS, no? Any help would be greatly appreciated!
Vehicle: 2019 E53 AMG.
Location: Ontario, Canada
![IMG_4475](https://user-images.githubusercontent.com/12537336/212656071-374a43bc-b001-4ea1-9a8e-68a2e626da6f.jpeg)

**Comment by ReneNulschDE** [comment]
Did you tried the HA service MBAPI2020 - engine_start?
![image](https://user-images.githubusercontent.com/33263735/212668059-47e8ad13-cc69-4f7c-8116-e8f13e7d5dfc.png)

**Comment by alikhodrali** [comment]
Thank you so much! That worked! Could you help me setup switches for this and for aux heat among other things by any chance? I'm an Electrical/AI engineering student but I'm still having trouble setting this custom integration up. I'm lost tbh haha. I wouldn't even mind helping you create instructions for others on my free time. I'm trying to get these switches to show in Homekit so I can use them with Siri. I mostly use homebridge on my other Pi but there's no working Mercedes Me plugin so this is the first time using HACS.

**Comment by ReneNulschDE** [comment]
Don't get me wrong: You are a student (with a mercedes), so you are eager to learn and you are trained to read. start here https://www.home-assistant.io/integrations/switch.template/ or here https://www.home-assistant.io/dashboards/button/

or check the hundreds of inputs here: https://community.home-assistant.io/t/mercedes-me-component/41911/1420 - just scroll up
