### ISSUE TITLE
Don't receive 6 pin code via email.

### ISSUE THREAD

**Issue by Marc1200** [ReneNulschDE/mbapi2020#103]
Hello,
I don't receive a 6 number pin via email. I set up integration and fill in email but i receive nothing.

**Comment by ReneNulschDE** [comment]
please enable the debug log (see readme in the repo), restart HA and retry it and share the relevant log entries please. In general, this is working.

**Comment by Marc1200** [comment]
This is the only debug line of the integration

2023-01-16 14:16:58.832 INFO (MainThread) [custom_components.mbapi2020.oauth] Start request PIN <EMAIL>

**Comment by ReneNulschDE** [comment]
are you 100% that this the account email that you use for your MB me app?

**Comment by ReneNulschDE** [comment]
Ok. What app do you use? What is your (App) country? Which region did you selected in the integration onboarding? What car do you have? Sorry - but in the last three years we never had that the email/pin topic had not worked. You say you use the "mercedes me connect app" and not the "mercedes me app" right?

**Comment by Marc1200** [comment]
It's the Mercedes me app, country is NL(Europe)
Mercedes GLC 2018.
I tried to sign in at the Mercedes portal in the browser with  Mercedes me id but when i enter the email, it says not found, when i enter the phone number then i can login.

**Comment by ReneNulschDE** [comment]
ok looks like you have found the issue, please try to add an email address to your account in the mb-portal. Log in with this component is working with the email address only currently.

**Comment by Marc1200** [comment]
Okay, i will try to add the email adress.

**Comment by ReneNulschDE** [comment]
hi marc (@Marc1200 ) did you have time to check this?

**Comment by Marc1200** [comment]
no i will check later, i will close the issue, that is most likely the problem
