### ISSUE TITLE
Feature: add loading indicators to commands

### ISSUE THREAD

**Issue by klejejs** [ReneNulschDE/mbapi2020#104]
When I trigger lock/unlock or auxiliary heating, it is sometimes hard to know if I pressed the button or not. Would it be possible to add loading state and icon when the, e.g, unlock button has been pressed but the state has not been updated yet?
This idea comes from my smart lock integration which does exactly that, it might be the case that the lock itself provides the loading state while Mercedes does not, but I don't think it would be hard to mimic that, would it?

P.S. Thank you for the great integration, I use it often and it is really convenient. Keep up the amazing work!

**Comment by ReneNulschDE** [comment]
thanks for this request. Unfortunately, this is not so easy to implement has the communication with the MB System is async and a implementation would be more complex. The diagnostic sensor "Car" has some attributes "last_command_*". These attributes show the status of the last command. You can try to create your own sensor to show the status in the frontend. See template sensor in the HA-docs.

Nevertheless, I will add this to the list but please do not expect a fast implementation.

Thx
Rene

**Comment by klejejs** [comment]
Thanks for the reply! I tried with a template sensor and it works for me as well though an API implementation would be better as it would integrate with the lock entity.
One thing I noticed while tinkering with this was that the lock state often updates some time after the doors have been locked or unlocked. Can an update from API be somehow forced?

**Comment by ReneNulschDE** [comment]
The master branch contains an update to the lock. Now the status is_locking and is_unlocking is provided. (But for the first 30 seconds only after initiating). I will integrate this in one of the next releases. 

Frontend Result (see color changes if the icon):
![Screencast from 2023-01-24 10-27-34](https://user-images.githubusercontent.com/33263735/214256987-8a844782-284e-4afe-ae82-22e49c371439.gif)

**Comment by klejejs** [comment]
Thank you!

**Comment by ReneNulschDE** [comment]
solved wit v0.8.1
