### ISSUE TITLE
Configuration of a statistic with source "Charging Power" not possible

### ISSUE THREAD

**Issue by bakerman100** [ReneNulschDE/mbapi2020#107]
Hi all,

I think I´ve found an issue with the "Charging Power" entity in mbapi2020 version 0.8.0.  
When adding a "statistic" in the dashboard, I could integrate sensor.<verhicalID>.charging_power in earlier versions of mbapi2020. 
With the version 0.8.0 I cannot find the data source any longer in the system, event though other entities and the integration itself in HA are nicely working. 

HA system support page points to this help page:
https://www.home-assistant.io/more-info/statistics/

What is the problem here or do I need to change the mbapi2020 configuration in HA?

Thanks for providing this awesome integration.

**Comment by ReneNulschDE** [comment]
Hi,

this fixed with v0.8.1 - The unit kW was missing. Please make sure you fix your statistics via developer tools/statistics.
