### ISSUE TITLE
serviceintervaldays missing from Odometer

### ISSUE THREAD

**Issue by mihsu81** [ReneNulschDE/mbapi2020#109]
Hi @ReneNulschDE ,

Thank you for this integration.

Since the update to v0.8.0 the attribute _serviceintervaldays_ disappeared from the entity _Odometer_.
I'm attaching the debug logs.
[config_entry-mbapi2020-a81a506fa51e983c282bb48320d2f13c.json.txt](https://github.com/ReneNulschDE/mbapi2020/files/10581840/config_entry-mbapi2020-a81a506fa51e983c282bb48320d2f13c.json.txt)

Adding the attribute _serviceintervaldistance_ from https://github.com/ReneNulschDE/mbapi2020/commit/174e841dd6045a6fbbf0bccc10887bac8d247f99 works and appears in the entity Odometer.

![image](https://user-images.githubusercontent.com/40715497/216683388-d4da676f-0bf3-411c-97a4-b6e171cd9da0.png)

**Comment by ReneNulschDE** [comment]
When you take look in the debug file, you could see that the serviceintervaldays get reported with status=3. these means that the mb systems can't report this value temporarily. Normally, this gets solved automatically in the next few days. So please be patient. This is not a problem of this component. The mb server just deliver no data right now.

**Comment by mihsu81** [comment]
Thanks a lot for the info. I didn't know that.
