### ISSUE TITLE
Statistic Diagramm Card in Home Assistant not working for long term charts

### ISSUE THREAD

**Issue by f45tb00t** [ReneNulschDE/mbapi2020#110]
Hi Renè,

I just tried to use the "Statistikdiagramm-Kartenkonfiguration" but I could not find the entity in the list. The HA Developers pointed that also out in the documentation and ask to refer the dev of the integration to: https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

Do you think this is possible to correct that? Or maybe point me in the direction what I need to do to get the long term diagram working with the card?

My Coupè is very "thirsty" and I would like to check the provided data a little more in detail.

Again - thanks a lot for this awesome work! :)

Cheers

fb

**Comment by ReneNulschDE** [comment]
Hi fb,

lass uns kurz die sprache wechseln. Kannst Du mir helfen was du mit Statistikdiagramm-Kartenkonfiguration meinst? Ich nutze immer nur die englische HA version - was machst du bzw. was willst du erreichen?

**Comment by f45tb00t** [comment]
Hi,

ich will eine neue Karte anlegen. "Statistikdiagramm-Kartenkonfiguration" heißt es in dem deutschsprachigen UI.
Dort kann man diverse Einstellungen tätigen. Wie z.B. Zeitraum (5 Minuten, Stunde, Tag, Woche, Monat), zu zeigende Tage, Statustypen (Mittel, Min, Max, Summe, ...) Diagrammtyp(line, bar) und dazu eine Entität auswählen. Der Graph der daraus gebildet wird ist ein wenig schöner, als wenn ich einfach nur auf den Benzinverbrauch klicke und dort eine Timerange einfüge.

In der englischen UI wird es wohl "add map - statistic diagram" heißen. Allerdings müssen die Entitäten dafür angepasst werden, wie in dem verlinkten Artikel

**Comment by ReneNulschDE** [comment]
Ok, danke. Ich schau mir dies morgen mal an.

**Comment by ReneNulschDE** [comment]
Hi, ich hab jetzt mehrere Stunden damit zugebracht und nein, ich verstehe nicht warum diese Karte es nicht anzeigt (nach kleineren Code Änderungen in meiner Komponente). Ich habe jetzt die Frage im Forum gestellt:
https://community.home-assistant.io/t/how-to-use-statistic-card-or-why-are-my-custom-sensors-are-not-visible/533794

**Comment by ReneNulschDE** [comment]
Hi,

Der Master Branch enthält die notwendigen Anpassungen. Kannst Du das testen?

Grüße
Rene

**Comment by f45tb00t** [comment]
Hi,


hab eben das master.zip runtergeladen, entpackt und per "cp -r" direkt in den order rein und HA neu gestartet. 

Leider finde ich die Entitäten noch nicht in der Liste. Hab auch mal den Cache vom Browser gelöscht, aber selbiges Ergebnis.

**Comment by ReneNulschDE** [comment]
Welche HA Version nutzt Du? Kannst Du prüfen ob Du die Statistiken unter HA-URL/developer-tools/statistics siehst?

**Comment by f45tb00t** [comment]
HA habe ich in Version 2023.2.4. Die Statistiken kann ich bei den Dev Tools nicht finden.

**Comment by ReneNulschDE** [comment]
Danke, ich teste dies nochmal in einer anderen Instanz

**Comment by ReneNulschDE** [comment]
solved with v0.8.2
