### ISSUE TITLE
Climate control not available

### ISSUE THREAD

**Issue by plh4** [ReneNulschDE/mbapi2020#111]
First thanks for the module!

I added a Smart EQ today and it seems to work fine.
But I am missing the function to start the climate. There is only a "lock" button?

**Comment by ReneNulschDE** [comment]
Hi, the smart integration is working "by accident" only. (We get some data via the websocket but all webservices deliver not data). To use the climate control you have to setup the [smart](https://github.com/ReneNulschDE/ha-smart-eq-connect) integration. Check the different posts in the [forum](https://community.home-assistant.io/t/smart-eq-connect/356866/13) how to setup the component.

**Comment by plh4** [comment]
Hey Rene, thanks for the answer.
I thought this is not the right integration, because it is no longer maintained. 
When trying to add it via HACS -> custom repositories, it does not load when adding URL https://github.com/ReneNulschDE/ha-smart-eq-connect. 
When I enter "ha-smart-eq-connect" only, it loads and loads and loads... but never appears.
Are there know problems regarding this?

**Comment by ReneNulschDE** [comment]
Hi, I have unarchived the solution. (HACS does not work with archived repos).
