### ISSUE TITLE
Smart EQ Control integration vs. MB API

### ISSUE THREAD

**Issue by ReneNulschDE** [ReneNulschDE/mbapi2020#113]
@vwcruiser: Deine Fehlermeldung in der SmartEQ integration zeigt, dass Du eine alte Version der Komponente benutzt. Mercedes hat die API URL von *.smart.com auf *.smart.mercedes-benz.de geändert. Du findest ein aktuelles Release im SmartEQ repo.

Die MBAPI Komponente funktioniert auch noch mit Smarts. Bitte stell sicher dass die Version 0.8.4 installiert ist. Bitte lösche die Datei .mercedesme-token-cache im HA-Config Verzeichnis. 

Und starte dann den anmeldeprozess nochmal.

**Comment by vwcruiser** [comment]
Hallo Rene, ich muss morgen früh raus, werde für heute hier aufhören. Wo finde ich ein aktuelles SmartEQ repo? In HACS habe ich kein SmartEQ repo. Mac Macovic hat mir damals per Teamviewer geholfen, das zu integrieren…

Gruß Kay

 

Von: Rene Nulsch ***@***.***> 
Gesendet: Sonntag, 26. Februar 2023 21:25
An: ReneNulschDE/mbapi2020 ***@***.***>
Cc: vwcruiser ***@***.***>; Mention ***@***.***>
Betreff: [ReneNulschDE/mbapi2020] Smart EQ Control integration vs. MB API (Issue #113)

 

@vwcruiser <https://github.com/vwcruiser> : Deine Fehlermeldung in der SmartEQ integration zeigt, dass Du eine alte Version der Komponente benutzt. Mercedes hat die API URL von *.smart.com auf *.smart.mercedes-benz.de geändert. Du findest ein aktuelles Release im SmartEQ repo.

Die MBAPI Komponente funktioniert auch noch mit Smarts. Bitte stell sicher dass die Version 0.8.4 installiert ist. Bitte lösche die Datei .mercedesme-token-cache im HA-Config Verzeichnis.

Und starte dann den anmeldeprozess nochmal.

**Comment by vwcruiser** [comment]
Hallo Rene, konnte es doch nicht lassen! Ich habe nochmal rein geschaut, ohne was zu ändern, waren plötzlich 24 Entities in der mbapi2020 da!

 



 

Schönen Sonntag Abend noch!

 

Vielen Dank für den Support!

 

Gruß Kay

 

Von: ***@***.*** ***@***.***> 
Gesendet: Sonntag, 26. Februar 2023 22:36
An: 'ReneNulschDE/mbapi2020' ***@***.***>
Betreff: AW: [ReneNulschDE/mbapi2020] Smart EQ Control integration vs. MB API (Issue #113)

 

Hallo Rene, ich muss morgen früh raus, werde für heute hier aufhören. Wo finde ich ein aktuelles SmartEQ repo? In HACS habe ich kein SmartEQ repo. Mac Macovic hat mir damals per Teamviewer geholfen, das zu integrieren…

Gruß Kay

 

Von: Rene Nulsch ***@***.*** ***@***.***> > 
Gesendet: Sonntag, 26. Februar 2023 21:25
An: ReneNulschDE/mbapi2020 ***@***.*** ***@***.***> >
Cc: vwcruiser ***@***.*** ***@***.***> >; Mention ***@***.*** ***@***.***> >
Betreff: [ReneNulschDE/mbapi2020] Smart EQ Control integration vs. MB API (Issue #113)

 

@vwcruiser <https://github.com/vwcruiser> : Deine Fehlermeldung in der SmartEQ integration zeigt, dass Du eine alte Version der Komponente benutzt. Mercedes hat die API URL von *.smart.com auf *.smart.mercedes-benz.de geändert. Du findest ein aktuelles Release im SmartEQ repo.

Die MBAPI Komponente funktioniert auch noch mit Smarts. Bitte stell sicher dass die Version 0.8.4 installiert ist. Bitte lösche die Datei .mercedesme-token-cache im HA-Config Verzeichnis.

Und starte dann den anmeldeprozess nochmal.
