### ISSUE TITLE
Possibility to see when charger is plugged in

### ISSUE THREAD

**Issue by Marc1200** [ReneNulschDE/mbapi2020#114]
Hello,
Is it possible to get an entity to see when the charging station is plugged in?

**Comment by ReneNulschDE** [comment]
Hi Marc,

the sensor "range_electric" has an attribute "Chargingstatus". The status should be 2 when its plugged-in but not charging.

**Comment by Marc1200** [comment]
I can't find it at that sensor:
![Screenshot_20230302-101513](https://user-images.githubusercontent.com/68737063/222384661-ca1e3f3b-764d-44f9-bc59-7dc2f56c28c7.png)

**Comment by ReneNulschDE** [comment]
Whats your car model?

**Comment by Marc1200** [comment]
Mercedes GLC 350e 4matic 2018.
I can see when a charger is plugged in at the Mercedes me app

**Comment by ReneNulschDE** [comment]
Could you enable the option "DEBUG ONLY: Enable save server messages to the messages folder" in the "Configure" dialog of the component? Restart HA, wait 2min, deactivate the option. 

Then compress the folder HA-Config-Dir/custom_components/mbapi2020/messages into a zip and send it to mb.dev-issue114@nulsch.de via email. 
And attach a diagnostic download of the component:

![image](https://user-images.githubusercontent.com/33263735/222392875-2f11d48e-5892-4877-be76-a557b8ec76ba.png)

**Comment by Marc1200** [comment]
I send you an email with the requested files.
