### ISSUE TITLE
State of Charge entity not visible on dashboard

### ISSUE THREAD

**Issue by cillin89** [ReneNulschDE/mbapi2020#124]
I'm using the default dashboard configuration in HA so no custom setup.
A few versions ago the 'State of Charge' entity disappeared from the dashboard.
The entity is still visible and working in the entities list however.

Any idea why it's not being added automatically anymore?

**Comment by ReneNulschDE** [comment]
Do you really run the dashboard in auto-mode or do you just added all the entities from the devices page? To check if you run in auto mode, just try to edit the dashboard and you should get a warning dialog. 

But to be open, I have no detailed knowledge in the lovelace dashboard tec and I'm quite unsure if I can help here. My code has no special logic and is using just the HA standards.

**Comment by cillin89** [comment]
I'm indeed running the auto-mode.
