### ISSUE TITLE
Configuration of integration fails with {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by westfeld** [ReneNulschDE/mbapi2020#125]
First of all let me thank for your great integration. I have installed it using HACS and it worked nicely with my car until it started burning CPU cycles and causing my home assistant to stall. After that I disabled the integration and removed it by deleting the directory in the custom_components folder. I also cleaned the MBapi files in the `.storage` folder in HA's configuration folder.

Now I would like to give it another try and reinstalled it via HACS but when I try to add the integration the configuration flow does abort with the message `{"message":"Invalid handler specified"}`.

I suspect that the first removal of the integration left the system in an unclean state. I would appreciate any hints how to fix that.

Thank you!

_Details about my HA installation_
It is running version 2023.1.7 and it is installed into an virtual environment running on Raspian 11.6.

**Comment by ReneNulschDE** [comment]
Please make sure that you have deleted the .mercedesme-token-cache file in the HA Config folder. And please check the logs for any other error messages and share it here.

**Comment by westfeld** [comment]
Thanks for the quick reply. I have already deleted the `.mercedesme-token-cache` file, but the error persists.

I get the following error message:

```
Error occurred loading configuration flow for integration mbapi2020:
cannot import name 'builder' from 'google.protobuf.internal'
(/opt/var/lib/hass/hass-3.9.env/lib/python3.9/site-packages/google/protobuf/internal/__init__.py)
```

**Comment by ReneNulschDE** [comment]
could you check the installed protobuf version? min version is 3.19.1

**Comment by westfeld** [comment]
I checked it and the protobuf version is 3.19.4

**Comment by ReneNulschDE** [comment]
ok, and what is the mbapi2020 version?

**Comment by westfeld** [comment]
I am running mbapi2020 version 0.9.1 installed via HACS.

**Comment by ReneNulschDE** [comment]
Sorry, I have to correct my protobuf statement. min version is 3.20.3

**Comment by westfeld** [comment]
Sorry for not responding faster. To upgrade the protobuf I had to update homeassistant to the current version, which made me compile python 3.10 on my RPi and recreating the virtualenv.

Now it is working as expected.
