### ISSUE TITLE
NodeJS or Similar help

### ISSUE THREAD

**Issue by thomasdye12** [ReneNulschDE/mbapi2020#129]
Hi, this is amazing I've been looking for something like this to allow me to control the car the official API is very locked down, I was wondering if you'd be able to help me make sense of how this works, I don't use home assistance, I kinda want something similar to a rest API, I will build that, but I just need some guidance on how your code works if that's okay and what I'm looking at

**Comment by thomasdye12** [comment]
I know this is not an issue, I could think of another way to reach out

**Comment by ReneNulschDE** [comment]
Hi Thomas,

The component has 3 main areas:
- Authentication - handled in oauth.py
- REST API on MB side to get master data and some special settings in api.py
- Websocket connect with protobuf objects transfered to get updates from MB Server side in client.py and websocket.py

In case you are more familiar with nodejs, take a look an the [iobroker integration ](https://github.com/TA2k/ioBroker.mercedesme) that is written in JS. 

In case you really want to understand the integration lets have a short call - write me an email mbapi.dev.issue129@nulsch.de

BR
Rene

**Comment by ReneNulschDE** [comment]
I will close this topic. contact me as described if you need more help.
