### ISSUE TITLE
switch for auxheat missing

### ISSUE THREAD

**Issue by danielrheinbay** [ReneNulschDE/mbapi2020#13]
# Rationale
The previous version of mbapipy used to have a switch for auxheat, see https://github.com/ReneNulschDE/mbapipy/blob/master/custom_components/mercedesmeapi/switch.py
Having a switch entity to start / stop auxheat makes it easy to integrate auxheat in Lovelace.

# As is
This new version has auxheat sensors (provided #12 is merged) and services to start and stop auxheat, but it doesn't have a switch (yet).

# To be
Take the sensors and services and turn them into a switch entity. Could be done manually using a [template switch](https://www.home-assistant.io/integrations/switch.template/), but it'd be much nicer if a switch came out of the box.

**Comment by ReneNulschDE** [comment]
Thanks Daniel, I’ll merge your PR later today. Currently, only the preheat and not the aux_heat services are implemented. Are you willing to test if I implement the auxheat services on on a special branch? If this works then the switch is simple.

**Comment by danielrheinbay** [comment]
Thank your for clarifying, @renenulschde. Absolutely willing to test :)

**Comment by ReneNulschDE** [comment]
hi @danielrheinbay ,

I have added the service in the master branch. Please check the services.

**Comment by danielrheinbay** [comment]
...and you've even implemented the switch in fb54579e9c490b089bd934d4cbff99e4c2da6efa -- thank you so much!
I have tested the switch and it works for me. It can turn the aux heat on and off.

`sensor.<car name>_auxheat_status` has these attributes:
car: <name>
vin: <vin>
value_short: inactive
value_description: inactive
retrievalstatus: VALID
timestamp: '2021-01-31T10:08:48'
auxheattime1: '14:15' (i.e. I've set this some days ago)
auxheattimeselection: '0' (i.e. the time selection isn't actually active, as it was used a few days ago)
auxheattime3: '00:00'
auxheatActive: false
auxheatwarnings: '0'
auxheattime2: '00:00'
friendly_name: <car name> Auxheat Status
icon: 'mdi:radiator'

`switch.<car name>_auxheat` has these attributes:
car: <car name>
vin: <vin>
retrievalstatus: VALID
timestamp: '2021-01-31T10:08:55'
friendly_name: <car name> AuxHeat
device_class: outlet

The last attribute, device_class, got me thinking: For now, switching the aux heat on and off works, which is awesome. However, Home Assistant sees the aux heat as an electrical outlet. Unfortunately, switches don't support the `device_class` attribute. So may be at some point we can implement a Climate component instead, see https://www.home-assistant.io/integrations/climate/ and https://developers.home-assistant.io/docs/core/entity/climate/ for details. Not the highes priority though, I guess ;)

**Comment by ReneNulschDE** [comment]
Thanks for testing, @danielrheinbay 

I have removed the outlet device_class from the switch again.

I will take a look on the climate component, but with lower Prio.
