### ISSUE TITLE
Support for more attributes

### ISSUE THREAD

**Issue by realPilotfish** [ReneNulschDE/mbapi2020#130]
The iobroker Mercedes Me integration shows the charging and refueling history (history.socjson, history.tankLevelJSON)
Would the be possible in mbapi2020 too?

**Comment by ReneNulschDE** [comment]
Hi Thomas,

as far as I know the MB-API-endpoints have no history endpoints. I do not know iobroker but I assume that the history is implemented with iobroker basis functionality.

The same exists in Home Assistant as long as you run with the default_config or you need the recorder and history component enabled in HA. With that you can use the HA-standard functionality to access historical data for the "fuel_level" or the "soc" sensor in this MBapi2020 component.

Please check the HA documentation:
[Standard History component](https://www.home-assistant.io/integrations/history/)
[Standard History stats component](https://www.home-assistant.io/integrations/history_stats/)
[and check the default History Graph card in the HA UI](https://www.home-assistant.io/dashboards/history-graph/)

Please let me know if this answers your request or please explain more in detail your use case.

Thx
Rene

**Comment by realPilotfish** [comment]
Good point, I really hadn't thought about that!
What you get in iobroker is a json which contains entries per completed charging, start, end, state before and after, amount.
I am in the process ob migrating to HA and don't habe a complete understanding of how to record such "self constructed"  historic data.
I will read through the informational links that you mentioned. 

Thanks a log for the integration and you support! :-)
