### ISSUE TITLE
Oil Level Percent unavailable

### ISSUE THREAD

**Issue by hav10** [ReneNulschDE/mbapi2020#132]
The oil level percent entity is now showing as not being provided by the integration.

This change happened at 03:00 24/07/2023

Version 0.9.2
HA 2023.6.2

Thanks

**Comment by ReneNulschDE** [comment]
Thanks for reporting. I can see this with my cars too. Let us wait a few days. Very often this is a problem on the MB server side.

**Comment by ReneNulschDE** [comment]
Hi, I checked the API messages and the oillevel is still missing. I can't see it in the official MB-app anymore. Lets see if it comes back.

**Comment by hav10** [comment]
Thanks for the update.

**Comment by Giuliointhetube** [comment]
Same here.

**Comment by PachangaDad** [comment]
Same here. As I have an open issue with MercedeMe Connect, I will inquire on specific Oil entry and report back. Stay tuned. :-)

**Comment by tbkon3** [comment]
Same here

**Comment by ReneNulschDE** [comment]
With the next release, the oil level sensor gets removed as it looks like that MB has removed this information from the data structure.

**Comment by PachangaDad** [comment]
Ha Ha, I guess we don’t need to worry about oil changes and any oil leakage in the future!

I hope they modify their warranty coverage to the same talking points !

 

PachangaDad

**Comment by ReneNulschDE** [comment]
The data is not provided by the MBAPI anymore. Sensor removed in v0.9.6
