### ISSUE TITLE
charging cable connected sensor - addition request

### ISSUE THREAD

**Issue by WimGo** [ReneNulschDE/mbapi2020#134]
Kind request to add the sensor that indicates whether or not an electric charging cable is plugged into the car.
This would allow me to enhance my Home Assistant code to control the car charging.
Thanks for this great integration,
Wim

**Comment by ReneNulschDE** [comment]
The sensor RangeElectric has an attribute Charging status. Values are explained here: https://community.home-assistant.io/t/mercedes-me-component/41911/590

Let me if this is enough or you need more help.

**Comment by ReneNulschDE** [comment]
Sorry, here is a link with all potential values

https://github.com/mercedes-benz/MBSDK-CarKit-iOS/blob/cbe02fc1322a6e7278b5ad1a3faafde2f36177c4/MBCarKit/MBCarKit/Common/Enums/Status/ZEVTypes.swift#L93

**Comment by WimGo** [comment]
Thanks Rene for the prompt and clear answers.
Problem solved.
