### ISSUE TITLE
Possible to get end of charge time week day

### ISSUE THREAD

**Issue by DragonNZ** [ReneNulschDE/mbapi2020#135]
Hi,
I am using your component in NZ. Works really well, thank you!

Would it be possible to get endOfChargeTimeWeekday as when using the 2Kw charger, it can take a day or two so the time alone is not enough.
The other one that would be great to have is maxSoc to know what charge we are aiming for.

Great work. Thank you for your work and support!

**Comment by DragonNZ** [comment]
Apologies, I found the maxSoc, but I don't see the endOfChargeTimeWeekday.

**Comment by ReneNulschDE** [comment]
Added a new attribute to Odometer and RemoteStartActive Sensors in the latest version 0.9.4
