### ISSUE TITLE
proto files

### ISSUE THREAD

**Issue by weymann** [ReneNulschDE/mbapi2020#136]
First: Sorry for _misuse_ this issue as a question!

I'm a developer in the openHAB project and provide the _MercedesMe binding_ to serve data for Mercedes vehicles. It's based on the _Developer Mercedes API_ which you may know will be shut down soon. Therefore I found your solution with the **SDK approach**.

Thanks to your repo I was able to rewrite my current implementation:

- PIN request - working
- Token request - working
- Build websocket - working
- receiving data - working

But now I'm struggeling decoding the received data. Looks like you generated the protobuf code based on proto files which are not available in this repo.
Would you be so kind to share these files me in order to bring my binding to life again? I would be so happy to have my Mercedes online again in my Smarthome environment!

**Comment by ReneNulschDE** [comment]
Hi Bernd,

Take a look in this repo

https://github.com/ReneNulschDE/MBSDK-CarKit-iOS/tree/master/Proto


Let me know when you need more help.

BR
René

**Comment by weymann** [comment]
Ah, perfect. 
First tests are ok so now I can finish my implementation
