### ISSUE TITLE
Efter indlæsning af sikkerhedskopi.

### ISSUE THREAD

**Issue by Viblabdk** [ReneNulschDE/mbapi2020#138]
virker integrationen ikke længere.

Har reloaded men det samme.

Hvor og hvordan finder jeg filen:

Backup and Restore

In case of problems after a restore of Home Assistant, please delete the file .mercedesme-token-cache in your HA-config folder and restart HA

**Comment by ReneNulschDE** [comment]
Please check my answer to your post in the ha community portal.
