### ISSUE TITLE
Sunroof status disappeared 

### ISSUE THREAD

**Issue by euroman2007** [ReneNulschDE/mbapi2020#139]
Hi,
My sunroof status disappeared in home assistant.
It also isn't possible to open or close my sunroof with home assistant anymore. Anyone else having this problem?

**Comment by ReneNulschDE** [comment]
Hi, the sunroof can be opened only if the car was not unlocked via keys (same like the official app)

If the car is closed and locked the sunroof open service works for me.

Please first check if the official app is working. Could be too that one of your licenses is expired.

**Comment by euroman2007** [comment]
Thanks for your reaction,
I am missing the sensors and entities entirely.
The license should not be the problem they are active until the end of 2025. Through the app the function works. I never use my key to lock or unlock the car. So that should not be the issue either. I have also reinstalled your app. But it didn't help unfortunately. Any ideas ?

**Comment by ReneNulschDE** [comment]
Can you first check if the HA service "mbapi2020.sunroof_open" / close is working when the car is closed and locked? If this doesn't work, what is the error message in the log

**Comment by euroman2007** [comment]
Thanks for your response, in the service section I can use the function to open and close the sunroof. Without problems. But if I check within my entities the function is not there. Open and close windows are there but the sunroof function not.. the reason why I ask is because they were there before. And I had made an Automation witch closed my car windows and the sunroof if any of them where open. Because sometimes you have people in the back they always forget to close the windows 😑

**Comment by ReneNulschDE** [comment]
Then you have to check your custom sensors (template?) - the component has no dedicated sunroof sensor out of the box.

**Comment by euroman2007** [comment]
Thank you very much. I never used costum sensors for it. But I'm gonna take a look. Greetings Fernando
Thanks for your time and great support
