### ISSUE TITLE
Cannot request PIN

### ISSUE THREAD

**Issue by xorob0** [ReneNulschDE/mbapi2020#14]
Hi, I'm in Belgium and I am trying to connect HA to Mercedes ME. I installed this component using HACS on a Raspberry Pi 4. Everything seems to be installed correctly but when I try to connect nothing happens and I am stuck on the inputs for the email and the server.
I have these logs:
```
Logger: custom_components.mbapi2020.oauth
Source: custom_components/mbapi2020/oauth.py:229
Integration: MercedesME 2020 (documentation, issues)
First occurred: 20:03:18 (9 occurrences)
Last logged: 20:11:35

Error requesting data from https://bff-prod.risingstars.daimler.com/v1/login: 400, message='Bad Request', url=URL('https://bff-prod.risingstars.daimler.com/v1/login')
Error requesting data from https://bff-prod.risingstars-amap.daimler.com/v1/login: 400, message='Bad Request', url=URL('https://bff-prod.risingstars-amap.daimler.com/v1/login')
```
I tried using different servers and even a phone number but I always have the same errors.

Thanks in advance for your help
Tim

**Comment by ReneNulschDE** [comment]
Thanks for reporting this. MB has changed the login procedure a little bit. I'll fix it over the weekend.

**Comment by ReneNulschDE** [comment]
I have published a Pre-Release v.0.5.1b. This should support the new authentication model in Europe.

**Comment by xorob0** [comment]
Thanks a lot ! I'll try it.

**Comment by xorob0** [comment]
Thanks man it's working ;)

**Comment by tgregory86** [comment]
I get the same issue for the US/North America.

**Comment by ReneNulschDE** [comment]
Please retest with the new Prerelease v0.5.1b2. Should work again
