### ISSUE TITLE
china device track gps location is not right

### ISSUE THREAD

**Issue by luckywaa** [ReneNulschDE/mbapi2020#140]
I think the problem is china need transform coordinate between earth(WGS-84) and mars in china(GCJ-02)
![image](https://github.com/ReneNulschDE/mbapi2020/assets/8738803/54b2d5e3-e5c7-4047-890d-216a06e0f9f5)

**Comment by ReneNulschDE** [comment]
with the code in the master branch, the component has now the option to activate the GCJ-02. Let me know, if you can test this.

The option is in the configure dialog.
![image](https://github.com/ReneNulschDE/mbapi2020/assets/33263735/b1ebe20b-9205-4d7e-bca0-aeac5fc982b2)

Please restart HA or Reload the component after activating this setting.

**Comment by ReneNulschDE** [comment]
Part of the 0.9.4 release

**Comment by luckywaa** [comment]
> Part of the 0.9.4 release

the problem is not fixed. 
I think it need to trans GCJ-02 to WGS-84, not the other way.
![image](https://github.com/ReneNulschDE/mbapi2020/assets/8738803/d5d87f86-da42-4cf5-ac64-4f9958aafa9b)

**Comment by luckywaa** [comment]
perhaps you can use this method
https://github.com/gaussic/geo_convert/blob/master/converter.py
