### ISSUE TITLE
Cannot change atrribute value "Bar" to kPa" for Tire Pressure

### ISSUE THREAD

**Issue by iHaveAstream** [ReneNulschDE/mbapi2020#141]
Hi,

first of all  many thanks for this awesome custom integration, good job! Really like it and appreciate your efforts @ReneNulschDE!

I'm using the latest version of the integration in HA 2023.10.0.
Works as it should for/with my S206, except for the values of tire pressure.
In the integration they will be declared in "Bar", rather than kPa. Resulting in having a tire pressure with xxx Bar, by far too much ;)

I tried to change the attribute values of each tire pressure sensor entity from Bar to kPa and clicked "Update", however, the change will not be saved/reflected. It stays on Bar. Pls.  see attached screenshot.

Thanks!
![Screenshot_20231006-211847_Home Assistant](https://github.com/ReneNulschDE/mbapi2020/assets/62019393/7b46f65f-361c-44a6-b0cc-a0317ecd99d3)

**Comment by toSvenson** [comment]
I can confirm the issue HA 2023.10.0 and mbapi2020 0.9.4

**Comment by ReneNulschDE** [comment]
The unit is defined in the official Mercedes me app. Please check your settings and change it there from Bar to kPa.


MBApp:
![image](https://github.com/ReneNulschDE/mbapi2020/assets/33263735/2c969e00-1391-4248-b55b-948f19c8b711)

Result:
![image](https://github.com/ReneNulschDE/mbapi2020/assets/33263735/375691ae-03b4-4f6b-8e10-4573f76c2d2c)

**Comment by iHaveAstream** [comment]
Hi,

yes, in the app the unit can be changed, but on the other hand, also bar will be declared with correct values:
![SmartSelect_20231007_083349_Mercedes me](https://github.com/ReneNulschDE/mbapi2020/assets/62019393/04260566-17ac-446e-97d5-46f8fd232524)

**Comment by ReneNulschDE** [comment]
The correct value will be shown in the next release (give me a few minutes). Is fixed in the master branch already.

**Comment by ReneNulschDE** [comment]
fixed in Release v0.9.5

**Comment by iHaveAstream** [comment]
> fixed in Release v0.9.5

Works like a charm!
Many thx @ReneNulschDE 

![Screenshot_20231007-183423_Home Assistant](https://github.com/ReneNulschDE/mbapi2020/assets/62019393/28b8bdc1-3730-4ec8-934b-a09557a2773c)
