### ISSUE TITLE
china gps trans not fixed

### ISSUE THREAD

**Issue by luckywaa** [ReneNulschDE/mbapi2020#142]
> Part of the 0.9.4 release

the problem is not fixed. 
I think it need to trans GCJ-02 to WGS-84, not the other way.
I bought Gaode Map service in China, the mercedes api return GCJ-02 of china, but in HA, it used WGS-84, so we need trans GCJ-02 to WGS-84 to support HA

_Originally posted by @luckywaa in https://github.com/ReneNulschDE/mbapi2020/issues/140#issuecomment-1750668668_

**Comment by ReneNulschDE** [comment]
I have flipped the conversion to GCJ-->WGS

**Comment by luckywaa** [comment]
it worked. thank you for your contribution.
