### ISSUE TITLE
Pre-climate control switch

### ISSUE THREAD

**Issue by afrojaner** [ReneNulschDE/mbapi2020#145]
Hey, first of all, thank you for your work. The setup worked as described and I get 39 entities displayed on my c300e. what do I have to do to get a pre-air conditioning switch?

**Comment by ReneNulschDE** [comment]
Hi,

The component has no switch for the preconditioning yet. You can use the HA-services in the mbapi2020 namespace and build your own button with the HA standard functionality. 

Take a look at the HA forum, there are multiple samples in the mbapi2020 thread.
