### ISSUE TITLE
Start parking heater not shown E 300 de Hybrid

### ISSUE THREAD

**Issue by eikebecher** [ReneNulschDE/mbapi2020#147]
Hi,

should ist be possible to start the parking heater for a hybrid car? It is not shown in my entities. 

Thanks in advance
Eike

**Comment by ReneNulschDE** [comment]
Hi Eike,

As far as I know the cars have to two options:
1. preclimating (preheating) - based on the battery 
2. Auxiliary heating (Standheizung) - based on a second device with petrol

For these two options you will find services in HA to start / stop the activity. Take a look at the available services in the mbapi2020 namespace.

Let me know if you have third something in your car and share the screenshots out of the MB App.

BR
René

**Comment by eikebecher** [comment]
Hi Rene,

thanks for your message.
For my car preclimating should be available. But I can not find it in HA.

**Comment by ReneNulschDE** [comment]
Hi,

As I said, there is a HA service to control this. The component has no explicit switches or buttons for this and yes, you can easily implement this with the standard HA functions. Take a look at the HA services list.

![image](https://github.com/ReneNulschDE/mbapi2020/assets/33263735/b0d04348-ff06-4183-9850-4301a457e967)

**Comment by ReneNulschDE** [comment]
No further feedback
