### ISSUE TITLE
AdBlue Füllstand anzeigen

### ISSUE THREAD

**Issue by xs400dohc** [ReneNulschDE/mbapi2020#151]
Hallo Herr Nulsch,

erst einmal besten Dank für Ihre gute Arbeit mit der Integration.

Bei mir läuft alles auf Anhieb. Was ich allerdings leider vermisse, ist eine Anzeige des AdBlue-Füllstands. Das war für mich der eigentliche Grund, die Integration zu installieren, um mir anzuzeigen, wann der nächste Kanister in den Tank passt. So muss ich immer in der App nachgucken.

Falls Sie noch weitere Informationen benötigen, stehe ich gerne zur Verfügung.

Liebe Grüße

xs400dohc

**Comment by ReneNulschDE** [comment]
Hallo @xs400dohc ,

AdBlue Füllstand in % ist ein Attribut des Sensors "Odometer". Das Attribut heisst "TankLevelAdBlue".

Grüße
Rene

**Comment by xs400dohc** [comment]
Hallo Rene,

besten Dank für die super schnelle Antwort.

Das hilft mir schon sehr weiter. Jetzt muss ich nur schauen, wie ich daraus eine Entität mache. Habe da schon mal was darüber gesehen. Muss ich jetzt nur noch wiederfinden ;-) 

Nochmals besten Dank und weiterhin viel Spaß/Erfolg bei Ihrer super Arbeit

xs400dohc

**Comment by ReneNulschDE** [comment]
Hi, 

einfachste Möglichkeit ist unter "Devices & Services" einen Helper vom Typ Template zu erstellen. 

Template:` {{ state_attr("sensor.XXXXX_odometer", 'tankLevelAdBlue') }} `

Ersetze XXXXX gegen deinen Namen.

**Comment by xs400dohc** [comment]
Hallo,

jetzt wo Sie es sagen kommt die Erinnerung.

Besten Dank für den Hinweis
