### ISSUE TITLE
Mercedes Me sensors offline

### ISSUE THREAD

**Issue by vistalba** [ReneNulschDE/mbapi2020#152]
Hi together

I run this integration since a few months. Got a new car last week and updated the config to get the new cars information.
Everything was working well until 23. November at 09:02. 
Since then all sensors are unavailable. And beside of that, also in the Mercedes me app everything is offline and not available :(

I want to ask if anyone else has similar issues? May this integration spammed the API and I got banned?

**Comment by ReneNulschDE** [comment]
Hi, if it's not working in the MB App then call the MB Support and try to get the app running again. Afterthat your integration should work again. Most often this is a problem with account linking.

This integration is acting like the MB app and I have never heard that the integration produced problems with the MBApp.

**Comment by Jealy91** [comment]
I contacted support about this over a week ago, they said it's a known issue at the moment.

> Thank you for contacting Mercedes-Benz about the issue you face with the remote information of your vehicle. We are sorry for the inconvenience. Its a known issue and at the moment the technical department is trying to resolve it and implement the solution.

**Comment by vistalba** [comment]
Called the support line today. They told me the same.
No information when this will be fixed.
I tried to re-add the car at all to the Mercedes Me account.
Now stuck on „activation…“ of the services. Was probably not a good idea. :-(

**Comment by Jealy91** [comment]
Was considering calling them soon too, thanks for that.

Really annoying actually as I went to drive yesterday and my tyre was flat! If I had the app integration working it would have told me much earlier that I had a puncture! Typical.

**Comment by StefanHesse** [comment]
For me the App is working perfectly, but the HA Integration is not updating since "26. November 2023 um 23:07:26"
I could open a case with MB, but they will not work on it because the App is working perfectly i guess. Any ideas how i could solve this problem?

**Comment by ReneNulschDE** [comment]
Hi,

Whenever that is working that we have to dive deeper with this integration. Could you enable debug logging, share more details about your environment and more detailed error description?

**Comment by StefanHesse** [comment]
Of course. I started debug logging now. How long should i let this run before sending you the data?
I updated my HA to version 2023.11.3 on November, 23rd and the integration worked after that update until November 26th.
I have an automation sending the SoC to an openWB wallbox, but this automation is not triggered becaused the mbapi2020 does not update the SoC. It is fixed at 80%.
What else do you need?

**Comment by ReneNulschDE** [comment]
@StefanHesse : Lets discuss this in a new issue as the problem is different from my perspective. #154

**Comment by mafde2023** [comment]
Same problem here, Mercedes me in the car, app and HA stopped working yesterday afternoon. Wrote an email to CAC today morning, no feedback yet....

**Comment by ReneNulschDE** [comment]
As we have more and more messages about this problem: Could you check if the deletion of the Token-file ([see here](https://github.com/ReneNulschDE/mbapi2020/issues/154) solves the problem with the integration? If, yes, then a logoff in the app could help there too.

**Comment by vistalba** [comment]
> As we have more and more messages about this problem: Could you check if the deletion of the Token-file ([see here](https://github.com/ReneNulschDE/mbapi2020/issues/154)) solves the problem with the integration? If, yes, then a logoff in the app could help there too.

Tried multiple times in the past 5 days. No luck.

**Comment by mafde2023** [comment]
I have done full reset incl. wipe of all data of the official Mercedes me App, but still doesn't work. As far as that won't work, I don't expect HA integration to work again.

**Comment by mafde2023** [comment]
A colleague have me the advice to check the approval of the data protection guidelines. What should I say, after login to Mercedes me web portal I had to accept again all data protection guidelines and just afterwards the app started to work again, but not having all information available..... Unfortunately HA doesn't work yet, but I think I first have to drive some minutes with the car again to sync all settings and status information again to the backend of Mercedes. Will do that tomorrow and give feedback again.

**Comment by Jealy91** [comment]
My app started working this evening, looks like Mercedes have fixed their services.

Reloaded the integration in Home Assistant and everything came to life.

**Comment by bbird8** [comment]
Same issue here out of the blue this morning. 
Sensors unavailable. Nothing changed locally. 
App seems still working.

**Comment by vistalba** [comment]
@ReneNulschDE Can‘t test as I‘m on a business trip without the car. Will report when I‘m back.

**Comment by nicolaus-hee** [comment]
Update to 0.9.8 did the trick for me.

I was facing the issue with 0.9.6. Had deleted the config but could not re-login ("unknown error" after providing e-mail address). Worked again after update to 0.9.8 via HACS.
