### ISSUE TITLE
SOC gets not updated

### ISSUE THREAD

**Issue by ReneNulschDE** [ReneNulschDE/mbapi2020#154]
Of course. I started debug logging now. How long should i let this run before sending you the data?
I updated my HA to version 2023.11.3 on November, 23rd and the integration worked after that update until November 26th.
I have an automation sending the SoC to an openWB wallbox, but this automation is not triggered becaused the mbapi2020 does not update the SoC. It is fixed at 80%.
What else do you need?

_Originally posted by @StefanHesse in https://github.com/ReneNulschDE/mbapi2020/issues/152#issuecomment-1829676924_

**Comment by ReneNulschDE** [comment]
@StefanHesse:
I just checked this with my car and the SoC gets updated. So it is not a generall problem. Let us try the simple things first:

1. Quit Home Assistant (HA)
2. Delete the file .mercedesme-token-cache in the config folder of HA
3. Restart HA
4. A warning (task) appears in the frontend that the MBAPI2020 component has to log on again. Carry out these steps. (with the same account as in the MB app)
5. Test

If this does not work:

1. Activate the option "DEBUG ONLY: Enable save server messages to the messages folder" in the configuration dialogue of the component
2. Click on the "Enable Debug Logging" function on the integration overview page
3. Restart HA
4. Wait 2min
5. Deactivate the option "DEBUG ONLY: Enable save server messages to the messages folder" in the configuration dialogue of the component
6. Click on the "Disable debug logging" option on the integration overview page and save the file that is offered for download
7. Compress all files in the HA-Config-Folder/custom_components/mbapi2020/messages folder into an archive
8. Send the files from points 6 and 7 by email to mbdev.issue-154@nulsch.de

**Comment by StefanHesse** [comment]
I have HA running within a Virtual machine on my Synology NAS. How can I quit HA and delete the token?
If i shutdown HA the Virtual machine is off and i do not know how to delete a file on the virtual disk.
Sorry for asking, but this is not my day 2 day business :-)

**Comment by ReneNulschDE** [comment]
When you create the docker environment on your NAS, you normally define folders for your configuration data and this is stored on your normal NAS discs. You can use the NAS explorer to go to this folder and delete the data. 

What was the tutorial that you used to set this up?

**Comment by ReneNulschDE** [comment]
Otherwise you can go to the configure dialog of the MBAPI2020 component and select the second last checkbox "Delete authentication token file now. require a restart of Home Assistant after save." Then restart HA
