### ISSUE TITLE
Unknown error occured

### ISSUE THREAD

**Issue by marcert** [ReneNulschDE/mbapi2020#160]
Hi,
the integration worked great the last weeks. Today I've update HA and afterwards it stopped working.
I've deleted the integration, restarted HA and now trying to add it again. But after entering the mail adress I get
"Unknown error occured".
Has somebody an idea what might happened there?
Thanks!

**Comment by ReneNulschDE** [comment]
Please update to the latest version and check again. See [here](#159 ) or [here](https://community.home-assistant.io/t/mercedes-me-component/41911/1656).

**Comment by marcert** [comment]
thanks for the quick help! Update solved it. I was only surprised that I had to do the update manually. For other (HACS) integrations I got extra information about updates.

**Comment by ReneNulschDE** [comment]
yeah, the update was published few minutes ago - and it need some time until it show up in HACS
