### ISSUE TITLE
Entities gone offline....

### ISSUE THREAD

**Issue by Begie1605** [ReneNulschDE/mbapi2020#161]
Hey From time to time (every couple of weeks) the integration stops working, no new values enter.
Did a reload but then entities go to unavailable.

Only solution up till now i found was to remove integration, restart HA, add integration again...and then it works again.
Except that everytime i do this somehow the charge power entitiy is not there anymore...and sometimes it popup after a second reinstall...

All on the latest verisons of ha, but was also the case on previous version.
BTW. I'm using the car in the EU

**Comment by ReneNulschDE** [comment]
Hi @Begie1605 ,

Its hard to judge without detailed logging. 

I would propose that you enable the debug log level for the component. Check the readme at the end. When the error is occurring next time we can dive deeper and check the logs. I'm interested to see what happens before and after the error. 

BR
Rene

**Comment by Begie1605** [comment]
Hey Rene,
totaly understand this....i'm going to install it from scratch again...and then enable the logging...next time i have the problem i will send the logs over...

In any case thnx for the answer already....

**Comment by dennzs** [comment]
Did this happen to you about one hour before you posted? Mine went offline as well at 16:04 EET so three hours 20 minutes ago.

**Comment by dennzs** [comment]
Ah sorry I only saw the other teapot error just now.

https://github.com/ReneNulschDE/mbapi2020/issues/159

**Comment by vistalba** [comment]
All my entities are „not available“ since 3h now. No change at all… just went offline.

**Comment by ReneNulschDE** [comment]
Did you installed the update today? If not please do it. If yes, what’s your region? Share the debug and diagnostic logs.

**Comment by vistalba** [comment]
@ReneNulschDE After update it is working fine again.

**Comment by veitw** [comment]
Just discovered the same issue, after update it works again.  Thanks @ReneNulschDE

**Comment by mafde2023** [comment]
Haveing same issue since yesterday. Which update should I install? HA or Custom Component? Didnt see any description how to update in documentation here

**Comment by ReneNulschDE** [comment]
This component.

**Comment by mafde2023** [comment]
How to update? Simply reinstall from HCAS and configure newly? Didnt see any update mechanism to keep configuration.

**Comment by Begie1605** [comment]
> Hi @Begie1605 ,
> 
> Its hard to judge without detailed logging.
> 
> I would propose that you enable the debug log level for the component. Check the readme at the end. When the error is occurring next time we can dive deeper and check the logs. I'm interested to see what happens before and after the error.
> 
> BR Rene

Hi,
i just updated to the latest version...removed token file, restarted and readded...
I also added the logging settings...
I have now charge power first directly available as entity...

Next time entities stop updateing, if there is, i will collect the logs and send them over...
Rgds
Benny

**Comment by ReneNulschDE** [comment]
> How to update? Simply reinstall from HCAS and configure newly? Didnt see any update mechanism to keep configuration.

Just update via HACS and restart HA. The configuration is handled via the HA platform. In case of problems open a new issue please. The problem that we discuss here is a different one.

**Comment by ReneNulschDE** [comment]
> Next time entities stop updateing

Thanks Benny. I will close this issue for now to reduce noise and you can reopen it when the problem happens again or send an email to Mbdev.issue161@nulsch.de
