### ISSUE TITLE
Can't connect to the API

### ISSUE THREAD

**Issue by DragonNZ** [ReneNulschDE/mbapi2020#162]
Hi,

I had to reconnect, so deleted the token as per documentation.
When I try to reconnect, it reports that there was an error.
This is in the log
![image](https://github.com/ReneNulschDE/mbapi2020/assets/4507081/5cc20a76-aaae-4074-982b-5d999f982c6b)

This error originated from a custom integration.

Logger: custom_components.mbapi2020.oauth
Source: custom_components/mbapi2020/oauth.py:224
Integration: MercedesME 2020 (documentation, issues)
First occurred: 8:08:30 PM (3 occurrences)
Last logged: 8:32:52 PM

ClientError requesting data from https://bff.amap-prod.mobilesdk.mercedes-benz.com/v1/login: 418, message="I'm a teapot", url=URL('https://bff.amap-prod.mobilesdk.mercedes-benz.com/v1/login')

Any idea to what is going wrong?

Thanks,
  John

**Comment by ReneNulschDE** [comment]
Please update to version v0.9.8. This was fixed last Friday.

**Comment by DragonNZ** [comment]
A

**Comment by DragonNZ** [comment]
closinf
