### ISSUE TITLE
binary.sensor.xxxxxx_windows_closed reports as open when windows are closed 

### ISSUE THREAD

**Issue by BobD61** [ReneNulschDE/mbapi2020#163]
windows closed sensor is showing as open when all windows are closed

Retrievalstatus
VALID
Timestamp
19 December 2023 at 13:01:25
Windowstatusfrontleft
2
Windowstatusfrontright
2
Windowstatusrearleft
2
Windowstatusrearright
2

![image](https://github.com/ReneNulschDE/mbapi2020/assets/76821747/fb921dd0-2ce1-4943-94f0-56ca993ffd37)

**Comment by BobD61** [comment]
This is using v0.9.8 of the integration

![image](https://github.com/ReneNulschDE/mbapi2020/assets/76821747/a4fce93e-9d59-48f0-b58a-f1b912eb5ae7)

**Comment by ReneNulschDE** [comment]
Could it be that you set the device_class: window manually in the HA frontend? My code does not create this setting and the device-class is the reason for this behavior.

**Comment by BobD61** [comment]
That was it - clearing device_class and it now correctly shows state on.

Thanks for your help
