### ISSUE TITLE
Lost device tracker for my mercedes

### ISSUE THREAD

**Issue by bobofruit1970** [ReneNulschDE/mbapi2020#167]
Since some time I lost device tracker entities for my mercedes:
device_tracker.wa7114a_device_tracker

wa7114a is the name of my mercedes.

Why my HA does not report existance of device tracker for my mercedes?

Does something changed according to device tracker in mbapi2020 integration?.

**Comment by ReneNulschDE** [comment]
Hi, let first check if the official MB App shows the car on the map. Very often the license to use this feature is just expired.

**Comment by bobofruit1970** [comment]
Official MB app shows the car position last updated 13.11
You right.
Thanks.

**Comment by bobofruit1970** [comment]
The official response from MB in brief.
"Due to the shutdown of the 3G network in the EU for cars equipped only with 2G/3G modem modules, MB will gradually disable the vehicle location service. After the end of the contractual period of operation of the service, it will not be extended."
