### ISSUE TITLE
Is there a way to change how often the plugin queries the API?

### ISSUE THREAD

**Issue by nthbooth** [ReneNulschDE/mbapi2020#169]
Hello first of all this is a great plugin I really like it.

I am using it for my smart fourfor electric on the same Mercedes me platform as other Mercedes cars.

Over the last week, I have been monitoring the car battery level (remember it has a very small battery compared to other cars) and I have noticed a decrease in the charge which I have not seen before. 

I assume this is caused by this plugin waking up the car each time it queries the API..

Is there any way to set how often the API is queried? Ideally, I would be doing it once an hour or something minimal like that.

thank you in advance.

Nick

**Comment by ReneNulschDE** [comment]
Hi, the component is using a push approach. Means that whenever the MB servers have a new status for the car the component gets informed about the new status. Means also that the component is not querying any car values. Therefore, I assume that the component has no impact on your car battery.

**Comment by nthbooth** [comment]
Thank you

**Comment by nthbooth** [comment]
Thank you closing ticket
