### ISSUE TITLE
service(unlock door)  VIN unknown or feature not availabe for this car.

### ISSUE THREAD

**Issue by inganyoyo** [ReneNulschDE/mbapi2020#17]
Dear ReneNulschDE,

I am living in Korea.

A problem occurred when i request service in to use the component you created.

service: mbapi2020.doors_unlock
data:
  vin: W1KZF8XXX

thx
--debug log--
Logger: custom_components.mbapi2020.client
Source: custom_components/mbapi2020/client.py:433
Integration: MercedesME 2020 (documentation, issues)
First occurred: 오후 6:40:08 (1 occurrences)
Last logged: 오후 6:40:08

Can't unlock car W1KZF8XXX. VIN unknown or feature not availabe for this car.

**Comment by ReneNulschDE** [comment]
Hi,

this error gets logged in two cases:
1. The VIN is wrong. --> You can find the VIN in all the sensor dialogs. (Normally all in UPPERCASE)
2. The compnent checks if your car has the option to unlock. You can disable this check in the options of the integration. 

Please check the two Points and test again.

**Comment by inganyoyo** [comment]
Dear ReneNulschDE,Dear ReneNulschDE,

"The compnent checks if your car has the option to unlock. You can disable this check in the options of the integration."

do you mean  "Disable capabilities check"?

**Comment by ReneNulschDE** [comment]
yes

**Comment by inganyoyo** [comment]
when i checked "Disable capabilities check", works good.
thx~!
