### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by geryduyck** [ReneNulschDE/mbapi2020#172]
I noticed that the integration was disconnected since a while, so I tried to remove and reconnect.
Unfortunately, it is no longer possible to link my mercedes account, and I retrieved the following error from the logs.

I assume the login protocol from mercedes has changed and can no longer be used the way it was by the add on.

This error originated from a custom integration.

Logger: custom_components.mbapi2020.oauth
Source: custom_components/mbapi2020/oauth.py:224 
Integration: MercedesME 2020 (documentation, issues) 
First occurred: 16:27:26 (5 occurrences) 
Last logged: 16:28:57

ClientError requesting data from https://bff.emea-prod.mobilesdk.mercedes-benz.com/v1/login: 418, message="I'm a teapot", url=URL('https://bff.emea-prod.mobilesdk.mercedes-benz.com/v1/login')

**Comment by ReneNulschDE** [comment]
Hi @geryduyck, looks like you are not using the latest release. This was fixed with v0.9.8... Please update,

**Comment by geryduyck** [comment]
You are completely right! My mistake, I overlooked the updates from HACS, when performing my monthly routines.
Works like a charm! thanks /closed
