### ISSUE TITLE
2 Mercedes Me Accounts -> 1 car is thrown out?

### ISSUE THREAD

**Issue by sweti3** [ReneNulschDE/mbapi2020#173]
hi,

I tried adding anouther hub (2. account) to the mercedes me integration. When I did that, one car was working, the other one went completely unavailable? Is this normal? 

Can we have this feature? Or is this just a home assistant feature that needs to be implemented still? Thanks for any help...

Sven

**Comment by ReneNulschDE** [comment]
Hi Sven,

a 2nd account is not supported. You can use the secondary driver option in the MB-Portal to invite your master account as driver of the second car. Then the second car is listed under your master account and is accessible in HA too.

BR
Rene

**Comment by sweti3** [comment]
Aaah damn it. Sorry, I thought this "add a Hub" was by design! this can be closed, sorry for the inconvenience Rene, thank you so much for your work!
