### ISSUE TITLE
Preheat indicator statys on

### ISSUE THREAD

**Issue by dennzs** [ReneNulschDE/mbapi2020#174]
The heater indicator usually stays ON for my EQB. The toggle itself does seem to work so I can turn it off and on but it will show as ON after having been on and turned off automatically. What could cause this?

**Comment by ReneNulschDE** [comment]
Do you mean the aux heater? The EQB has no aux heater normally, use the preclimate features of the component.

**Comment by dennzs** [comment]
Hi, I mean the preheat. 
<img width="575" alt="image" src="https://github.com/ReneNulschDE/mbapi2020/assets/78496184/9c71693d-7ab0-43cd-95e0-afb0fd84ce42">

It will get stuck "ON" like this. Activating and deactivating works but it doesn't always (usually) update in Home Assistant (nor to Homekit through it of course)

<img width="496" alt="image" src="https://github.com/ReneNulschDE/mbapi2020/assets/78496184/6b377f48-e51c-45b9-82e8-740ce0d21e14">

**Comment by dennzs** [comment]
I tested it some more and I think Home Assistant just stays in the last state that HA set so it gets confused when it's done through the MB app? Something with state updating FROM MB API

**Comment by ReneNulschDE** [comment]
Can you share the configuration of this switch? This is nothing that the component provides. I assume you have created this switch. You need to check the attributes precond_now or precond_active of the range_electric sensor. (or take a look in the HA-forum for example here: https://community.home-assistant.io/t/mercedes-me-component/41911/1652

**Comment by dennzs** [comment]
Hi. You're right of course, I completely forgot that I had created this using a template. I was missing the value_template so it was just sending the commands but not updating. 

Works perfectly now. Thank you very much!
