### ISSUE TITLE
Rename of integration entity is not renaming all sensors

### ISSUE THREAD

**Issue by dm82m** [ReneNulschDE/mbapi2020#175]
Hey Rene,

thanks for your integration. Just got my new car, removed the old one and added the new one and renamed the integration. It then asks if it should rename all car entities. Answered that with yes. As result only a few are renamed and the rest of the entities stays the old name.

Best,
Dirk

**Comment by ReneNulschDE** [comment]
Hi Dirk,
I have never done this or seen this option to rename. Could you you share some details? I would propose to delete the integration and readd it to have a clear state.
BR
Rene

**Comment by ReneNulschDE** [comment]
Thx, never saw this pin in the corner :-) Let me try to understand this in an test environment...

**Comment by dm82m** [comment]
I am changing my car each year. A few of my automations and also my solar charging depends on specific sensor names. Due to that reason I prefer renaming the sensors in your integration instead of changing multiple in my different config files. This is also very error-prone. Currently I manually renamed all the sensors, but it would be great if it just works out of the box with the embedded renaming feature. again, thanks for all your work!

**Comment by ReneNulschDE** [comment]
Can you share an screenshot example where this not worked well? I have just done it my test and it renamed all sensors of one of my cars.  Whenever this contains private information then you can send it to mbdev.i175@nulsch.de too.

**Comment by dm82m** [comment]
haha. damn it but it works now. I removed the integration configuration, re-added the car, renamed as described and it works. testet it on 16.01. three times the same way but it renamed only a few. no idea why. sorry for bothering you for no reason.
