### ISSUE TITLE
European market - Pin code request not working

### ISSUE THREAD

**Issue by ReneNulschDE** [ReneNulschDE/mbapi2020#177]
Guten Tag, ich versuche, Mercedes ME 2020 zu verwenden. Ich gebe die E-Mail-Adresse ein, erhalte jedoch keine PIN. Ich bin in Italien und habe Europa ausgewählt. Während ich für andere Leute gelesen habe, habe ich mich von der App und der Webseite abgemeldet, erhalte aber immer noch keine PIN. Können Sie mir ein paar Hinweise geben? Danke

_Originally posted by @Caferriade in https://github.com/ReneNulschDE/mbapi2020/issues/157#issuecomment-1904286210_

**Comment by ReneNulschDE** [comment]
Hi @Caferriade,

Grundsätzlich funktioniert in EU der Pin abruf.

Bitte stell zuerst sicher, dass die offizielle mobile app funktioniert. Manchmal muß dort nur den aktuellen Datenschutzrichtlinien zugestimmt werden. Stell auch sicher, dass Du wirklich den gleichen email account benutzt wie in der app (wäre auch nicht das erste mal :-))

Btw: Ich habe ein extra Issue angelegt. Das hier passt nicht mit China zusammen.

**Comment by Caferriade** [comment]
Guten Morgen, heute Morgen verhält sich die Komponente anders als gestern. Nach Eingabe der E-Mail-Adresse erscheint ein Popup ohne PIN-Abfrage.
Danke und gute Arbeit
![No-PIN-Request](https://github.com/ReneNulschDE/mbapi2020/assets/77505328/ca0a7ea8-b6a5-46b8-ab32-268c06dea91a)

**Comment by ReneNulschDE** [comment]
Welche Meldung kommt im Log dazu? Kannst Du Dich in der Mobile-App mal abmelden und neu anmelden? Funkioniert dies dort?

**Comment by Caferriade** [comment]
Ja, es funktioniert korrekt in der mobilen App. Ich melde mich ab und erhalte beim Anmeldevorgang eine E-Mail mit den sechs Ziffern, die ich in der mobilen App eingeben muss.

**Comment by ReneNulschDE** [comment]
Was steht im Log, nachdem Du in der deine email Adresse eingegeben hast und ok geklickt hast?

**Comment by ReneNulschDE** [comment]
und geh bitte mal in das Verzeichnis ***Dein-HA-Config-Verzeichnis/custom_components/mbapi2020 und schau mal in der Datei manifest.json welche Versionsnummer du installiert hast.

**Comment by Caferriade** [comment]
> Was steht im Log, nachdem Du in der deine email Adresse eingegeben hast und ok geklickt hast?
![Registry Log](https://github.com/ReneNulschDE/mbapi2020/assets/77505328/a467db39-bd9a-471a-a98a-dc1ab0faec2d)

**Comment by Caferriade** [comment]
> und geh bitte mal in das Verzeichnis ***Dein-HA-Config-Verzeichnis/custom_components/mbapi2020 und schau mal in der Datei manifest.json welche Versionsnummer du installiert hast.

![Version](https://github.com/ReneNulschDE/mbapi2020/assets/77505328/b99b3071-16bf-4629-b4f9-0531cbd948a1)

**Comment by Caferriade** [comment]
Wenn ich die Login-Adresse https://id.mercedes-benz.com/as/token.oauth2 manuell eingebe, erhalte ich die Fehlermeldung, die ich im Screenshot anhänge
![Address request login](https://github.com/ReneNulschDE/mbapi2020/assets/77505328/d774e805-c868-4556-8ee0-76a3fca78096)

**Comment by ReneNulschDE** [comment]
> > und geh bitte mal in das Verzeichnis ***Dein-HA-Config-Verzeichnis/custom_components/mbapi2020 und schau mal in der Datei manifest.json welche Versionsnummer du installiert hast.
> 
> ![Version](https://private-user-images.githubusercontent.com/77505328/298898878-b99b3071-16bf-4629-b4f9-0531cbd948a1.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDgwODQsIm5iZiI6MTcwNjAwNzc4NCwicGF0aCI6Ii83NzUwNTMyOC8yOTg4OTg4NzgtYjk5YjMwNzEtMTZiZi00NjI5LWI0ZjktMDUzMWNiZDk0OGExLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDExMDMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwODYzODVhYzZhNjdiZjFkOTIyMzVjNTM4YzIwYzVjNWUyYTdjZDM1NmU5ODJmYjMwNDZmZTQwZjVhZWE4YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OkvQi9mZm3GwInQCpK023BqCYo0tRHjBV3YnOCCIZSI)

Das ist nicht das Manifest-file aus dem ordner mbapi2020. Bitte nochmal prüfen.

**Comment by Caferriade** [comment]
Ich entferne die Komponente und installiere sie erneut

**Comment by Caferriade** [comment]
Ich habe die Komponente gelöscht und neu geladen. Ich füge Screenshots bei
![Custom_Component_with_Mercedes_me_New_Installation](https://github.com/ReneNulschDE/mbapi2020/assets/77505328/c25bd2dd-db9f-4351-97f4-e76323e9e009)
![Custom_Component_without_Mercedes_me](https://github.com/ReneNulschDE/mbapi2020/assets/77505328/3ad27623-b044-4cd8-86d6-37e66ab0faa5)
![New_Correct_Version](https://github.com/ReneNulschDE/mbapi2020/assets/77505328/262f7a47-d3ec-48b2-abc7-cde3fdd7558d)

**Comment by ReneNulschDE** [comment]
Kannst Du bitte mal in deiner configuration.yaml folgendes einfügen.

```
logger:
  default: warn
  logs:
    custom_components.mbapi2020: debug
```
Falls es schon einen Logger Eintrag gibt dann nur die letzte Zeile mit einfügen. Dann HA neustarten und nochmal versuchen. Wenn es nicht geht schau bitte mal in das homeassistant.log. Kannst es mir auch gern schicken an mbdev.i177@nulsch.de

**Comment by Caferriade** [comment]
Ok, ich werde gemäß Ihren Anweisungen fortfahren

**Comment by Caferriade** [comment]
> Hab es jetzt nochmal mit der Version 0.9.9 getestet und bei mir kommt die Pin per mail. Muß also was mit deinem account/umgebung sein. Finden wir schon...

Zum jetzigen Zeitpunkt befürchte ich es

**Comment by churchofnoise** [comment]
Same problem in Belgium, no pin code comes after request when trying to fix the integration after a restart of home assistant. Running v0.9.9

**Comment by mcsdodo** [comment]
I had this too (bad request in MB oauth flow).  What I did was:

1. "Delete authentication token file now. require a restart of Home Assistant after save" in Integration/Configure.
2. Reconfigure
3. No email arrived

Then I tried to re-save PIN within the app. Did steps above, now the email arrives and integration works again.

**Comment by ReneNulschDE** [comment]
Hi @mcsdodo , can you explain what you mean with "re-save PIN"

**Comment by ReneNulschDE** [comment]
Hi @churchofnoise , Du you use the HACS version or did you download the code from github? What is your HA version/Installation type?

**Comment by churchofnoise** [comment]
> Hi @churchofnoise , Did you use the HACS version or did you download the code from github? What is your HA version/Installation type?

From hacs, running latest ha supervised

**Comment by ReneNulschDE** [comment]
> From hacs, running latest ha supervised

Thx. Let me try to spin up a supervised instance...

**Comment by mcsdodo** [comment]
> Hi @mcsdodo , can you explain what you mean with "re-save PIN"

Sorry for the phrasing. I meant I just changed it to some value (in my case the same as previous) and saved. Just a blind shot, don't know whether it did something.

**Comment by churchofnoise** [comment]
> > From hacs, running latest ha supervised
> 
> Thx. Let me try to spin up a supervised instance... HA 2024.01.05?

Yes sir

**Comment by DavidGBlatchford** [comment]
It might be a coincident but it wouldn't work for me either down here in Australia until I went into the app and turned off Biometric ID under the security settings so it might be worth trying that.
