### ISSUE TITLE
European market: Bad Request PIN Request

### ISSUE THREAD

**Issue by juite** [ReneNulschDE/mbapi2020#178]
Hi,

I got a new Mercedes me account and I wanted to connect this account to HA. So I reinstalled the integration via HACS. After entering the e-mail to login an request a PIN... There was nothing... No mail, Just dust.. :)

2024-01-22 19:02:37.452 INFO (MainThread) [custom_components.mbapi2020.oauth] Start request PIN i*****@********ch.nl
2024-01-22 19:04:45.530 ERROR (MainThread) [custom_components.mbapi2020.oauth] ClientError requesting data from https://id.mercedes-benz.com/as/token.oauth2: 400, message='Bad Request', url=URL('https://id.mercedes-benz.com/as/token.oauth2')

Is there anything I did wrong?

Thanks in advance for your help with this great integration

**Comment by ReneNulschDE** [comment]
Hi, 

Do you have used the official MB app before? Maybe you just have to approve the new data privacy rules. Are you sure that you used the same email? Are there any special characters in your email? Looks like you are in the EU region, right?

I just checked it with my account and in general its working.

BR
Rene

**Comment by juite** [comment]
Hi,Thansk for your wuick reply.I have used the intgration for years. Very happy with it.  I got a new account. I will check the privacy Rules. No special characters in my mail adress and I’m in EU, Netherlands.Verstuurd vanaf mijn iPhoneOp 22 jan 2024 om 19:24 heeft Rene Nulsch ***@***.***> het volgende geschreven:﻿
Hi,
Do you have used the official MB app before? Maybe you just have to approve the new data privacy rules. Are you sure that you used the same email? Are there any special characters in your email? Looks like you are in the EU region, right?
I just checked it with my account and in general its working.
BR
Rene

**Comment by ReneNulschDE** [comment]
ok, please check and keep in mind that you can only add one MB account to HA currently. In case you need more than one account use the secondary driver function to invite your HA-account to the other cars.
