### ISSUE TITLE
European market - Pin code request not working

### ISSUE THREAD

**Issue by dirkclemens** [ReneNulschDE/mbapi2020#179]
@ReneNulschDE,
when registering the mbapi2020 component via HACS, I do not receive an Email (for some hours so far).
I am using the Mercedes Me App (iOS) since Nov 23 with the same Mailaddress I used here.

I am new to HA, using the latest version on Docker. My hardware is a Gigabyte MiniPC running the latest Ubuntu Server. 

HACS:
<img width="583" alt="Bildschirmfoto 2024-01-25 um 16 38 09" src="https://github.com/ReneNulschDE/mbapi2020/assets/908446/8f853f35-86d4-4b84-8054-f1593bcdb39f">

Mercedes Me:
<img width="583" alt="Bildschirmfoto 2024-01-25 um 16 37 12" src="https://github.com/ReneNulschDE/mbapi2020/assets/908446/c450a8a3-c8d3-4c74-be26-0da940c9e012">

Integration: 
<img width="668" alt="Bildschirmfoto 2024-01-25 um 11 53 43" src="https://github.com/ReneNulschDE/mbapi2020/assets/908446/db648a9a-083a-4023-a30a-72d1bf600028">

This is how I start the Home Assistant container in docker:
```
docker run -d \
  --name ha \
  --privileged \
  --restart=unless-stopped \
  -e TZ=Europe/Berlin \
  -v /opt/homeassistant/data:/config \
  -v /run/dbus:/run/dbus \
  --network=host \
  --device /dev/ttyACM0:/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2475760-if00 \
  ghcr.io/home-assistant/home-assistant:stable 
``` 
 Thanks in advance for any hint

**Comment by dirkclemens** [comment]
@ReneNulschDE I just tried it one more and now I received an email. So works fine.

**Comment by ReneNulschDE** [comment]
Thanks for the info. I'll keep it open for some days so that other can see that it was a problem on MB-side.

**Comment by mikburnz** [comment]
Same here. i try every day. upadeted and deletet versions. started the whole system. I dont receive any Code. Worked finde till last week.

**Comment by mikburnz** [comment]
So its not solved. Problem still actual.

**Comment by ReneNulschDE** [comment]
@mikburnz : Please open an own issue with all the relevant information.
