### ISSUE TITLE
Unknown market - Pin code request not working

### ISSUE THREAD

**Issue by max130570** [ReneNulschDE/mbapi2020#180]
After the update I installed the mercedes me integration again but I no longer get the pin via the email. home assistant is updated to the latest version. the data is correct but it no longer works
Thank you in advance for every solution

**Comment by ReneNulschDE** [comment]
Please add some more information:
1. What is your region?
2. Add your system information. Can be found in: Settings ⇒ System ⇒ Repairs ⇒ Three Dots in Upper Right ⇒ System information.
3. What is the version of your mbapi2020 component. Can be found in:  the manifest.json of the custom_component

**Comment by max130570** [comment]
Hello and thank you for your attention! I connect to the Europe zone more precisely from Italy, I am attaching the information you requested from me. the problem is still not solved
![IMG_5481](https://github.com/ReneNulschDE/mbapi2020/assets/122102706/2a2d7827-b649-4d4a-b526-4a569a1fa62d)
![IMG_5480](https://github.com/ReneNulschDE/mbapi2020/assets/122102706/9874f55f-8c00-416e-81eb-3b61f1fd1e7f)

**Comment by ReneNulschDE** [comment]
May I ask you to check for example this and see how the user reported the details? 
Example: https://github.com/ReneNulschDE/mbapi2020/issues/184
The screenshots of the HA system are not enough. I can't see the HAOS and addon details. You can also see what my next questions will be.

**Comment by ReneNulschDE** [comment]
Could you please reset the security pin in your MB mobile app and check again? This was the solution for multiple users.

**Comment by max130570** [comment]
I tried all the procedures you indicated to me, but also changing the pin
followed not to work unfortunately
The problems started in conjunction with a heavy upgrade of the Mb system
that made several changes
Maybe it depends on that

Il giorno ven 2 feb 2024 alle 15:49 Rene  ***@***.***> ha
scritto:

**Comment by ReneNulschDE** [comment]
Please see here:
https://github.com/ReneNulschDE/mbapi2020/issues/184#issuecomment-1930897256
