### ISSUE TITLE
European Market - Pin Email Request Not Working

### ISSUE THREAD

**Issue by krisblackhall** [ReneNulschDE/mbapi2020#181]
Hi,
Similar to recent posts I can report that this issue is still occurring as of now.
Have been using this custom integration for several months. Has worked brilliantly.

Today, after restating HA for other reasons, this integration failed to set up. Hence I tried removing and re-adding.
During the setup process no email is recieved with Pin number.

I have tested by logging out and in of the Mercedes App. When I log into the Mercedes app, I do recieve a pin email. But when tyring to log in through the HA integration setup, no pin is recieved.

European Market (UK).
Latest version of HA and this custom integration.

Not sure if MB servers are blacklisting requests from HA perhaps? As the MB app itself and the MB website login with email pin works normally.

**Comment by ReneNulschDE** [comment]
Hi,
Thanks for the ticket. Currently, I have no idea why this happens to some of the users. I expect a problem on MB side but I'm not sure. HA was not blacklisted as for example all my environments are working.

Whenever you are more technical, then you could try the beta release v0.9.10-beta.1 - I made one small change in the pin request structure - but also this just shooting around... If not, I propose to wait a few days. Most of the times the MB-Devs solving their problems fast.

**Comment by cpdowsett** [comment]
using the new  beta9.10 has fixed the issue for me.

Thanks

**Comment by ReneNulschDE** [comment]
Could you please reset the security pin in your MB mobile app and check again? This was the solution for multiple users.

**Comment by ReneNulschDE** [comment]
Please see here
https://github.com/ReneNulschDE/mbapi2020/issues/184#issuecomment-1930897256

**Comment by krisblackhall** [comment]
> Please see here [#184 (comment)](https://github.com/ReneNulschDE/mbapi2020/issues/184#issuecomment-1930897256)

Thank you. I can confirm this worked for me too. Just updated to the latest beta version, restated HA, added the integration and it's all back fine. I received the PIN in an email within 10 seconds of setting up the integration.
Many thanks for investigating this and your help. Much appreciated. A splendid integration to have in HA.
