### ISSUE TITLE
European Market - Pin Email Request Not Working

### ISSUE THREAD

**Issue by tibuski** [ReneNulschDE/mbapi2020#182]
FYI, same issue in BE

Tried with latest beta, email and mobile phone.

I can test/take logs if you need.

Regards,

Laurent

**Comment by ReneNulschDE** [comment]
Hi,
thanks for reporting. I'm still unsure what is raising the issue. Some users reported that they received the Pin mails again after a few days without any change some others still have the problem. Other users (like me) have no problem at all. I have requests > 50 pins in the last 72h...

Could describe your environment?
- Add your system information. Can be found in: Settings ⇒ System ⇒ Repairs ⇒ Three Dots in Upper Right ⇒ System information.
- What is the version of your mbapi2020 component. Can be found in: the manifest.json of the custom_component

**Comment by tibuski** [comment]
First of all, thank you very much for your work and your really quick reaction !
Second, here is the requested info :

manifest.json
``` json
{
  "domain": "mbapi2020",
  "name": "MercedesME 2020",
  "codeowners": [
    "@ReneNulschDE"
  ],
  "config_flow": true,
  "dependencies": [],
  "documentation": "https://github.com/ReneNulschDE/mbapi2020",
  "integration_type": "hub",
  "iot_class": "cloud_push",
  "issue_tracker": "https://github.com/ReneNulschDE/mbapi2020/issues",
  "loggers": [
    "custom_components.mbapi2020"
  ],
  "requirements": [
    "protobuf>=3.19.1"
  ],
  "version": "0.9.10"
```


## System Information

version | core-2024.1.5
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 4.14.167-0-vanilla
arch | x86_64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 30, 2024 at 2:00 AM
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-4.ui.nabu.casa
certificate_status | ready
instance_id | 33ebe278f29e4199980f603e71693ffa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 3
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 18, 2024 at 12:36 PM
-- | --
current_recorder_run | January 28, 2024 at 11:48 AM
estimated_db_size | 380.68 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by ReneNulschDE** [comment]
Thanks. Do you use a HA standard container image or is this customized?

**Comment by tibuski** [comment]
Standard with image from : ghcr.io/home-assistant/home-assistant:stable

**Comment by aleksej0307** [comment]
I also have the same problem. Hope a solution is found.

**Comment by ReneNulschDE** [comment]
> ghcr.io/home-assistant/home-assistant:stable

I checked the process with my account and it works as expected...

Are you able to execute an command on the host maschine and in the docker environment? If yes, send me an email mbdev.i182@nulsch.de and I will share the command. (Please share the os-version of the host too in the mail.)

or...

1. connect to your docker instance with "docker exec -it homeassistant bash"
2. Copy the curl command from https://pastes.io/0uugksd1bd
3. Replace XXXXXX with your mb-account-email
4. run

Result should be:
```
HTTP/1.1 200 OK
Content-Security-Policy: default-src https:
Content-Type: application/json
Referrer-Policy: strict-origin-when-cross-origin
Strict-Transport-Security: max-age=63072000
X-Authmode: CIAMNG
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
Date: Sun, 28 Jan 2024 19:12:51 GMT
Content-Length: 43
Connection: close

{"isEmail":true,"username":"XXXXXXX"}

```
and you should get a email

**Comment by tibuski** [comment]
Hello,

It worked, received the PIN !

``` sh
nuc:/config# curl -i -s -k -X $'POST' \
    -H $'Host: bff.emea-prod.mobilesdk.mercedes-benz.com' \
    -H $'User-Agent: MyCar/1.40.0 (com.daimler.ris.mercedesme.ece.ios; build:2097; iOS 17.3.0) Alamofire/5.4.0' \
    -H $'Ris-Os-Name: ios' \
    -H $'Ris-Os-Version: 17.3' \
    -H $'Ris-Sdk-Version: 2.111.1' \
    -H $'X-Locale: en-GB' \
    -H $'X-Trackingid: 4eaa3090-94a6-4688-ba4a-8bd6c270fe59' \
    -H $'X-Sessionid: 6d1521d2-9f17-415d-a442-95e859aeba5d' \
    -H $'Content-Type: application/json' \
    -H $'X-Applicationname: mycar-store-ece' \
    -H $'Ris-Application-Version: 1.40.0 (2097)' \
    -H $'Accept: */*' \
    -H $'Accept-Encoding: gzip, deflate, br' \
    -H $'Connection: close' \
    --data-binary $'{\"emailOrPhoneNumber\" : \"surname@xxxxxxxxxxx.be\", \"countryCode\" : \"EN\", \"nonce\" : \"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee\"}' \
    $'https://bff.emea-prod.mobilesdk.mercedes-benz.com/v1/login'
```
``` sh
HTTP/1.1 200 OK
Content-Security-Policy: default-src https:
Content-Type: application/json
Referrer-Policy: strict-origin-when-cross-origin
Strict-Transport-Security: max-age=63072000
X-Authmode: CIAMNG
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
Date: Sun, 28 Jan 2024 20:08:17 GMT
Content-Length: 49
Connection: close

{"isEmail":true,"username":"surnmae@xxxxxxxxxxx.be"}

```

**Comment by tibuski** [comment]
And now the integration works too ... I didn't change anything.

Probably a Mercedes backend issue ...

**Comment by tibuski** [comment]
Still working, once again, thank you for your work on this integration and the support you provided !

**Comment by hcraveiro** [comment]
It's happening to me the same problem. Also, when I tried to run the curl command I got:
HTTP/1.1 400 Bad Request
Content-Security-Policy: default-src https:
Content-Type: application/json
Referrer-Policy: strict-origin-when-cross-origin
Strict-Transport-Security: max-age=63072000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
Date: Mon, 29 Jan 2024 09:50:08 GMT
Content-Length: 0
Connection: close

**Comment by ReneNulschDE** [comment]
Can you please share the list of installed addins and the version information of the manifest file? See above...

**Comment by karJohBab** [comment]
Hallo,

hab das selbe Problem, dass ich keinen Pin bekomme :(

Hab nur ein Fahrzeug
Version (Manifest Datei) ist die Beta 0.9.10 
Login ist via Mail ohne Sonderzeichen 


## System Information

version | core-2024.1.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1381
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 14. Januar 2025 um 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-12.ui.nabu.casa
certificate_status | ready
instance_id | b9365bda93894af0a861e651f33cfbdc
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 28.5 GB
disk_used | 12.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Mosquitto broker (6.4.0), Terminal & SSH (9.7.1), ESPHome (2023.12.9), Home Assistant Google Drive Backup (0.112.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 3
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 22. Januar 2024 um 18:23
-- | --
current_recorder_run | 29. Januar 2024 um 12:42
estimated_db_size | 73.10 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by hcraveiro** [comment]
> Can you please share the list of installed addins and the version information of the manifest file? See above...
> 
> And do you have any other device in your network where you can run a command under Linux or Windows or Mac? Do you use the email address or mobilephone numer to request the pin? Are there any special characters (other then numbers or letters) in your email?

The addons are already on the list I provided. The manifest is this one:
{
  "domain": "mbapi2020",
  "name": "MercedesME 2020",
  "codeowners": [
    "@ReneNulschDE"
  ],
  "config_flow": true,
  "dependencies": [],
  "documentation": "https://github.com/ReneNulschDE/mbapi2020",
  "integration_type": "hub",
  "iot_class": "cloud_push",
  "issue_tracker": "https://github.com/ReneNulschDE/mbapi2020/issues",
  "loggers": [
    "custom_components.mbapi2020"
  ],
  "requirements": [
    "protobuf>=3.19.1"
  ],
  "version": "0.9.9"
}

**Comment by KleinChris89** [comment]
I have the same problem

**Comment by ReneNulschDE** [comment]
> I have the same problem

Please read the different comments in this issue, and deliver, test the different things. This is not a generell bug in this component.

**Comment by ReneNulschDE** [comment]
@karJohBab : I have moved you comment to a new issue... I'm loosing the control :-)

**Comment by ReneNulschDE** [comment]
@hcraveiro : Thanks! May I ask you to open a new issue for this and copy all the information into that one? This will help me to keep control.

**Comment by hcraveiro** [comment]
> @hcraveiro : Thanks! May I ask you to open a new issue for this and copy all the information into that one? This will help me to keep control.

Yes, for sure! Thank you!
