### ISSUE TITLE
European Market - Pin Email Request Not Working

### ISSUE THREAD

**Issue by ReneNulschDE** [ReneNulschDE/mbapi2020#183]
hab das selbe Problem, dass ich keinen Pin bekomme :(

Hab nur ein Fahrzeug
Version (Manifest Datei) ist die Beta 0.9.10 
Login ist via Mail ohne Sonderzeichen 

## System Information

version | core-2024.1.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1381
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 14. Januar 2025 um 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-12.ui.nabu.casa
certificate_status | ready
instance_id | b9365bda93894af0a861e651f33cfbdc
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 28.5 GB
disk_used | 12.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Mosquitto broker (6.4.0), Terminal & SSH (9.7.1), ESPHome (2023.12.9), Home Assistant Google Drive Backup (0.112.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 3
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 22. Januar 2024 um 18:23
-- | --
current_recorder_run | 29. Januar 2024 um 12:42
estimated_db_size | 73.10 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

_Originally posted by @karJohBab in https://github.com/ReneNulschDE/mbapi2020/issues/182#issuecomment-1914644455_

**Comment by ReneNulschDE** [comment]
I checked the image with my account and it works as expected...

1. connect to your HA command line and connect directly to the HomeAssistant instance with "docker exec -it homeassistant bash"
2. Copy the curl command from https://pastes.io/0uugksd1bd
3. Replace XXXXXX with your mb-account-email
4. run
5. check the result
6. leave the docker instance with "exit"

Result should be:
```
HTTP/1.1 200 OK
Content-Security-Policy: default-src https:
Content-Type: application/json
Referrer-Policy: strict-origin-when-cross-origin
Strict-Transport-Security: max-age=63072000
X-Authmode: CIAMNG
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
Date: Sun, 28 Jan 2024 19:12:51 GMT
Content-Length: 43
Connection: close

{"isEmail":true,"username":"XXXXXXX"}
```
and you should get a email

**Comment by karJohBab** [comment]
Thank you. 
I have try it, the response was the same but the username was an empty string in the response. I didn't receive a email

**Comment by ReneNulschDE** [comment]
Can you run this comment in the SSH-Addon-Shell? (so without executing "docker exec blabla")

**Comment by karJohBab** [comment]
In the addon shell it was the same response but I have found the mistake. 

With my phone number it works :-D

In the app the login works with email and phone number but i think i have used the number for initial create my MB account 

Thank you for help. :)
