### ISSUE TITLE
European Market - PIN Email not receiving nor chance to fill

### ISSUE THREAD

**Issue by mikburnz** [ReneNulschDE/mbapi2020#185]
I have been trying daily since last week to have the PIN sent to me. Without success. Today, after submitting the request, no window appeared for entering the PIN anymore. Has the service been discontinued

![1](https://github.com/ReneNulschDE/mbapi2020/assets/154707156/0672dec0-dfd0-4a63-8978-cf6afcb4ea50)
![2](https://github.com/ReneNulschDE/mbapi2020/assets/154707156/5faf805c-87ec-4acb-8f38-9331e3b3276b)

**Comment by ReneNulschDE** [comment]
Thanks for the issue. No the integration is still working for a lot of people. However, a few have problems getting the pin right now and I have no idea why this happens. Thatswhy I ask you to share some more information. Please take a look on #184 this for the first few post a good example what I need from you. Just post it here. In case you do not want to share it publicly, send me an email mb.dev.i185@nulsch.de. Thx

**Comment by mikburnz** [comment]
Hope the answer ist correct:

Generic x86-64
Core
2024.1.5
Supervisor
2023.12.1
Operating System
11.4
Frontend
20240104.0

{
  "domain": "mbapi2020",
  "name": "MercedesME 2020",
  "codeowners": [
    "@ReneNulschDE"
  ],
  "config_flow": true,
  "dependencies": [],
  "documentation": "https://github.com/ReneNulschDE/mbapi2020",
  "integration_type": "hub",
  "iot_class": "cloud_push",
  "issue_tracker": "https://github.com/ReneNulschDE/mbapi2020/issues",
  "loggers": [
    "custom_components.mbapi2020"
  ],
  "requirements": [
    "protobuf>=3.19.1"
  ],
  "version": "0.9.9"
}

do you need further information?

**Comment by ReneNulschDE** [comment]
Thanks @mikburnz,

Lets dive a little bit deeper...

I checked the image with my account and it works as expected...

1. connect to your SSH-Addon Shell connect directly to the HomeAssistant instance with "docker exec -it homeassistant bash"
2. Copy the curl command from https://pastes.io/0uugksd1bd
3. Replace XXXXXX with your mb-account-email
4. run
5. check the result
6. leave the docker instance with "exit"
Result should be:
```
HTTP/1.1 200 OK
Content-Security-Policy: default-src https:
Content-Type: application/json
Referrer-Policy: strict-origin-when-cross-origin
Strict-Transport-Security: max-age=63072000
X-Authmode: CIAMNG
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
Date: Sun, 28 Jan 2024 19:12:51 GMT
Content-Length: 43
Connection: close

{"isEmail":true,"username":"XXXXXXX"}
```
and you should get a email...

In case you got an error (http400) or the username field is empty (http200) and did not got an email. Run the same steps without connecting to the homeassistant-core instance. (so just in the SSH-Addon-shell)

If also this fails, please check if you can use a device in your local network but not connected to HAOS. In case this is a windows machine let me know - I have an powershell command with the same content available.
