### ISSUE TITLE
Can not connect to MB OAuth API

### ISSUE THREAD

**Issue by xs400dohc** [ReneNulschDE/mbapi2020#187]
Hello Mr. Nulsch

since 29.02.2024 22:24:13 I don't get anymore data from your integration.
Reboot doesn't fix the problem.

In the log I get this report:

2024-02-02 13:18:56.352 ERROR (MainThread) [custom_components.mbapi2020.oauth] ClientError requesting data from https://id.mercedes-benz.com/as/token.oauth2: 400, message='Bad Request', url=URL('https://id.mercedes-benz.com/as/token.oauth2')
2024-02-02 13:18:56.353 DEBUG (MainThread) [custom_components.mbapi2020] Can not connect to MB OAuth API https://id.mercedes-benz.com. Will try again.

I'm running HA on a Fujitsu Thin Client, 
Core 2024.1.6
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

Is the problem on my computer or is there a problem with the server of mercedes?
With the android-app from mercedes there is no problem, so I think the problem is on my side.
If you have any suggestions to get the integration running again, I will be happy.
I wrote in english and not in german, so other users can follow better if it's a general problem.

Many thanks

xs400dohc
attached my system information
## System Information

version | core-2024.1.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.71-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1382
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 116.7 GB
disk_used | 49.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.8.1), Mosquitto broker (6.4.0), Zigbee2MQTT (1.35.2-1), Samba share (12.2.0), Studio Code Server (5.15.0), MariaDB (2.6.1), Duck DNS (1.15.0), DHCP server (1.3.1), phpMyAdmin (0.9.1), ESPHome (2023.12.9), Grafana (9.1.3), InfluxDB (5.0.0), File editor (5.7.0), RPC Shutdown (2.4), Portainer (2.19.4-3), Samba Backup (5.2.0), Node-RED (17.0.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 7
views | 26
mode | storage

</details>

<details><summary>MercedesME 2020</summary>

error | failed to load: unknown
-- | --

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 7. Dezember 2022 um 07:36
-- | --
current_recorder_run | 2. Februar 2024 um 14:14
estimated_db_size | 4291.78 MiB
database_engine | mysql
database_version | 10.6.12

</details>

**Comment by ReneNulschDE** [comment]
Hi,

Can you please reset the security pin on your android MB app? (you can use the same code as before)

This helped multiple users. See here (https://github.com/ReneNulschDE/mbapi2020/issues/185) for example.

BR
Rene

**Comment by ReneNulschDE** [comment]
Please delete the .mercedesmeauth.. file in your HA config directory and restart HA. (or use the delete option in the Configure dialog of the integration)

**Comment by xs400dohc** [comment]
Hello Mr. Nulsch,

thank you for the really fast answer.

As you wrote I changed the pin in the app, deleted the integration , restarted HA and reinstalled the integration. Now it's working again.

Thanks once more
xs400dohc
