### ISSUE TITLE
Error Requesting Data, Please reauthenticate

### ISSUE THREAD

**Issue by OlavRab** [ReneNulschDE/mbapi2020#19]
I just tried to set up the MBAPI for my 2019 CLA Shooting brake.
Installing and receiving the TAN-Code all worked perfectly fine, I got the message that the MBAPI was successfully set up.
But then the message appeared to reauthenticate. Am I doing something wrong?

![afbeelding](https://user-images.githubusercontent.com/38460642/118692341-372fdf00-b80a-11eb-83d8-7304e43a3a93.png)

![afbeelding](https://user-images.githubusercontent.com/38460642/118692360-3dbe5680-b80a-11eb-85c2-a3febdda69ca.png)

![afbeelding](https://user-images.githubusercontent.com/38460642/118692403-4d3d9f80-b80a-11eb-906f-e27a447c8730.png)

Latest reads from the log:
``2021-05-18 18:44:58 ERROR (MainThread) [custom_components.mbapi2020.oauth] Error requesting data from https://id.mercedes-benz.com/as/token.oauth2: 400, message='Bad Request', url=URL('https://id.mercedes-benz.com/as/token.oauth2')
2021-05-18 18:44:58 ERROR (MainThread) [custom_components.mbapi2020] Authentication failed. Please reauthenticate.
2021-05-18 18:46:00 ERROR (MainThread) [custom_components.mbapi2020.oauth] Error requesting data from https://id.mercedes-benz.com/as/token.oauth2: 400, message='Bad Request', url=URL('https://id.mercedes-benz.com/as/token.oauth2')
2021-05-18 18:46:00 ERROR (MainThread) [custom_components.mbapi2020] Authentication failed. Please reauthenticate.
2021-05-18 18:52:56 ERROR (MainThread) [homeassistant.components.system_health] Error fetching info
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 69, in get_integration_info
data = await registration.info_callback(hass)
File "/config/custom_components/mbapi2020/system_health.py", line 21, in system_health_info
client = hass.data[DOMAIN]
KeyError: 'mbapi2020'``

**Comment by ReneNulschDE** [comment]
Thanks for reporting.

Do you see any entities or sensors for your car(s)?
In which country do you live?
Are their any other errors?
Do you have any special signs in your login email address?

**Comment by OlavRab** [comment]
Hi,

I cannot see any sensors of my car.
I live in the Netherlands
This is the only error, the request to reauthenticate
My email address has dots : olav.van.etc@gmail.com

**Comment by ReneNulschDE** [comment]
can you please 
- delete the file .mercedesme-token-cache in your HA-config folder. 
- Remove the MB integration from the integrations-page. 
- Add the integration again

**Comment by czornikk** [comment]
Hi, 

I'm getting the same error after restoring from a snapshot. I have tried deleting file .mercedesme-token-cache, removing the integration, restarting HA and adding the integration again and I get the same error.

![image](https://user-images.githubusercontent.com/47973790/126536473-fa5d2ad8-0a48-4ede-afe7-240292a5ae75.png)

**Comment by czornikk** [comment]
P.S.: I was able to get it to work by changing the Time Zone of Home Assistant to Etc/GMT, restarting and trying to authenticate again. After that I reverted to my Time Zone and everything is working. I read about this authentication issue for some other integration and it did the trick here too. Maybe this helps someone else.
