### ISSUE TITLE
System log error: "Error doing job: Task exception was never retrieved"

### ISSUE THREAD

**Issue by netweaver1970** [ReneNulschDE/mbapi2020#190]
Hi,

I find below message in the HA system log, multiple times. 
Anything I need to be worried about or report to you? 
Does the component make concurrent calls?

- HA version 2024.1.5
- component version 0.9.10-beta1

Thanks.

'''
Logger: homeassistant
Source: custom_components/mbapi2020/websocket.py:172
Integration: MercedesME 2020 ([documentation](https://github.com/ReneNulschDE/mbapi2020), [issues](https://github.com/ReneNulschDE/mbapi2020/issues))
First occurred: 00:10:04 (4 occurrences)
Last logged: 14:17:13

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/mbapi2020/websocket.py", line 172, in _recv
    data = await self._connection.receive()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_ws.py", line 232, in receive
    raise RuntimeError("Concurrent call to receive() is not allowed")
RuntimeError: Concurrent call to receive() is not allowed
'''

**Comment by ReneNulschDE** [comment]
Thx, this is a known bug of the beta version. Will be fixed in the next version.
