### ISSUE TITLE
Preconditioning start with departure time has broken

### ISSUE THREAD

**Issue by negronoir** [ReneNulschDE/mbapi2020#194]
Hi, I use preheat_start_departure_time in one of my automations.

Up to version v0.9.9, it works right and set preconditioning at departure time

Triggered manually at February 8, 2024 at 15:58:58
Call a service 'MercedesME 2020: Preconditioning start with departure time' on
Finished at February 8, 2024 at 15:58:58 (runtime: 0.21 seconds)

But on current version v0.10.0 the automation raises an error

Triggered manually at February 8, 2024 at 16:11:31
Call a service 'MercedesME 2020: Preconditioning start with departure time' on
**Stopped because an error was encountered at February 8, 2024 at 16:11:31 (runtime: 0.25 seconds)
setup_services.<locals>._get_config_entryid() takes 1 positional argument but 2 were given**

I've rolled back & forward between this two versions v0.9.9 & v0.10.0 and the error can be easily reproduced

Thanks!

Toni

**Comment by ReneNulschDE** [comment]
Solved with release v0.10.1

**Comment by negronoir** [comment]
> Solved with release v0.10.1

I just have tried v0.10.1 and you're right. It's solved

Many thanks!

Toni
