### ISSUE TITLE
AUX heater not working in update 

### ISSUE THREAD

**Issue by Olausson92** [ReneNulschDE/mbapi2020#196]
I get this error on latest update: **This entity is no longer being provided by the mbapi2020 integration. If the entity is no longer in use, delete it in settings.**

Core
2024.2.0
Supervisor
2024.01.1
Operating System
11.5
Frontend
20240207.0

**Comment by ReneNulschDE** [comment]
Hi, does your car has an auxheater ? if not this is explained in the release notes. If yes, please share the diagnostic logs.

Please don't mix aux-heater(secondary heating engine) with pre-entry-climate/pre-heater (all the eqx and hybrids)

**Comment by ReneNulschDE** [comment]
Thx  - let me check.

**Comment by ReneNulschDE** [comment]
Looks like the data was not available in the dataset that MB has send after the start. 
Could you please:

1. enable in the configure dialog of the component the option "DEBUG ONLY: Enable save server messages to the messages folder"
2. restart HA
3. Wait 2 minutes
4. Disable in the configure dialog of the component the option "DEBUG ONLY: Enable save server messages to the messages folder"
5. Send me the json files out of the folder /config/custom_components/mbapi2020/messages via email to mbdev.issue196@nulsch.de

**Comment by ReneNulschDE** [comment]
And to clarify: Is the sensor not available or the switch?

**Comment by Olausson92** [comment]
Well, i am a noob regarding this so you have to be more clear what I should
do xD

Den tors 8 feb. 2024 kl 17:46 skrev Rene Nulsch ***@***.***>:

**Comment by Olausson92** [comment]
Alright! Then I'll wait for an update :)
