### ISSUE TITLE
Smart missing after uninstall and reinstall 0.10/0.10.1

### ISSUE THREAD

**Issue by Whatsek** [ReneNulschDE/mbapi2020#198]
After upgrading to 0.10 I had the PIN log issue. So I uninstalled, removed the folder, restarted an reinstalled the component. The PIN verification was working after that, but no cars are found. ( Should be an Smart ED) 

I installed the Mercedes.me app on my phone and tried to add my Smart again, but the message was: This vehicle is already in your account. 

I upgraded to 0.10.1 and restarted Home Assistant, still no car in Home Assistant. I enabled logging:

_Logger: custom_components.mbapi2020
Source: custom_components/mbapi2020/__init__.py:173
Integration: MercedesME 2020 ([documentation](https://github.com/ReneNulschDE/mbapi2020), [issues](https://github.com/ReneNulschDE/mbapi2020/issues))
First occurred: 9:57:47 PM (1 occurrences)
Last logged: 9:57:47 PM

No active cars found. Websocket connection disabled._

I am using the mbapi2020 since it was migrated from the previous smart api component, and it always worked fine.

**Comment by ReneNulschDE** [comment]
Smarts are worked only by "accident"... 

Are you able to edit a code file to test something?

I have no access to a smart anymore and can't test it.

**Comment by Tgxcorporation** [comment]
Ok I'm ready
Thanks

**Comment by ReneNulschDE** [comment]
I prepared this gist: https://gist.github.com/ReneNulschDE/96916f579feafb7474d9d9e4225bd412

But, I'm not sure if we have to change some other parts too. But this is the starting point.

Background: Smarts have no masterdata records and I created the car based on the websocket information only.

**Comment by Tgxcorporation** [comment]
It's working now!!! Great

**Comment by Whatsek** [comment]
That's good news! I can try this tomorrow. Thanks for your great support!

**Comment by ReneNulschDE** [comment]
Its part of the master branch now and will be part of the next release too

**Comment by Whatsek** [comment]
Can confirm this works! Thank you for still supporting our small Mercedes brothers!

**Comment by ReneNulschDE** [comment]
I have published a pre release v0.11.0-beta.1.
