### ISSUE TITLE
Feature Request: charging Energy in kW

### ISSUE THREAD

**Issue by apfelflo89** [ReneNulschDE/mbapi2020#20]
Is there a way to get the charging power in kW?

Thats what it looks like within the app:

![IMG_AC246C8C7D56-1](https://user-images.githubusercontent.com/48082211/128493234-001f72d5-fa1b-412b-aac1-bf5f3416d3d1.jpeg)

**Comment by ReneNulschDE** [comment]
Currently, this attribute is not available. Let me check after my vacation.

**Comment by ReneNulschDE** [comment]
With https://github.com/ReneNulschDE/mbapi2020/commit/263d7abdfffc4508c2c7365f5019b7bb8ccbd93c the Sensor "Range Electric" has a new attribute "chargingPower"
