### ISSUE TITLE
AUxHeat not available anymore

### ISSUE THREAD

**Issue by mikburnz** [ReneNulschDE/mbapi2020#201]
### The problem

Auxheat is not availableanymore : Diese Entität wird nicht mehr von der Integration mbapi2020 bereitgestellt. Wenn die Entität nicht mehr verwendet wird, lösche sie in den Einstellungen."

For me the most important switch. 

Can you bring it to run again?

### What version of MBAPI2020 do use?

version": "v0.10.1

### What type of installation are you running?

Home Assistant OS

**Comment by ReneNulschDE** [comment]
This solved in v0.10.2-beta1 or take a look here #197

**Comment by ReneNulschDE** [comment]
v0.11.1 published
