### ISSUE TITLE
Preheating state

### ISSUE THREAD

**Issue by rubenvanparys** [ReneNulschDE/mbapi2020#202]
### The problem

Is it possible to query the preheating state (similarly as the auxiliary heating sensor does)? You can turn it on/off, but it would be useful to get the state from the system.

### What version of MBAPI2020 do use?

0.10.1

### What type of installation are you running?

Home Assistant Container

**Comment by ReneNulschDE** [comment]
Please check the attributes of the range_electric sensor. There you can fin some precond-attributes

**Comment by thogens** [comment]
Hi all,

I'm facing the same "issue" with the separate buttons for enable/disable. Any hint on how I can expose a single switch to HomeKit that reflects the current state of pre-heating and makes it possible to "enable/disable"?
Thomas

**Comment by ReneNulschDE** [comment]
Hi Thomas,

Please check the mbapi2020 thread in the HA forum. https://community.home-assistant.io/t/mercedes-me-component/41911

I'm sure we discussed a solution based on a template switch

**Comment by ReneNulschDE** [comment]
Hi, may I ask you to ask this question in the forum? I'm on vacation the next 4 weeks and have access to my mobile only. I'm sure someone can help, otherwise I will take a look on it when I'm back in June.
