### ISSUE TITLE
How to use the exclusion of cars by FIN/FIN?

### ISSUE THREAD

**Issue by TrueMeistro** [ReneNulschDE/mbapi2020#203]
Wir haben das Thema via eMail geklärt. Ursache: Die FIN/VIN des Fahrzeugs war in den Optionen der Komponente in der "Exclude List" eingetragen.

_Originally posted by @ReneNulschDE in https://github.com/ReneNulschDE/mbapi2020/discussions/171#discussioncomment-8020155_

Hallo Rene, sieht bei mir so aus als ob das gleiche Problem bei mir besteht.

Wie und wo kann ich die FIN aus der "Exclude List" herausbekommen?

Schon mal danke!

**Comment by ReneNulschDE** [comment]
Klicke auf Configure in the Übersichtsseite der Integration.
![image](https://github.com/ReneNulschDE/mbapi2020/assets/33263735/73e617d2-8a69-4b84-a05c-a3e58515189c)

und lösche den Eintrag bei Exclude-Vin

**Comment by TrueMeistro** [comment]
sorry - I think I am standing on the hose! :-)
sieht bei mir ganz anders aus:
![grafik](https://github.com/ReneNulschDE/mbapi2020/assets/135322110/c836b954-7e84-4272-af1c-6fee82d03269)

**Comment by ReneNulschDE** [comment]
Mein screenshot wollte nur den Weg zum Configure Dialog zeigen. Im ersten Feld deines Screenshots stehen die FIN/VIN die exkludiert sind.

**Comment by TrueMeistro** [comment]
Klarer Fall von „wer lesen kann ist im Vorteil!“. Danke, ist mir peinlich…

**Comment by ReneNulschDE** [comment]
OK, und du solltest die Debug option ausschalten und du willst wahrscheinlich auch nicht die GCJ-02 translation - ausser dein Auto fährt durch China....

**Comment by TrueMeistro** [comment]
Nach China erst ab nächster Woche… ;-) Vielen Dank!
