### ISSUE TITLE
When changing charging program, max_state_of_charge doesn't update

### ISSUE THREAD

**Issue by TheGroundZero** [ReneNulschDE/mbapi2020#210]
### The problem

When changing the charging program (e.g. from Standard to Home), the max_state_of_charge doesn't update.
For example, if the Standard was set to a charge goal of 100% but the Home program sets it to 50%, MBAPI will still report 100% as max_state_of_charge.

### What version of MBAPI2020 do use?

v0.11.1

### What type of installation are you running?

Home Assistant Container

**Comment by ReneNulschDE** [comment]
There is a special sensor "max_soc" for this case, but as discussed in the other ticket, the sensor does not work in the current release and is fixed in the master branch with https://github.com/ReneNulschDE/mbapi2020/commit/543ce5ebf0d75524ae9273d82da63857b49af808

**Comment by ReneNulschDE** [comment]
I have published a beta version [v0.11.2-beta.4](https://github.com/ReneNulschDE/mbapi2020/releases/tag/v0.11.2-beta.4). The error is handled in this release. Please check.

**Comment by ReneNulschDE** [comment]
Fixed withh v0.12.0
