### ISSUE TITLE
Failing to Authenticate on 2024.3

### ISSUE THREAD

**Issue by 74Rog** [ReneNulschDE/mbapi2020#212]
### The problem

My HA installation was failing to update to 2024.3 so I've redeployed from scratch and then restored from backup and then waas able to upgrade to 2024.3.
I get a message that I need to reauthenticate MercedesMe 2020, I get the email with the code and enter it but it fails to authenticate with the following error in the HA logs.

This error originated from a custom integration.

Logger: custom_components.mbapi2020
Source: custom_components/mbapi2020/__init__.py:63
integration: MercedesME 2020 (documentation, issues)
First occurred: 22:36:27 (2 occurrences)
Last logged: 22:37:21

Authentication failed. Please reauthenticate.

### What version of MBAPI2020 do use?

v0.12.0

### What was the last working version of MBAPI2020?

v0.11.1

### What type of installation are you running?

Home Assistant OS

**Comment by ReneNulschDE** [comment]
Please enable the debug log, run the process again and share the log

**Comment by tbkon3** [comment]
same for me: the error is:
[%key:common::config_flow::abort::reauth_successful%]

**Comment by tbkon3** [comment]
Fixed:
Deleted the old "Hub", reboot and reconfigured, all ok!!!

**Comment by 74Rog** [comment]
I've deleted and reinstalled now and it is fine. 
It did start to get a bit weird as I had multiple reconfigure buttons in Devices and Services but all good now.

**Comment by ReneNulschDE** [comment]
Thanks, This is not related too 2024.3.3. 
- The multiple button problem is on my list.
- Reauth-Problem: I assume that this happens after an upgrade of HA in an HAOS environment. Whenever the backup is not created near time (<10min) before the upgrade than there is a high risk that invalid keys are stored in the backup. (Reason: the auth and reauth keys are vaild for 120min only and are renewed every 110min)

**Comment by janwilms** [comment]
This is the error I got now

This error originated from a custom integration.

Logger: custom_components.mbapi2020.oauth
Source: custom_components/mbapi2020/oauth.py:312
integration: MercedesME 2020 (documentation, issues)
First occurred: 08:48:43 (3 occurrences)
Last logged: 08:52:47

Error requesting: https://id.mercedes-benz.com/as/token.oauth2 - 0 - {"error_description":"unknown, invalid, or expired refresh token","error":"invalid_grant"}

**Comment by ReneNulschDE** [comment]
In what context did you got this error? HA-Upgrade / Restore?

**Comment by Marijncouckuyt** [comment]
I ran into the same problem after upgrading to 24.3.3.
It fails to reauth after removing the integration and reinstalling it.
Gives 'unknown error'

**Comment by j9brown** [comment]
Hmm, I understand why the auth tokens expire and may need to be refreshed after an update, but why does authentication still not work after the reconfigure task completes successfully?

**Comment by j9brown** [comment]
Still unable to re-authenticate in v0.13.

**Comment by ReneNulschDE** [comment]
I have made one change in v0.14-beta1 and try to read from the HA config store first instead of using the file cache... But still testing it on my instances.

**Comment by j9brown** [comment]
I noticed this in the beta release notes.  Not sure whether it is relevant but it sounds superficially related: https://developers.home-assistant.io/blog/2024/04/25/always-reload-after-successful-reauth-flow/

**Comment by ReneNulschDE** [comment]
Sounds related but we want the reload after the auth issue. I changed the flow a little bit in the latest beta of the component. Now I try to load the tokens from the cache instead of the file system.

**Comment by DirkV71** [comment]
Problem to create new hub.

German Customer with *.com Email-Adress. Only can create a Hub for North America. But there it can´t find my car via VIN.

Regards, Dirk

**Comment by Rainman67** [comment]
I have a german *.de E-Mail-Adress and exactly the same problem. Maybe the authentication-server of Mercedes is temporarily down?

**Comment by DirkV71** [comment]
Yes, thats a option. I downgrade the integration to Version 0.12 and the problem was still there. I will try it tomorow again...

**Comment by Andreasroessler248** [comment]
Hi Dirk some issue here started today in the morning. Seems to be a general issue.

**Comment by ReneNulschDE** [comment]
Will close this on. The first issue was a HA-core bug.
