### ISSUE TITLE
Minor spelling issue

### ISSUE THREAD

**Issue by aegjoyce** [ReneNulschDE/mbapi2020#215]
### The problem

https://github.com/ReneNulschDE/mbapi2020/blob/91960c70ee5ee2e2177b0e6694127a45ee5504ba/custom_components/mbapi2020/translations/en.json#L25

"adress" should be "address"

### What version of MBAPI2020 do use?

v0.12.0

### What type of installation are you running?

Home Assistant OS

**Comment by ReneNulschDE** [comment]
Thx, fixed with https://github.com/ReneNulschDE/mbapi2020/commit/952a17da4297bc2a2bb3716aadb2bad1c5110abb
