### ISSUE TITLE
Component only shows 3 enteties

### ISSUE THREAD

**Issue by a94marbo** [ReneNulschDE/mbapi2020#22]
Hi
The component has for some time only been showing 3 entities.
I have reinstalled the component, I still only see this:
![image](https://user-images.githubusercontent.com/39158765/134968808-1e77a28e-2edf-476a-9b6e-c0c8092e4d32.png)
![image](https://user-images.githubusercontent.com/39158765/134968844-f7944650-9e3a-444e-8b4c-b9cccce63dc3.png)
![image](https://user-images.githubusercontent.com/39158765/134969094-7ec172b9-6355-4a00-89d4-89a777ce7356.png)

**Comment by ReneNulschDE** [comment]
Hi, the available features are depended on the car and the purchased licenses.

Please check first if you see more data in your ios/android app.

You can enable the "debug only..." option and restart HA. After that you will find a file ca*.json in your custom_components/mbapi2020/messages folder. This file contains the enabled capabilities of your car.

In case it is a license problem that you can purchase more features on your mercedesme portal/app.

BR
Rene
