### ISSUE TITLE
Values jump between actual Value and old Value?

### ISSUE THREAD

**Issue by Ravenbs** [ReneNulschDE/mbapi2020#221]
### The problem

During loading, the Values of our "Smart EQ" jump between the "Start to load" Value of 42% and the actual loading value.
This is how it looks in Home Assistant - makes ist more clear:
![image](https://github.com/ReneNulschDE/mbapi2020/assets/34074340/6eb8a07b-c723-4fb1-a43d-e96e25a86ae9)

Thisis how it looks in Influx (&Grafana):
![image](https://github.com/ReneNulschDE/mbapi2020/assets/34074340/c1892234-0b66-468a-a806-9498e77058e3)

This is how the Data looks like in Influx (dont know how to output raw data from HA):
Fields:
time                car            car_str           device_class_str domain entity_id                         friendly_name  friendly_name_str                 retrievalstatus_str state_class_str timestamp      timestamp_str       unit_str value vin            vin_str
Values:
...
1712655447798482000 1453391151234 W1A4533911K51234 battery          sensor w1a4533911k51234_state_of_charge 1453391151234 W1A4533911K51234 State of Charge VALID               measurement     20240409021052 2024-04-09 02:10:52 PERCENT  42    1453391151234 W1A4533911K51234
1712655455979917000 1453391151234 W1A4533911K51234 battery          sensor w1a4533911k51234_state_of_charge 1453391151234 W1A4533911K51234 State of Charge VALID               measurement     20240409113631 2024-04-09 11:36:31 PERCENT  47    1453391151234 W1A4533911K51234
1712655462800080000 1453391151234 W1A4533911K51234 battery          sensor w1a4533911k51234_state_of_charge 1453391151234 W1A4533911K51234 State of Charge VALID               measurement     20240409021052 2024-04-09 02:10:52 PERCENT  42    1453391151234 W1A4533911K51234
1712655470976120000 1453391151234 W1A4533911K51234 battery          sensor w1a4533911k51234_state_of_charge 1453391151234 W1A4533911K51234 State of Charge VALID               measurement     20240409113631 2024-04-09 11:36:31 PERCENT  47    1453391151234 W1A4533911K51234
1712655477800164000 1453391151234 W1A4533911K51234 battery          sensor w1a4533911k51234_state_of_charge 1453391151234 W1A4533911K51234 State of Charge VALID               measurement     20240409021052 2024-04-09 02:10:52 PERCENT  42    1453391151234 W1A4533911K51234
1712655485977244000 1453391151234 W1A4533911K51234 battery          sensor w1a4533911k51234_state_of_charge 1453391151234 W1A4533911K51234 State of Charge VALID               measurement     20240409113631 2024-04-09 11:36:31 PERCENT  47    1453391151234 W1A4533911K51234
1712655492801273000 1453391151234 W1A4533911K51234 battery          sensor w1a4533911k51234_state_of_charge 1453391151234 W1A4533911K51234 State of Charge VALID               measurement     20240409021052 2024-04-09 02:10:52 PERCENT  42    1453391151234 W1A4533911K51234
...

As you can see, the Database entrys for "42%" and "47%" look nearly the same - exept one difference:
Good values have the correct time in "timestamp_str"
Bad values have all "2024-04-09 02:10:52" in "timestamp_str", even if it is now 12:00. And its always this string in time, not ticking forward... 

It is the same for all other Values - not only SOC.
For example Charging Power also jumps between "0" and "6.9kW" even if it is constantly charging:
![image](https://github.com/ReneNulschDE/mbapi2020/assets/34074340/705b2e22-c2d8-4c30-ae4f-5f445e3648e7)
Same with the timestamp_str here, expect that bad values have: "2024-04-06 06:53:00" and good values the actual time.

### What version of MBAPI2020 do use?

v0.13.0

### What type of installation are you running?

Home Assistant OS

**Comment by ReneNulschDE** [comment]
Interesting. Looks like the MB Servers sending different datasets. Could you go to the options of the component and activate "Debug only: Save messages...". Then let it run until you some of these data jumps. Switch of the debug only:.... option. Go to the folder ***HA-config***/custom_components/mbapi2020/messages, compress all files into an zip or tar. Send the archive to mbdev.issue221@nulsch.de and I can take a look.

**Comment by Ravenbs** [comment]
I will do so. Need to wait a Day until the car is empty to charge again :). Tnx for taking a look, I love your plugin.

**Comment by Ravenbs** [comment]
Short update from today:
Today driving and loading had perfect results - no longer jumping.
Only difference is, that now the debug logging is active.
Will keep the logging on for one more day - then try to disable logging if this has an impact. Will report if anything changes.

**Comment by ReneNulschDE** [comment]
Do you have any other input? Otherwise I'll close the issue.

**Comment by Ravenbs** [comment]
Thank you for tracking this. The issue has never ocurred again since then.
