### ISSUE TITLE
Device Tracker no longer showing correctly

### ISSUE THREAD

**Issue by jimmyfitz** [ReneNulschDE/mbapi2020#222]
### The problem

In the last 2 updates (can't find the page to check version) my car's device_tracker stopped working. This has two impacts, the car Location no longer shows up on my HA map, and the Places sensor based on the car device_tracker is unknown.

### What version of MBAPI2020 do use?

v0.13.0

### What was the last working version of MBAPI2020?

v0.12.

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[config_entry-mbapi2020-7086a365c1f5ed8be1b4c4865dab4803.json](https://github.com/ReneNulschDE/mbapi2020/files/14928922/config_entry-mbapi2020-7086a365c1f5ed8be1b4c4865dab4803.json)

**Comment by jimmyfitz** [comment]
This is the error log from the Places sensor showing that device_tracker isn't sending location.
This error originated from a custom integration.

Logger: custom_components.places.sensor
Source: custom_components/places/sensor.py:511
integration: Places: OpenStreetMap Sensor (documentation, issues)
First occurred: April 9, 2024 at 7:02:23 PM (1 occurrences)
Last logged: April 9, 2024 at 7:02:23 PM

(XXXXXX Location) Tracked Entity (device_tracker.XXXXXX_device_tracker) is not set or is not available. Not Proceeding with Update.

**Comment by ReneNulschDE** [comment]
The data in the log looks correct. Could you please check via [![Open your Home Assistant instance and show your state developer tools.](https://my.home-assistant.io/badges/developer_states.svg)](https://my.home-assistant.io/redirect/developer_states/)
if the device_tracker.XXXXXX_device_tracker is really missing. 

Could be that your places sensor is too fast and gets loaded before the mb-component has created the senor.

**Comment by jimmyfitz** [comment]
It's there (and appears to show data) but ever since the update it's not working.  I've now not only uninstalled and reinstalled Places but I've completely rebuilt my Home Assistant on a new box and the problem persists.  Something is suddenly wrong about the way it's being presented (since it's not showing on the map either).

device_tracker.XXXXXX_device_tracker
XXXXXX Device Tracker
home
source_type: gps latitude: -33.787601 longitude: 151.1157 gps_accuracy: 0 car: XXXXXX vin: XXXXXXXXXXXXXXXXX retrievalstatus: VALID timestamp: 2024-04-10T17:40:58 positionHeading: 217.9 friendly_name: XXXXXX Device Tracker



</body>
</html>[device_tracker.edy87b_device_tracker](http://192.168.11.243:8123/developer-tools/state#)
EDY87B Device Tracker
home	source_type: gps
latitude: -33.787601
longitude: 151.1157
gps_accuracy: 0
car: EDY87B
vin: WDC2539842V206156
retrievalstatus: VALID
timestamp: 2024-04-10T17:40:58
positionHeading: 217.9
friendly_name: EDY87B Device Tracker

**Comment by ReneNulschDE** [comment]
Is your car in the home zone? Then it will not show up in the default map. You can add a map-tile on this tile the cars in the home zones are visible.

Let me check the places component, never used this one...

Background: The HA core team changed a lot in the last two releases when it comes to component loadtimes. as said let me check...

**Comment by ReneNulschDE** [comment]
Places is working for as long disable the option "Use GPS Accuracy"

**Comment by jimmyfitz** [comment]
Thanks Rene,

I'm not sure why it broke when I upgraded, but that definitely seems to be the cause of all my subsequent attempts to fix (by deleting and recreating the sensor) as that GPS accuracy setting defaults to on and I hadnt changed it.

So, it seems like it's a non-issue and user error. Apologies and thanks.


________________________________
