### ISSUE TITLE
Logs being filled with connecting to Mercedes, connected too Mercedes messages

### ISSUE THREAD

**Issue by adamf83** [ReneNulschDE/mbapi2020#223]
### The problem

Since upgrading to the latest version (although I can’t say for sure it wasn’t happening before), my logs are filled with messages like the ones below.  I have at least 4hrs of these messages which is making it hard to see anything else in the log.  I feel this should probably be a debug message that is printed when debug logging is enabled (which it’s not in this case)

2024-04-10 05:41:45.135 INFO (MainThread) [custom_components.mbapi2020.websocket] Connecting to wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/v2/ws
2024-04-10 05:41:45.233 INFO (MainThread) [custom_components.mbapi2020.websocket] Connected to mercedes websocket at wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/v2/ws

### What version of MBAPI2020 do use?

v0.13.0

### What type of installation are you running?

Home Assistant OS

**Comment by ReneNulschDE** [comment]
You could change the logger filter to warning. Just set 
custom_components.mbapi2020.websocket: warning
in your [logger](https://www.home-assistant.io/integrations/logger/) configuration

**Comment by ReneNulschDE** [comment]
Do you have any other input? Otherwise I'll close the issue.
