### ISSUE TITLE
shouldn't odometer sensor have state_class total_increasing instead of measurement?

### ISSUE THREAD

**Issue by thomasdelaet** [ReneNulschDE/mbapi2020#224]
### The problem

odometer currently has measurement state_class which makes it impossible to generate useful statistics-graphs. Shouldn't this be total_increasing instead?

### What version of MBAPI2020 do use?

v0.13.0

### What type of installation are you running?

Home Assistant Core

**Comment by ReneNulschDE** [comment]
Thx, yes, this makes sense. Feel free to create a PR. The setting is in the const.py. I'm on vacation with limited access right now.

**Comment by thomasdelaet** [comment]
pull request created: https://github.com/ReneNulschDE/mbapi2020/pull/225
