### ISSUE TITLE
Remove spikes

### ISSUE THREAD

**Issue by jdiazbb** [ReneNulschDE/mbapi2020#226]
### The problem

How can I remove spikes on fuel graphs like this?
![canvas](https://github.com/ReneNulschDE/mbapi2020/assets/5345120/f7f35f70-5528-4fbe-8c6f-4f19f308acac)

It is my car "Liquid consumption start", and values go up to 100l/km when engine starts. ¿Can I set a "max" value for that graph?

### What version of MBAPI2020 do use?

v0.13.0

### What type of installation are you running?

Home Assistant OS

**Comment by ReneNulschDE** [comment]
Home assistant has standard functions to remove such spikes. Take a look on the filter function. https://www.home-assistant.io/integrations/filter/

**Comment by jdiazbb** [comment]
Thanks for that! i'm a newbie with HA. I'll review it! :)

**Comment by ReneNulschDE** [comment]
Take a look at the community too, there are tons of examples. https://community.home-assistant.io/search?q=Filter%20spikes

I will close the issue. Feel free to join the mbapi2020 thread in this community too.
