### ISSUE TITLE
Not able to set up the integration

### ISSUE THREAD

**Issue by steuerlexi** [ReneNulschDE/mbapi2020#231]
### The problem

The integration seems to have an API issue. See HA Community post [https://community.home-assistant.io/t/mercedes-me-component/41911/1867?u=steuerlexi](url)

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.mbapi2020.oauth
Quelle: custom_components/mbapi2020/oauth.py:312
Integration: MercedesME 2020 (Dokumentation, Probleme)
Erstmals aufgetreten: 10:49:28 (1 Vorkommnisse)
Zuletzt protokolliert: 10:49:28

Error requesting: https://bff.emea-prod.mobilesdk.mercedes-benz.com/v1/login - 0 -```

### What version of MBAPI2020 do use?

v0.13.0

### What was the last working version of MBAPI2020?

v0.13.0

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

<img width="585" alt="image" src="https://github.com/ReneNulschDE/mbapi2020/assets/13646308/683dd5d5-b824-4a41-80f2-405e089cc968">

**Comment by ReneNulschDE** [comment]
thx, the minimum required app version was changed this morning on the mb server side. i have made a fix in the const.py. as you know,  I'm on vacation without a laptop. could someone test this change? if ok, I can publish a new version.

**Comment by DirkV71** [comment]
I have checked your your changes manually in my installtion. Work very well! Thx for your work and have a nice vaction...

**Comment by Roos-AID** [comment]
I also applied the changes manually, and can confirm that it works again.  Thanks and have great vacation.

**Comment by Rainman67** [comment]
After installing the update it works perfectly! I wish you very nice holidays and I also want you to spent a beer or coffee!

**Comment by mreutegg** [comment]
@Sweti934, @Rainman67 you could head over to https://github.com/sponsors/ReneNulschDE and make a donation.

**Comment by Rainman67** [comment]
Hi,

 

habe Dir ein Bierchen gekauft! 😊

 

Danke nochmal für Deine Arbeit und auch heute für's spontane Eingreifen!

 

Liebe Grüße

 

Michael

 

Von: Marcel Reutegger ***@***.***> 
Gesendet: Dienstag, 28. Mai 2024 19:35
An: ReneNulschDE/mbapi2020 ***@***.***>
Cc: Rainman67 ***@***.***>; Mention ***@***.***>
Betreff: Re: [ReneNulschDE/mbapi2020] Not able to set up the integration (Issue #231)

 

@Sweti934 <https://github.com/Sweti934> , @Rainman67 <https://github.com/Rainman67>  you could head over to https://github.com/sponsors/ReneNulschDE and make a donation.

**Comment by UDicke** [comment]
@ReneNulschDE, I planed to apply the changes manually this afternoon, but when I started to do so, you already have overtaken my plan even during your vacation! I applied the proposed update and everything was running again! Brilliant 🥇 

Und jetzt zapf ich Dir auch ein Bier! 😊
Gruß Ulrich
