### ISSUE TITLE
Missing entities

### ISSUE THREAD

**Issue by froggi1930** [ReneNulschDE/mbapi2020#235]
### The problem

Hi there,

last week I got my new car - enabled the integration and got a lot of entities back... Yesterday all my entitities were gone and I had to reconfigure the integration. Now I see much less entities and I am missing one which showed how many kilometers I used the car in only electric mode (not sure how the entity was labeled). Any idea what happened - or how do I get this data?

Thanks,
Georg

### What version of MBAPI2020 do use?

v0.14.0

### What type of installation are you running?

Home Assistant OS

**Comment by ReneNulschDE** [comment]
Hi Georg, as said in the discussions thread, I need the diagnostic file to take a look. If you don't want to share it here, you can send it to mbdev.i235@nulsch.de

**Comment by froggi1930** [comment]
Guten Morgen Rene,

Heute Morgen sind statt 17 wieder 42 Entitäten in HA angezeigt.

Passiert das öfters, oder war das ein Bug bei Mercedes?

Vielen Dank für Deine Unterstützung...

Viele Grüße,

Georg
________________________________
Von: Rene Nulsch ***@***.***>
Gesendet: Donnerstag, 30. Mai 2024 23:11
An: ReneNulschDE/mbapi2020 ***@***.***>
Cc: Georg ***@***.***>; Author ***@***.***>
Betreff: Re: [ReneNulschDE/mbapi2020] Missing entities (Issue #235)


Hi Georg, as said in the discussions thread, I need the diagnostic file to take a look. If you don't want to share it here, you can send it to ***@***.******@***.***>

**Comment by ReneNulschDE** [comment]
Ich vermute ein Bug auf MB Seite. Die haben ein größeres Update gemacht und einige Nutzer haben geschrieben, dass nicht alles aktuell war. (Tech-Background: Sah so aus als hätte MB alle buchbaren Dienste deaktiviert und wieder aktiviert, dies kann dann eine Stunden/Tage dauern...)
