### ISSUE TITLE
All my entities are unavailable

### ISSUE THREAD

**Issue by wnaylor** [ReneNulschDE/mbapi2020#24]
I have 2 MercedesMe 2020 instances showing up in my integrations. One integration has 2 devices and 3 entities and the other has 2 devices and 19 entities. All the entities are unavailable (status in red)
![MercedesMe 2020 HA Integration (p1)](https://user-images.githubusercontent.com/4623959/138894350-ffd3abc4-2af0-43fd-a396-b5e525adc635.png)
![MercedesMe 2020 HA Integration (p2)](https://user-images.githubusercontent.com/4623959/138894352-417fd4c9-ebc4-467f-bd0a-91051487fefc.png)
![MercedesMe 2020 HA Integration (p3)](https://user-images.githubusercontent.com/4623959/138894354-4100c65e-ef01-4f2f-8e58-7d781af604ca.png)
![MercedesMe 2020 HA Integration (p4)](https://user-images.githubusercontent.com/4623959/138894356-dbf687fa-3263-4032-9613-92b6c5a3bc46.png)
<img width="2560" alt="MercedesMe 2020 HA Integration (p5)" src="https://user-images.githubusercontent.com/4623959/138894358-139233ff-d57f-4ecb-aedc-ade733ae9b83.png">
<img width="2560" alt="MercedesMe 2020 HA Integration (p6)" src="https://user-images.githubusercontent.com/4623959/138894359-5134250c-bccb-46e5-b711-446cb664f058.png">
.

**Comment by jackgithome** [comment]
I did an update to HA today and suddenly none of my entities show available either.  Nothing I could do would get them to show available.  Please help.  I use Android and it works fine on Android but not through HA.

**Comment by jackgithome** [comment]
So I was playing around.  I can still remote lock/unlock my car through HA, but for some reason everything shows unavailable.  Not sure what I'm doing wrong.

**Comment by ReneNulschDE** [comment]
@wnaylor : Two integrations are not supported. Please use the secondary driver option to add other cars (see MB portal) to your own account.

@jackgithome: We are discussing this issue in the HA community. rigth?

**Comment by jackgithome** [comment]
Yes, that's correct.
