### ISSUE TITLE
Webapi change

### ISSUE THREAD

**Issue by Wank-ster** [ReneNulschDE/mbapi2020#240]
### The problem

Unable to connect to server.
I had the same problem connecting from evcc but they got it fixed. https://github.com/evcc-io/evcc/pull/14093

![IMG_1873](https://github.com/ReneNulschDE/mbapi2020/assets/142676146/ea7bfe46-6e73-48ac-99e3-dd243dc9861d)

### What version of MBAPI2020 do use?

V0.13.0

### What was the last working version of MBAPI2020?

V0.13.0

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
Error setting up entry xxxxxxxxxx@gmail.com (Region: Europe) for mbapi2020
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 584, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mbapi2020/__init__.py", line 77, in async_setup_entry
    for car in masterdata.get("assignedVehicles"):
               ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by ReneNulschDE** [comment]
Please update to v0.14.0 of the component. Was fixed before I changed it in EVCC. :-)

**Comment by ReneNulschDE** [comment]
Duplicate #231

**Comment by Wank-ster** [comment]
Sorry for bothering you, seems like I missed this update - and of course, THANK YOU!
