### ISSUE TITLE
Geographic violation issue 

### ISSUE THREAD

**Issue by apartment-wharf** [ReneNulschDE/mbapi2020#245]
### The problem
sensor.gc210dp_geofencing_violation
It does not synch in real time.

### What version of MBAPI2020 do use?

V0.15.0

### What type of installation are you running?

Home Assistant OS

**Comment by ReneNulschDE** [comment]
This sensor is a pull sensor. The default update interval is 5 minutes. In case you need a different update interval, you could create an automation and call the service "homeassistant.update_entity" with your geofencing entity "sensor.XXXXX_geofencing_violation"

![image](https://github.com/ReneNulschDE/mbapi2020/assets/33263735/dda98a2e-f96c-46f1-93dd-d1fd0dae14a3)

**Comment by apartment-wharf** [comment]
Even setting the automation
for some reason does not update.

[image: geographic violation.jpg]

It does update the device tracker only.
however it is always set away for some strange reason.  Not sure How  the
tracker works where to set Away / home location.
[image: Screenshot 2024-06-11 140209.jpg]

There the Automation

[image: Screenshot 2024-06-11 140402.jpg]

**Comment by ReneNulschDE** [comment]
Did you create the geofences in the MBApp? Does the geofencing in the mbapp work?

**Comment by apartment-wharf** [comment]
Yes it is created.
I have just noticed that it updated only when the location changes.
So all good then.
Best would be a push request rather then a pull.

How the other sensor works?
device_tracker.gc210dp_device_tracker
It is always set AWAY.

**Comment by ReneNulschDE** [comment]
Can't change this to push as this information is available via MB-API with pull only.

The device_tracker is using the home-assistant zones for the presence detection. See here https://www.home-assistant.io/integrations/zone/

**Comment by ReneNulschDE** [comment]
let me know if you have further questions.

**Comment by apartment-wharf** [comment]
All good. Just Mercedes GPS system is very slow to update. Nothing we can
do about it
