### ISSUE TITLE
W206 - AMG C43 (2024)

### ISSUE THREAD

**Issue by f45tb00t** [ReneNulschDE/mbapi2020#246]
### The problem

Hi,

I am wondering when all entities will be available in the integration.  I don't remember how long it took with my prior E Class Coupe (C238) built in 2022. But there I had like 30+ entities.

With the new AMG I have only 6 entities. Any advice?
Btw. I'm using the newest version of your integration.

FB

### What version of MBAPI2020 do use?

v0.15.0

### What type of installation are you running?

Recent Home Assistant Core

**Comment by ReneNulschDE** [comment]
Are the information available in your mbapp? Are all the services activated in the car/app? Normally, the info should be complete 72 hours after the activation. Keep in mind that you have to restart HA or reload the mbapi2020 integration.

**Comment by ReneNulschDE** [comment]
Is the problem solved?

**Comment by f45tb00t** [comment]
Hello Renè,


I was on a trip to reach the 1500km. ;) sorry for the late reply.

Yes, the issue is solved I guess. Have now 33 entities. It seems not the needed service was enabled. Do you know which precise service is needed for that? Usually I don't like to enable too many services.

**Comment by ReneNulschDE** [comment]
Could you list the available services? This is different from car to car.

**Comment by f45tb00t** [comment]
Hi, just for the sake of completeness I list all of them

Digitale Extras:

Infotainment: 
Digital Light Animations
Digitales Radio
Erweiterte Radio Informationen
Erweiterte Radiosenderverfolgung
Internet Radio
Komfort Datenvolumen
Minigames
Music Streaming
News Flash
Online Suche
Smartphone Integration
Wettervorhersage

Komfort:
Digitale Schlüsselübergabe
Energizing Comfort
Elektronisches Fahrtenbuch
Fahrzeugauffindefunktion
Fernabfrage Fahrzeugstatus (guess this one)
Fernsteuerung Fenster/Schiebedach
Fuel&Pay
Geographische Fahrzeugüberwachung
In-Car Office
Individuelle Empfehlungen
MBUX Sprach-Assistent
Parkservice-Überwachung
Personalisierung
Schnittstelle Drittanbieter: Fahrzeugdaten
Türfernschließung und -entriegelung

Navigation:
Car to X Communication
Fahrzeugstandort
Festplatten-Navigation
Geteilte Navigation
Live Traffic Information
Lokale Suche
Online Kartenupdate
Online Routenführung
Parken für App
Parken für Navigation
Satellitenbilder
Verkehrsbeschränkung
Wetterkarte

Sicherheit und Service:
Fahrzeugferndiagnose
Fahrzeugortung
Geobasierte Online Information für Fahrunktionen
Hilfe bei Fahrzeugdiebstahl
Individuelle Verbrauchsanzeige
Mercedes Benz Notrufsystem
Notfall Schlüsseldeaktivierung
Softwareaktualisierungen
Telediagnose
Unfall & Pannenmanagement
Wartungsmanagement
Weitergabe anonymisierter Fahrzeugdaten an Dritte

**Comment by f45tb00t** [comment]
Still not sure which service is needed. But makes no sense to keep this open.

Thanks again for the oustanding work! :)
