### ISSUE TITLE
How to remove a vehicle

### ISSUE THREAD

**Issue by Dazula** [ReneNulschDE/mbapi2020#25]
Hi, I need to remove a vehicle that I sold.  I can delete all the entities, but I cannot see how to delete the device (vehicle)
What is the process for this.  thank you.

**Comment by ReneNulschDE** [comment]
You mean that you have still access to the old car? On the integration page, click on configure on the MBAPI2020 tile. Add your VIN to the exclude option and restart HA. This filter out this car.

**Comment by Dazula** [comment]
No I don't have access to the car, only you can see the device still in HA.  

Added exclude old VIN, however still shows as 2 devices.

<img width="351" alt="Picture 1" src="https://user-images.githubusercontent.com/76919589/139726520-1b4d6df8-b942-4440-b7eb-4318c85c1f76.png">

**Comment by ReneNulschDE** [comment]
Are you based in the US?

**Comment by ReneNulschDE** [comment]
Hi, I have pushed a fix to the master branch. On startup old cars get removed from the device registry now. Could check this or do you need a new release?

**Comment by ReneNulschDE** [comment]
Fixed with release v0.5.12

**Comment by Dazula** [comment]
Thanks, that worked a treat.

**Comment by ReneNulschDE** [comment]
Hi @akula3 , the only option is to delete the integration from the HA-Integration page and re-add it. It should have no effect on other cars/configuration as long as you have not renamed your entities. (The entity names will be the same after readding)
