### ISSUE TITLE
Device Tracker

### ISSUE THREAD

**Issue by froggi1930** [ReneNulschDE/mbapi2020#250]
### The problem

I have noticed that the GPS position which is shown in HA does not match the position which is shown in the Mercedes meApp.
Is this a common problem?

### What version of MBAPI2020 do use?

v0.15.00

### What type of installation are you running?

Home Assistant OS

**Comment by ReneNulschDE** [comment]
Never heard about this problem except for China. In China you have to enable the GCJ-02 translation in the options of the integration. (And disable for the rest of the world)

Please describe in detail what differences do you see.

**Comment by froggi1930** [comment]
Hi Rene,

Thanks for your message. GCJ-02 translation was enabled, so now it works as expected.

Best regards,

Georg

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
