### ISSUE TITLE
coordinates of tracker are incorrect

### ISSUE THREAD

**Issue by penguin242** [ReneNulschDE/mbapi2020#254]
### The problem

The coordinates returned are of by about 1.000050415956 for latitude and 0.9966484928 for longitude. 

### What version of MBAPI2020 do use?

V0.16.0

### What type of installation are you running?

Home Assistant Core

### Example YAML snippet

```yaml
bypass via helper: 
{{ state_attr('device_tracker.xxxxxxx_device_tracker', 'latitude') / 1.0000504159565269679922767578942}}

{{ state_attr('device_tracker.xxxxxxx_device_tracker', 'longitude') / 0.99664849282758626564702663733325}}
```

**Comment by ReneNulschDE** [comment]
Please share the diagnostic log or search in this log for "enable_china_gcj_02" and the setting.

**Comment by penguin242** [comment]
China off did the trick! thx!
