### ISSUE TITLE
Run this component as standalone service?

### ISSUE THREAD

**Issue by spl01tprivate** [ReneNulschDE/mbapi2020#259]
### The problem

Hi,

I wanted to know, whether it is possible to run this service as standalone service.
I have the use case of pulling the Mercedes Me data and make it available for other services in a stack of IoT tools.
Unfortunately, I am not able to install homeassistant into this stack, which is why, I wanted to ask, whether you maybe got a version of this component, which can be used as standalone service.
I appreciate your awesome work and would be glad if you can help me out on this one 😄 

Kind regards,
Marius

### What version of MBAPI2020 do use?

v0.17.0

### What was the last working version of MBAPI2020?

v0.17.0

### What type of installation are you running?

Home Assistant OS

**Comment by ReneNulschDE** [comment]
I understand the request for a library for use without home assistant very well. Unfortunately, this would increase the complexity in terms of development lifecycle and support without any added value for me. Therefore, I have no current plans to implement this in an extra library.
