### ISSUE TITLE
Km not Miles

### ISSUE THREAD

**Issue by Dazula** [ReneNulschDE/mbapi2020#26]
Hi,  Is this an issue with home assistant or the integration ?

Km Shows when it should be miles.

<img width="224" alt="image" src="https://user-images.githubusercontent.com/76919589/141695893-0395451a-d67a-482b-ac24-c8ab522402ac.png">

<img width="364" alt="image" src="https://user-images.githubusercontent.com/76919589/141696017-8232a671-9c71-4000-8222-05c0edf31765.png">

The car records Km as you can see above and the unit conversation is correct to miles but displays Km not Miles

Thanks

**Comment by ReneNulschDE** [comment]
hi, what is your HA setting? See configuration, general, unit system?

**Comment by Dazula** [comment]
Switching to imperial will show the unit xx mi.

The switch in HA between miles and Km, does not change the unit value, like it does with say the weather. degC/DegF

It will show 100miles and 100km, not 160km.   

So even if I leave as Metric - the Km is not the correct value.

**Comment by ReneNulschDE** [comment]
Let me check. We had this in the HA-Community a year ago. The sensor name is rangeelectric**km**. And the km is hardcorded in the const.py. Sorry, I can't remember and have to look the discussion.

**Comment by ReneNulschDE** [comment]
The value is based on your MB-App setting. If you configured miles in the app then value in HA is miles to. There is a special attribute distance-unit in the odometer sensor that shows the unit. So please align your HA-setting with MB/App setting.

**Comment by Dazula** [comment]
It appears that the value in HA is set by the units settings in HA. There is no way that I could see in HA to set different units for distance, temperature, speed etc. 
<img width="634" alt="image" src="https://user-images.githubusercontent.com/76919589/144742083-5c893378-abf7-4254-9179-d1145503033f.png">

The MercedesMe app does however for different unit types.
<img width="280" alt="image" src="https://user-images.githubusercontent.com/76919589/144742017-90df1065-1198-4550-8625-472f89a489e8.png">

HA shows the correct unit in the sensor, but HA does not use this. 
<img width="366" alt="image" src="https://user-images.githubusercontent.com/76919589/144742131-bb68e4ec-6bf4-43b6-999b-ec357c918fe1.png">

My work around has been to use customisations.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/76919589/144741928-b0e6580f-e49a-417c-b693-41cf386ae648.png">

Then using the following

<img width="284" alt="image" src="https://user-images.githubusercontent.com/76919589/144741993-63ed49fe-4c28-4a28-a788-c208a561fd60.png">

<img width="232" alt="image" src="https://user-images.githubusercontent.com/76919589/144742198-ce12c5db-6054-4919-a39d-4622bf79f01c.png">
