### ISSUE TITLE
Location being shown as Away / never at home

### ISSUE THREAD

**Issue by kmanan** [ReneNulschDE/mbapi2020#260]
### The problem

Hi, running into this weird issue after updating. The car’s location never shows up as home and is stuck on Away. Any ideas that I can try to troubleshoot?

### What version of MBAPI2020 do use?

Latest

### What type of installation are you running?

Home Assistant OS

**Comment by ReneNulschDE** [comment]
Please check if the attributes for positionLat and Long are changing when you move the car. If these values are not changing, check in the official mb-app if you're licenses are expired.

**Comment by kmanan** [comment]
> Please check the device_tracker sensor and check if the attributes for positionLat and Long are changing when you move the car. If these values are not changing, check in the official mb-app if you're licenses are expired.

Thanks, I'll check. I doubt that that's the thing here, subscriptions are all active. The Vehicle Info Card shows the right address and that's the address that's hardcoded as Home in HA in config.yaml. I'll see what the Merc app shows when I drive out.

**Comment by kmanan** [comment]
Nvm. I think I fixed it. The hard-coded radius was too small. The other car wasn't showing up at home either. Increased the radius in config.yaml and seems to be fixed now. User error lol
