### ISSUE TITLE
Charging power state is 'unknown' when not charging

### ISSUE THREAD

**Issue by HertogArjan** [ReneNulschDE/mbapi2020#261]
### The problem

5 days ago I updated my HA installation to core-2024.8.3 and the mercedesme2020 integration from v0.16.0 to v0.17.0. Since then the 'charging power' entity for my Mercedes vehicle frequently has the state 'unknown'. This wasn't the case before the updates.

As far as I can tell from the history this only happens when the vehicle is not charging, however the state isn't always 'unknown' when not charging either. Generally when the car starts a charging session the charging power transitions to an actual value and the state does not become 'unknown' for the duration of the session. After the charging session ended the charging power is recorded as 0 kW for maybe 4-6 hours (this duration is inconsistent) before the state transitions to 'unknown'.

I checked home-assistant.log but could not find any messages from the mbapi2020 integration.

EDIT:
I believe the changes made in commit 1e1caba in sensor.py are the only changes that can explain why this behaviour changed. I see an unknown state is now returned in situations where it wasn't before. 

One change I think is a bit odd is [here](https://github.com/ReneNulschDE/mbapi2020/commit/1e1caba713b8be4bce2c2b4cb08baeb973a68802#diff-1b239a525f45ffeeb7a99cf242594ed1ff1be801aeb85e9c34cd9023e69d5e2dR127-R128) in sensor.py. When self.device_retrieval_status() matches "NOT_RECEIVED" it now returns state STATE_UNKNOWN, However [earlier ](https://github.com/ReneNulschDE/mbapi2020/commit/1e1caba713b8be4bce2c2b4cb08baeb973a68802#diff-1b239a525f45ffeeb7a99cf242594ed1ff1be801aeb85e9c34cd9023e69d5e2dR102-R103) in another class when self.device_retrieval_status() matches "NOT_RECEIVED" the state returned is "NOT_RECEIVED". Is this an error?

EDIT2:
After testing a few changes in sensor.py I now know [these lines from sensor.py](https://github.com/ReneNulschDE/mbapi2020/commit/1e1caba713b8be4bce2c2b4cb08baeb973a68802#diff-1b239a525f45ffeeb7a99cf242594ed1ff1be801aeb85e9c34cd9023e69d5e2dR105-R106) are where the unknown state originates from. If I remove those the behaviour is as before.

### What version of MBAPI2020 do use?

v0.17.0

### What was the last working version of MBAPI2020?

v0.16.0

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

[config_entry-mbapi2020-13d244245781e6192429d55b023cd8ba.json](https://github.com/user-attachments/files/16899299/config_entry-mbapi2020-13d244245781e6192429d55b023cd8ba.json)

**Comment by ReneNulschDE** [comment]
Thanks for reporting and analyzing. Could you please enable the option "Debug only: Save server messages..." and let in run until you see the behavior? Then compress all the files in the custom_components/mbapi2020/messages folder and send the file to mbdev.i261@nulsch.de

Disable the option afterwards again.

**Comment by ReneNulschDE** [comment]
thanks for the discussion via email. This [commit](https://github.com/ReneNulschDE/mbapi2020/commit/03503f4cf1641d4873afa517ad939f22fc9cd19b) contains the relevant change. 

Change:
Whenever the sensor has a default of 0 and the status from the API is "not provided by the car" (3) then the default value is used.

**Comment by HertogArjan** [comment]
I've applied your changes and so far it seems to be working as expected, no more unknown state. I will check again in a couple of days. Thanks again for your quick efforts

**Comment by ReneNulschDE** [comment]
Fixed in v0.18.0 - thanks for your support
