### ISSUE TITLE
sensor._charge_flap_dc_status

### ISSUE THREAD

**Issue by hwb45** [ReneNulschDE/mbapi2020#262]
### The problem

I am trying to use this sensor in an automation so when it is open and I am at home, then I can pause my solar batteries. The home flag works ok, but there is no value of Open or Closed in the entity shown in the title, just unknown and unavailable 

Don't know if it is my setup or the entity definition.

Can you let know

Thanks 
Henry

### What version of MBAPI2020 do use?

v0.18.1

### What type of installation are you running?

Home Assistant OS

**Comment by ReneNulschDE** [comment]
Hi Henry, could you please share the diagnostic log.

The MBAPI2020 integration provides the ability to [download diagnostic data](https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics).
It would really help if you could download the diagnostics data for the account/hub you are having issues with, and drag-and-drop that file into the textbox below.
It generally allows pinpointing defects and thus resolving issues faster.

**Comment by hwb45** [comment]
There are no diagnostics for this issue. I have taken some pictures of the entity. The charge flap is currently open, but there is no entry for open or closed.

![image](https://github.com/user-attachments/assets/5441a031-1677-4a3b-9149-091c84b21a7d)

![image](https://github.com/user-attachments/assets/54bfc7a0-25a8-4b20-a758-8394469b0211)

![image](https://github.com/user-attachments/assets/7107ebdf-6d92-4025-bc4c-de623ca418e3)

**Comment by ReneNulschDE** [comment]
The internal state values are translated in the frontend to "Open", "Close" & "Flap pressed" . 

``` 
0=open, 
1=closed, 
2=flap_pressed
``` 

So please check for `0` in your automation.

You can also use the "developer tools"/"States" page to check the internal values:
![image](https://github.com/user-attachments/assets/27b62d78-0cfd-4f02-a668-e17511dd30e8)
