### ISSUE TITLE
Missing Precondition State Sensor on Model 214 Hybrid

### ISSUE THREAD

**Issue by philippwaller** [ReneNulschDE/mbapi2020#263]
### The problem

I'm using the integration with an S214 Hybrid and noticed that while I can start and stop the preconditioning just fine, I'm not getting any sensor data for its status. I took a quick look at the implementation and saw that the response expects a precond node in the JSON. However, for the 214 Hybrid, this node is null. Instead, the attributes seem to be nested under the electric attribute.

<img width="529" alt="Bildschirmfoto 2024-09-29 um 19 00 20" src="https://github.com/user-attachments/assets/394fa5f7-3449-491d-ba00-4a3b27836527">

I've attached the diagnostic data with ad-hoc preconditioning turned on and off for your reference.

### What version of MBAPI2020 do use?

2024.10.0b4

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[precon_off.json](https://github.com/user-attachments/files/17180118/precon_off.json)
[precon_on.json](https://github.com/user-attachments/files/17180119/precon_on.json)

**Comment by ReneNulschDE** [comment]
Thanks for this detailed report. The precond status is reported via two attributes (precondNow or precondActive) of the sensor `range_electric`. There is no special sensor for this feature currently. Please check the range_electric sensor.

You can build your own sensor via a template sensor (`value_template: "{{ state_attr('sensor.XXX_range_electric', 'precondNow') or state_attr('sensor.XXX_range_electric', 'precondActive') }}"`).

**Comment by philippwaller** [comment]
Hey @ReneNulschDE,

Your tip about the precond attributes was spot on—I had overlooked them before.

I've also put together a proposal to improve the integration of the precondition attribute and created a PR #264 for it. Let's bounce some ideas around and see how we can further optimize it.

Looking forward to your feedback!

**Comment by philippwaller** [comment]
solved by PR #264.
