### ISSUE TITLE
No car information registered for this account. Check the MB website with the same account. Giving up...

### ISSUE THREAD

**Issue by wookash** [ReneNulschDE/mbapi2020#278]
### The problem

Integration suddenly stopped working and gives this message in logs: No car information registered for this account. Check the MB website with the same account. Giving up...

### What version of MBAPI2020 do use?

2024.11.2

### What was the last working version of MBAPI2020?

v0.19.1

### What type of installation are you running?

Home Assistant Container

### Anything in the logs that might be useful for us?

```txt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mbapi2020/__init__.py", line 207, in async_setup_entry
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: No car information registered for this account. Check the MB website with the same account. Giving up...
```

### Additional information

The same version of extension was working fine, it just stopped working suddenly today

**Comment by multinet33** [comment]
Same here

**Comment by ReneNulschDE** [comment]
Could you enable the debug log and restart HA? Wait until the error occurs and share all the lines with mbapi2020.

The error means that we found some masterdata and we could connect to the websocket-backend. But the backend has not delivered any car information in the first 30sec.

Does the official MB mobile app works?

**Comment by wookash** [comment]
Hello. The mobile app was working, that’s why I created this issue. However, I think the problem was on the Mercedes side as I’ve also tried logging in via web and their webpage showed issues with certificate. Anyway, the integration is working fine now. I’m closing this. Thank you for quick response!
