### ISSUE TITLE
Ignition state values are door values 

### ISSUE THREAD

**Issue by blferreira** [ReneNulschDE/mbapi2020#280]
### The problem

From home assistant I’m using ignition state for some automations to detect when car is turned on. 
since last update this sensor is reporting the same value as door state

### What version of MBAPI2020 do use?

Latest

### What was the last working version of MBAPI2020?

Latest

### What type of installation are you running?

Home Assistant Container

**Comment by ReneNulschDE** [comment]
The ignition sensor got just a frontend translation. Internal values are the same:
```
      "ignitionstate": {
        "state": {
          "0": "Locked",
          "1": "Off",
          "2": "Accessory",
          "4": "On",
          "5": "Start"
        }
      },
```

Please describe the problem more detailed/share your automation code...

**Comment by blferreira** [comment]
Thanks! You should be right. The added translation might be the reason for the home assistant automation conditions stop working.
