### ISSUE TITLE
looses connection to the car 

### ISSUE THREAD

**Issue by owskov** [ReneNulschDE/mbapi2020#282]
### The problem

I need to reload the integration (or restart Home Assistant) to receive updated information about my car in Home Assistant. This issue started recently.

I use the battery level from the integration to decide when and how long the car charger should run.

As I am new to Home Assistant, I’m unsure whether the issue lies in the HA configuration or the integration itself.

The "polling for updates" feature is enabled.

### What version of MBAPI2020 do use?

V0.18.1

### What type of installation are you running?

Home Assistant Core

### Diagnostics information

[config_entry-mbapi2020-01J79MR364YV8JA28490CH5GEE (1).json](https://github.com/user-attachments/files/17892504/config_entry-mbapi2020-01J79MR364YV8JA28490CH5GEE.1.json)

**Comment by ReneNulschDE** [comment]
Duplicate #279 

polling is used only for the Geofencing sensor. The rest is push websocket connection.

**Comment by Hooshee** [comment]
I have the same issue. It works for about two days, then it loses connection (without warning), and shows the last synced data. If I reload integration, everything is back to normal for another two days. 

![image](https://github.com/user-attachments/assets/1df4b165-0afa-45bb-a523-4fbefe559f62)
 No entries for yesterday and today, while I was moving around with the car. But not only the location is not refreshing, petrol level, km stands, etc is from the nov 22th state.

**Comment by ReneNulschDE** [comment]
duplicate #279  - please review this case and the solutions/beta-versions

**Comment by ReneNulschDE** [comment]
v0.20.0 is published.
