### ISSUE TITLE
v0.20.1 Failed to set up

### ISSUE THREAD

**Issue by lasry1** [ReneNulschDE/mbapi2020#284]
### The problem

Failed to set up, no entities found (it was previously working fine and i can see my car through the mercedes me APP and website)

### What version of MBAPI2020 do use?

v0.20.1

### What type of installation are you running?

Home Assistant OS

**Comment by ReneNulschDE** [comment]
I see this too... Let me analyze it.

**Comment by ReneNulschDE** [comment]
I have published a beta release v0.20.2-beta.1 - This should solve 95% of the use-cases...

**Comment by lasry1** [comment]
v0.20.2-beta.1 solved my issue! incredible work!

**Comment by geertmeersman** [comment]
v0.20.2-beta.1 working here too. Thanks Rene

**Comment by Mosty510** [comment]
working here too! Thanks for the fast work!!

**Comment by ptruman** [comment]
Ditto - that's resolved for me.

**Comment by firstcolle** [comment]
is the double account still necessary?
in this case how can i invite the new account? on the app i can only invite via qr code

**Comment by ReneNulschDE** [comment]
I assume, yes - we will see it in the evening when the block will happen. This case here is afaik not related to the blocking.

To invite the second user with on mobile phone:
1. Create the qr-code with the primary account in the app end send the picture to a PC
2. Logout in the app
3. Login with the second user 
4. Use the QR code to add the device.

The webportal invite is not stable and failed most of the time. But the QR code invite is quite stable.

**Comment by thomasdelaet** [comment]
this might be a super naive question but is there a way to get in touch with mercedes team who manages this API to help them understand that there is actually value in keeping these things stable / having a bit of a more community focus around this?

**Comment by marcert** [comment]
Hi,
setup was possible with the updated beta version- but it seems that I do not get anymore updates of the data (primary user is used on the mobile and a secondary user on HA).

**Comment by ReneNulschDE** [comment]
Could you share the debug log?

**Comment by marcert** [comment]
How often will there be data from the integration? It will be helpful to know how long the debug protocol should be enabled. Or can I force to get something in?

**Comment by ReneNulschDE** [comment]
Data would be every few seconds... Go to the integration page. Click on Enable Debug log. Reload the component. wait 2-3 min. Disable the debug log. then a file is downloaded

**Comment by ReneNulschDE** [comment]
ok, 429 - then we have to wait until tomorrow... :-(

**Comment by dharvey242** [comment]
How do you download the beta?  I have the same issue.  Created a second account, added it to the first.  Using the second account for HA.  Same error message.  No car information found...

**Comment by ReneNulschDE** [comment]
Beta? We have a general version v0.20.2 available since yesterday already. Go to HACS and check for a new version.

**Comment by dharvey242** [comment]
> Beta? We have a general version v0.20.2 available since yesterday already. Go to HACS and check for a new version.

Confirmed as working - Thanks!!!! added the dashboard too!
