### ISSUE TITLE
Smart missing after v0.20.2

### ISSUE THREAD

**Issue by Tgxcorporation** [ReneNulschDE/mbapi2020#285]
### The problem

My Smart EQ is missing after installing v0.20.2. 
Was ok before.

Errors in log:

Registratore: custom_components.mbapi2020.client
Fonte: custom_components/mbapi2020/client.py:328
Integrazione: MercedesME 2020 ([documentazione](https://github.com/ReneNulschDE/mbapi2020), [problemi](https://github.com/ReneNulschDE/mbapi2020/issues))
Prima occorrenza: 01:06:10 (15 occorrenze)
Ultima registrazione: 09:57:35

Flow Problem - VepUpdate for unknown car: W1A45XXXXXXXX6361

### What version of MBAPI2020 do use?

v0.20.2

### What was the last working version of MBAPI2020?

v0.20.1

### What type of installation are you running?

Home Assistant OS

**Comment by Tgxcorporation** [comment]
I tried to invite you using the smart.dev.invite@nulsch.de email address on the Mercedes site. 
The site gives an error when adding the email address. Cannot add the secondary user.

**Comment by user86000** [comment]
same here with 0.20.2
smart eq

**Comment by lucabacchipg** [comment]
mee too. 2 smart no data with 0.20.2

**Comment by ReneNulschDE** [comment]
@Tgxcorporation : Could you send me an email? [smart.dev.invite@nulsch.de](mailto:smart.dev.invite@nulsch.de)

**Comment by ReneNulschDE** [comment]
I have published a new version v0.20.3 - This one should bring the Smart cars back. Thanks to @Tgxcorporation for the access.

**Comment by Tgxcorporation** [comment]
Thank you for your quick reply! It's working again!
