### ISSUE TITLE
Entities are not loaded 

### ISSUE THREAD

**Issue by OMENITA** [ReneNulschDE/mbapi2020#287]
### The problem

Hello No data is loaded . 

Current version v0.20.3 installed . Auto = Smart eq 2017
EU the values are available in the app 

Installed since October 2023 until Friday without problems.
 Tested 
New installation 
log out and log in again 
Delete account add new 
Reconnect account with pin email 
Add 2 hubs . 
Create 2 Email = No data available 
![1](https://github.com/user-attachments/assets/7ff6bed0-855b-4693-8c23-1f8bdf6405d2)
![2](https://github.com/user-attachments/assets/4875d84d-84ae-4efc-8c9f-c5514aa780bd)
![5](https://github.com/user-attachments/assets/6
![3](https://github.com/user-attachments/assets/4ecbf0bf-0b3e-4537-96d4-c5676de33ffc)
6fe2603-f064-4030-b553-afafde94501e)
![6](https://github.com/user-attachments/assets/990bbba6-1569-446e-bcfb-706d02b977be)

### What version of MBAPI2020 do use?

v0.20.3

### What was the last working version of MBAPI2020?

v0.19

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[config_entry-mbapi2020-01JAB86QJWCXRKJYE0HA81VX72-3.json](https://github.com/user-attachments/files/17970294/config_entry-mbapi2020-01JAB86QJWCXRKJYE0HA81VX72-3.json)

### Anything in the logs that might be useful for us?

```txt
Account should not be blocked according to me. I can log in to the website normally
```

**Comment by ReneNulschDE** [comment]
could you share the error log?

**Comment by OMENITA** [comment]
[error_log (1).zip](https://github.com/user-attachments/files/17970318/error_log.1.zip)

Thank you for your quick reply. Attached is an error log from this morning . Hope it fits 

greetings

**Comment by ReneNulschDE** [comment]
Error with the websocket connection (retry counter: 2): 429 - Invalid response status

Your account is blocked and the component will reload at around 1am...

Did you read the release notes 0.20.2 or [here](https://community.home-assistant.io/t/mercedes-me-component/41911/2202)?

**Comment by OMENITA** [comment]
Yes, I have read these. But I think the blocking has taken place because I have entered the account umpteen times today. Interesting is but in the homepage https://www.smart.mercedes-benz.com/ I can log in without problems.

How can I best proceed now ? as already mentioned it ran without problems since september october :-) 

ps thanks for your help

**Comment by ReneNulschDE** [comment]
Wait until tomorrow - the account gets unblocked automatically. Make sure that you follow the best practices that I shared in the release notes. ... and, maybe we will see a new release in the next days who will try to solve it too

**Comment by ReneNulschDE** [comment]
reopen the case in case it does not work.

**Comment by OMENITA** [comment]
Thank you very much for the super quick reply.

**Comment by ReneNulschDE** [comment]
btw: The portal https://www.smart.mercedes-benz.com/ works because this one is different then the MB-Portal... We have a difference here. And yes, the release note was not so focussed on the Smart cars - the main user group is MB - Smart Cars is working just by "mistake"/"surprise" :-)

**Comment by OMENITA** [comment]
:-) then it's great if it still works. 
Today's registration was successful. I have now also got the 2nd account up and running and this has now finally received data. Had to rewrite this 2-3 times 
![Smart](https://github.com/user-attachments/assets/a79e80ef-7f28-41a6-a93c-00c6033c23d6)

Thanks again for the nice support 

Greetings
