### ISSUE TITLE
Ausheat Start & Stop switches Missing while Auxheat status sensor is working fine.

### ISSUE THREAD

**Issue by TrippleP** [ReneNulschDE/mbapi2020#288]
### The problem

My aux heat Automation was not working for a few days and today I had the time to check.
So i switched to a dedicated integration User for my Mercedes Me account (logedin to the app before)
AuxHeat start and stop is missing in my entity list.
I tried to use preclimate, but this does start the blower only and not the AuxHeat.

### What version of MBAPI2020 do use?

v0.20.3

### What type of installation are you running?

Home Assistant Container

### Diagnostics information

[config_entry-mbapi2020-01JDXMF0W8XASE6C5WRDC24W0B.json](https://github.com/user-attachments/files/17978716/config_entry-mbapi2020-01JDXMF0W8XASE6C5WRDC24W0B.json)

**Comment by ReneNulschDE** [comment]
Thanks for reporting this and the adding the diagnostic report. (This helps a lot)

Looks like MB introduced a new capability "Auxheat" that I don't check. (Currently I check for "AUXHEAT_START" and this is False in your account)... Until this is fixed...

- Go to the mbapi2020 integration page (Settings, Devices..., MB Api 2020)
- Click on Configure
- Activate "Disable capabilities check"
- Click save, the component gets reloaded

Please check again and report back.

**Comment by TrippleP** [comment]
Thanks for the swift response.
One additional entity but thats not the auxheat start.
btw. we can switch to German if you prefer.

[config_entry-mbapi2020-01JE3TB5GS13YDMK4VX1KHP197.json](https://github.com/user-attachments/files/17979243/config_entry-mbapi2020-01JE3TB5GS13YDMK4VX1KHP197.json)

**Comment by ReneNulschDE** [comment]
Please let us first check if the service/action is working.

- Go to Developer Tools, Actions 
- Select MBAPI... AuxHeat Start
- Add your FIN

Click start and check the error.log

**Comment by TrippleP** [comment]
From Dev Tools it works...

**Comment by ReneNulschDE** [comment]
OK, so just the buttons are missing? Do you get the Switch?

**Comment by TrippleP** [comment]
When checking the Entities in the mbapi I see the AuxHeat status listed only.
Same if I try to add it back to the Dashboard.

**Comment by ReneNulschDE** [comment]
ok, let me check/fix it.

**Comment by ReneNulschDE** [comment]
One last ask:

Could you enable the debug logging on the mbapi2020 integration page and restart HA? Wait 2min after the restart and click disable debug log. You get a file downloaded. Please send this to mbdev.i288@nulsch.de. Thx

**Comment by TrippleP** [comment]
done

**Comment by ReneNulschDE** [comment]
Thanks for sharing the files. I have fixed this and it is part of the release v0.21.0-beta.1 - However, this test release contains some other critical changes. Keep your current workaround and wait for the next stable release. Install the test release only in case you have some deeper experience with HA and the MBAPI2020 component... - I'll close this for now, feel free to open it again, in case this is not solved. Thanks again for sharing the details.
