### ISSUE TITLE
Suggestion to improve readme

### ISSUE THREAD

**Issue by sondree** [ReneNulschDE/mbapi2020#29]
Nice work! Thanks for sharing this addon. 

When installing I found the following statement in the readme confusing: 

```PIN: Security PIN to execute special services. Please use your MB mobile app to setup```

My mobile app has the option of setting a pin, but this is a 4 digit pin and not the pin you want. I suggest that the readme explictly states the steps required to install the addon:

1. Install the addon through HACS
2. Add the addon as an integration under Configuration->Integrations
3. Add the pin received by email after completing the username step. This pin is valid for 15min.

At least thats how it worked for me. Thanks!

**Comment by ReneNulschDE** [comment]
Hi, Thanks. Yes, right the doc is not 100% clear. However the Security PIN is used to Open the windows and doors and needs the setup via the MB-App. Let me change the doc a little bit...

**Comment by ReneNulschDE** [comment]
Added with commit https://github.com/ReneNulschDE/mbapi2020/commit/ee163898b1776febc393eb4833c81c4feb813783
