### ISSUE TITLE
Broken since 2024.12 or just me.? (resolved)

### ISSUE THREAD

**Issue by roperstv** [ReneNulschDE/mbapi2020#290]
### The problem

post the 2024.12 update no reported entities working.
Ver v0.20.3
deleted and re-added integration.
re-configured hub succefully
restarted HA
no device or entities showing below hub.

if anyone could confirm working in 2024.12 be greatful,

Thanks

### What version of MBAPI2020 do use?

V2024.12

### What was the last working version of MBAPI2020?

v0.20.3

### What type of installation are you running?

Home Assistant Core

### Diagnostics information

"integration_manifest": {
    "domain": "mbapi2020",
    "name": "MercedesME 2020",
    "codeowners": [
      "ReneNulschDE"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/ReneNulschDE/mbapi2020",
    "integration_type": "hub",
    "iot_class": "cloud_push",
    "issue_tracker": "https://github.com/ReneNulschDE/mbapi2020/issues",
    "loggers": [
      "custom_components.mbapi2020"
    ],
    "requirements": [
      "protobuf>=3.19.1"
    ],
    "version": "v0.20.3",
    "is_built_in": false,
    "overwrites_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 0.004230429000017466
    },
    "_removed for identity purpose but value in origin_": {
      "config_entry_setup": 35.992655075000584
    }
  },
  "data": {
    "entry": {
      "created_at": "2024-12-04T23:07:34.933020+00:00",
      "data": {
        "nonce": "removed for identity purpose but value in origin",
        "region": "Europe",
        "token": {
          "access_token": "**REDACTED**",
          "expires_at": 1733368053,
          "expires_in": 14399,
          "refresh_token": "**REDACTED**",
          "token_type": "Bearer"
        },
        "username": "**REDACTED**"
      },
      "discovery_keys": {},
      "disabled_by": null,
      "domain": "mbapi2020",
      "entry_id": "_removed for identity purpose but value in origin_",
      "minor_version": 1,
      "modified_at": "2024-12-04T23:20:38.312908+00:00",
      "options": {
        "cap_check_disabled": false,
        "delete_auth_file": false,
        "enable_china_gcj_02": false,
        "excluded_cars": "_removed for identity purpose but value in origin_",
        "pin": "**REDACTED**",
        "save_files": false
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "title": "_removed for identity purpose but email in origin_ (Region: Europe)",
      "unique_id": "**REDACTED**",
      "version": 1

### Anything in the logs that might be useful for us?

```txt
Integration created succefully upon inputing my 6 pin email verification.
Just no entities showing.
Has worked flawless prior the 2024.12 update.

Best Regards
```

**Comment by HertogArjan** [comment]
I can verify the component IS working for me after installing 2024.12. I am using a docker install. 

Did you check the logs for any reported errors? In my case it didn't work initially because my account was blocked by Mercedes (429 Too many requests), but after 00:00 GMT it started working again.

**Comment by ReneNulschDE** [comment]
@roperstv : I would second the comment from @HertogArjan . I'm developing with the next version of HA and test the last 3 three releases. So this should not be a problem with 2024.12. I expect also that this is the "account blocked"- error 429 Problem. Please check again, normally the component gets reloaded at 00:01 GMT and the sensors should be back.

**Comment by roperstv** [comment]
Thanks [ReneNulschDE] / [HertogArjan]

bizarrely only started occurring after the core update it may of simply been coincidental. 
Re-added again this morning and is working flawless, I'll put this down to too many requests/temp block.

Can close this one, thanks all.

**Comment by ReneNulschDE** [comment]
Thanks for the retest... see [here](https://community.home-assistant.io/t/mercedes-me-component/41911/2262) for the latest status regarding the http429
