### ISSUE TITLE
Mercedes Vito -24 PreHeat not visable to control

### ISSUE THREAD

**Issue by Anden78** [ReneNulschDE/mbapi2020#297]
### The problem

Hi
I have a Mercedes Vito -24 with PreHeat/timer, and it is not visable at all i HA? Everything else seems to be shown correctly. The only Switch I have in HA for it, is the Lock/Unlock. 
If I use the lock feature it doesn’t work properly due to its slowness. But if I use the MB app, the status in HA changes quite fast. 

Note: I have only one account (same in HA as MB app) as it is completely impossible to change user in the app to login as a different user. And as long as that other user, created in MB Me dashboard, isnt verified thrue the app, it is not possible to login as a different user, as I cannot verify the second user. Its a Moment 22 situation and MB support doesnt really understand anything….Any ideas?

### What version of MBAPI2020 do use?

V0.21.0

### What type of installation are you running?

Home Assistant OS

## System Information

version | core-2024.12.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.51-haos-raspi
arch | aarch64
timezone | Europe/Stockholm
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1484
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 58.0 GB
disk_used | 12.8 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS (0.9.0), File editor (5.8.0), Terminal & SSH (9.15.0), Samba share (12.3.2), Home Assistant Google Drive Backup (0.112.1), Matter Server (6.6.1), Node-RED (18.1.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 3
views | 10
mode | storage

</details>

<details><summary>MercedesME 2020</summary>

api_endpoint_reachable | ok
-- | --
websocket_connection_state | closed
cars_connected | 1
version | v0.21.0

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 29 november 2024 23:08
-- | --
current_recorder_run | 12 december 2024 13:58
estimated_db_size | 620.61 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by ReneNulschDE** [comment]
Could you share a [diagnostic report](https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics) and a [debug log](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging) (Replace MQTT in the Docs with MBAPI2020? --> [mbdev.i297@nulsch.de](mailto:mbdev.i297@nulsch.de)

After enabling the debug log, start a action that is slow currently. 

For the preclimate action:
Please start the action/service `mbapi2020.preheat_start_departure_time`
add your vin and set the timer value to the result of `now().hour * 60 + now().minute + 15` - example: Current time is 14:15 then 14*60+15+15 = 870

**Comment by Anden78** [comment]
Hi

I found the problem now.
I had to tick the "Disable capabilities check". So now it works flawless
and seamlessly :)

Wow what a great work you have done

Many thanks

//Andreas

Den fre 13 dec. 2024 kl 08:09 skrev Rene Nulsch ***@***.***>:
