### ISSUE TITLE
Error with the websocket connection

### ISSUE THREAD

**Issue by pstoian** [ReneNulschDE/mbapi2020#3]
I am in Dallas TX / US region 
Using Mercedes ME / mbrace application
Vehicle: 2017 GLS450

After I have installed the custom repo under HACS - and installed the integration under Configuration > Integrations - this is what I see: 

![image](https://user-images.githubusercontent.com/11281042/103560662-bc2ee300-4e7d-11eb-8def-42aca6abdc08.png)

Below is the log error:
****************************************************************************

Logger: custom_components.mbapi2020.client
Source: custom_components/mbapi2020/client.py:175
Integration: MercedesME 2020 (documentation, issues)
First occurred: 10:37:27 AM (1 occurrences)
Last logged: 10:37:27 AM

Error with the websocket connection: Received message 257:None is not bytes

**********************************************************************************************

Thank you for your support

**Comment by ReneNulschDE** [comment]
Hi,

this component does not work for the US market currently. However, it looks like that the MB-Dev team is working on it based on the feature toggles of the app. Please wait for the new MB app announcement in your market. In the past, it took 12 month until EU features have been available in the US market. So only 9 months left.

If your car was built in 2019 or later you can check this repo: https://github.com/ReneNulschDE/mbapipy
But please accept that this repo is not supported from my side anymore.
