### ISSUE TITLE
Devicetracker permanently offline

### ISSUE THREAD

**Issue by kohlsalem** [ReneNulschDE/mbapi2020#30]
Hi, 

i installed this integration on my hassos running on a odroid device with a Star2.3 Mercedes since December 2021. 

So far i was very happy with all the automations i run on it.  Things like "Cold? Home? Workday? So start Aux Heater". This is so awsome :-). Or at least it was :-/.

Pretty exactly one month later the device_tracker is permanently shown as "unavailable". The rest of the integration parts still work perfectly. Just the device tracker.

Is there anything i can do to fix it, or is this a bug?

Thanks
Michael

**Comment by ReneNulschDE** [comment]
is one of your licenses expired? How old is your car?

**Comment by kohlsalem** [comment]
The car is from December 21, so if a license would expire after 1 month, this could be the case. However:

- The positioning is shown at the mercedes.me app
- Except "Internet in the Car" and "Support on Car Theft" all 43 (Wtf) Services are active, Including Car Position (Fahrzeugstandort) 

So i could not see a cause there...

**Comment by ReneNulschDE** [comment]
Could you enable the option "Debug only..." in the options of the integrations? Then 
- restart HA
- wait 3 min
- disable the debug option
- zip the files in custom_components/mbapi2020/messages
- share it via email mb.dev(-at-)nulsch.de or as a private message in the [HA-community](https://community.home-assistant.io/t/mercedes-me-component/41911/1117)

**Comment by kohlsalem** [comment]
@ReneNulschDE , the described issue seems to be a clear layer8 problem :-(

When i wrote "The positioning is shown at the mercedes.me app" i mixed my phone position with the car. In my defense: I sit 1,5 meters away from the car. Trying do redo while the car was away i have seen my fault. Clicking the right icon, the app states, that the location is suppressed. ("Aaaargl") Still it took me a while to find that option in the car well hidden in the WLan and Buetooth section.   

Doing the search i updated the cars system OTA; now i cant connect at all; even delete/reconnect is not possible, but this should be a different issue, therefor i close here.

Thanks for your help!

**Comment by kohlsalem** [comment]
After rebooting HA twice it runs now smoothly again :-) :
