### ISSUE TITLE
Error setting up entry mbapi2020 for mbapi2020

### ISSUE THREAD

**Issue by stitch992** [ReneNulschDE/mbapi2020#32]
Newbie on HA so excuse in case of unnnecessary issue rasing. 

The plugin worked fine for me but cannot connect to the service since midday today. Have attached the log below. 

Thanks for looking into it. 

Cheers
Armin

![image](https://user-images.githubusercontent.com/96181539/149354403-776fefb4-4e82-40f6-bf6f-1c3b78b70002.png)

**Comment by ReneNulschDE** [comment]
should be fixed with release v0.6.0

**Comment by Citrowallon** [comment]
Mamy thanks for reactivity...
