### ISSUE TITLE
Use string state instead of numerical

### ISSUE THREAD

**Issue by skyborgff** [ReneNulschDE/mbapi2020#37]
Could you change the numerical states to string, so for example, instead of Ignition state being 1, 2 ,3, ... , it would be the equivalent in Description_short .

**Comment by ReneNulschDE** [comment]
Currently, I do not have a list of all the potential string-values for all the attributes. This would add additional problems from an translation perspective too. And, it would break all the stuff that the users have build before. Therefore, I'm not a fan of doing this. Why do you not start a discussion in the [HA-Community ](https://community.home-assistant.io/t/mercedes-me-component/41911)for this integration.

Will close this here and happy to reopen after we heard the community.
