### ISSUE TITLE
Pinned dependency for protobuf causes errors in HA 2022.02

### ISSUE THREAD

**Issue by mountainsandcode** [ReneNulschDE/mbapi2020#39]
The pinned dependency version for protobuf in mbapi2020 causes an issue when using HA 2022.02 because it clashes with the built-in AppleTV integration https://github.com/postlund/pyatv/issues/1641 https://github.com/home-assistant/core/issues/65498

Ideally, the version pinning for protobuf should be removed.

**Comment by apfelflo89** [comment]
Yeah for me too! Could you at least bump up the dependencies?

**Comment by apfelflo89** [comment]
Can be solved for now by deleting mbapi2020, upgrading and then get it again via HACS but remove `  "requirements": ["protobuf==3.14.0"],` from the manifest.json . Works for me at least.

**Comment by ReneNulschDE** [comment]
I have created a new release v0.6.3 and updated the dependency of protobuf to 3.19.1

**Comment by ReneNulschDE** [comment]
I can't remove the pinned version because it will not work if no other component has installed protobuf before. Removing the requirement will just work in case you use the HA appletv integration too.

**Comment by apfelflo89** [comment]
Hey Rene thank you for the quick fix! How about putting   `"requirements":` ["protobuf >=3.19.1"],` in the manifest so you don't need to change your code in case HA gets a bump in the protobuf version and mbapi just looks for a version greater than you expect? Should be more update safe.
Thank you

**Comment by ReneNulschDE** [comment]
Tested this and saw that then an error with the HA Nest component when protobuf 3.19.4 gets installed…

**Comment by WizBangCrash** [comment]
HA 2023.1.1 has core components using protobuf v4.21.12
When I updated to this version of HA I get the following error message in the logs:
```
2023-01-05 21:26:48.069 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package protobuf>=3.19.1,<4: ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/.local'
```
Is mbapi2020 really required to have a 3.x version?

I modified the manifest.json file to `"requirements": ["protobuf>=3.19.1"]` and restarted. Everything seems to be working fine with the core version of 4.21.12

**Comment by ReneNulschDE** [comment]
The beta release v0.8.0b2 was released yesterday and it's fixed in this version.

**Comment by WizBangCrash** [comment]
Thank you. Just downloaded and installed. Working nicely. Thanks.
