### ISSUE TITLE
Integration crashing "after a while" - runs fine after HA restart

### ISSUE THREAD

**Issue by jhhbe** [ReneNulschDE/mbapi2020#4]
hi,

I'm on version 2020.12.0 and currently running version 5.8 on an RPI4 - version of mbapi2020 is 209f520

I have debug on so could provide more information if needed.

Logger: homeassistant
Source: custom_components/mbapi2020/websocket.py:96
First occurred: January 5, 2021, 11:19:47 PM (5 occurrences)
Last logged: 5:58:50 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/mbapi2020/client.py", line 169, in connect
    await self.websocket.connect(on_data, on_connect, on_disconnect)
  File "/config/custom_components/mbapi2020/websocket.py", line 96, in connect
    res_raw = await s.receive_bytes()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_ws.py", line 284, in receive_bytes
    raise TypeError(
TypeError: Received message 257:None is not bytes

Many thanks!
Jhh

**Comment by ReneNulschDE** [comment]
Hi Jhh,

thanks for reporting. This is a know bug and I'm working on a fix.

BR
Rene

**Comment by jhhbe** [comment]
Much appreciated and looking forward to this! Btw - thank you for an excellent piece of work.

**Comment by ReneNulschDE** [comment]
Please retest. I have updated the component. More details: https://community.home-assistant.io/t/mercedes-me-component/41911/631

**Comment by jhhbe** [comment]
If it disconnected after 200mins, then now it must be working: no errormessages in the log since restart yesterday evening.

Many thanks!

PS: unlock service works also!
