### ISSUE TITLE
Error importing platform

### ISSUE THREAD

**Issue by Botond24** [ReneNulschDE/mbapi2020#41]
`Logger: homeassistant.config_entries
Source: config_entries.py:711
First occurred: 08:03:30 (1 occurrences)
Last logged: 08:03:30

Error occurred loading configuration flow for integration mbapi2020: cannot import name 'Platform' from 'homeassistant.const' (/srv/homeassistant/lib/python3.9/site-packages/homeassistant/const.py)`

I've had this error for a while and haven't been able to figure it out. The integration is on v0.6.3

**Comment by ReneNulschDE** [comment]
Do you run an older HA-Version? Minimum HA Version is 2021.12.9 - In case you can't upgrade ping me via a private message in the HA community and I can share the needed code changes (2 lines)

**Comment by Botond24** [comment]
I am a actually, thanks
