### ISSUE TITLE
Aux heat is not working on EQC

### ISSUE THREAD

**Issue by Mastiffen** [ReneNulschDE/mbapi2020#43]
I assume Aux Heat is the same as turning on the AC to pre-heat (or pre-cool) the car to the set temperature. If not, I apologize for the misunderstanding. The switch is there on my EQC integration, but it's not doing anything. I can unlock the car, but not turn on the AC.

**Comment by ReneNulschDE** [comment]
for the EQC (or other hybrids) you have to use the preheat_start/stop instead of auxheat_start/stop. (auxiliary heating is a secondary combustion heating)
