### ISSUE TITLE
 Charging Power in energie dashboard

### ISSUE THREAD

**Issue by XVD-XVD** [ReneNulschDE/mbapi2020#44]
Can you fix this? That the sensor can be used in the energie dashboard.

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

kind regards!

**Comment by Couto** [comment]
Same thing, from an user perspective this makes sense to fix, as this can help us track energy costs from charging the attery.

**Comment by ReneNulschDE** [comment]
Please install the latest version and check this post https://community.home-assistant.io/t/mercedes-me-component/41911/1225

**Comment by Couto** [comment]
I had some trouble setting it up (I'm a HA noob to be fair), but after some fiddling, I can confirm that it works.
Can I suggest that the instructions on how to add the device to the Energy Dashboard be added to the readme file? (Nothing big, just a nice to have)

<img width="1651" alt="Screenshot 2022-04-07 at 10 56 19" src="https://user-images.githubusercontent.com/165314/162173641-083d4956-3c44-44a7-81e4-a2ffb8ab00fe.png">

Either way, thank you so much! <3
