### ISSUE TITLE
Missing entities for my V Class

### ISSUE THREAD

**Issue by vincentsticky** [ReneNulschDE/mbapi2020#45]
Hello,
Congratulation on your work,  this is very good to get data from Mercedes in HA
My major problem is that I only get 7 entities

![image](https://user-images.githubusercontent.com/73120862/158824208-9f9c9a31-ffe3-4b60-be0e-3267d73632d1.png)

The entities are those ones :

![image](https://user-images.githubusercontent.com/73120862/158824300-c13321f3-8edd-4784-85a8-e2a670ec382a.png)

one time I had an odometer but was often marked as unavailable. (only got 2 or 3 times the odometer info)

Is this linked to limited features of my VClass and not covered by the API?

Thanks in advance

Vincent

**Comment by vincentsticky** [comment]
Hello. I understand that this is linked to the services attached to my car but I do not understand then why I add access sometimes to the odometer ?

**Comment by ReneNulschDE** [comment]
I saw this odometer problem (and few other sensors) in the past. Looks like that the MB-API does not deliver the odometer information when the component start. I have this on my list of further improvements to check for new information and creating the relevant sensors  later too. 

Unfortunately, this happens very seldom and is hard to debug/test.

**Comment by ReneNulschDE** [comment]
Before I change the code let us try something different. (I have also one car where some data is not reported by the MBAPI when the car was not moved for more then 48h)

Next when you stopped driving. Please try to Reload the component and let us check if Odometer is reported again.
1. Home-Assistant, Configuration, Devices and Integrations
2. Click on the 3 dots of the MB Integration
3. Click on Reload
4. Wait 5-10 seconds and check if Odometer gets reported again

Please let me know the results

**Comment by vincentsticky** [comment]
Hello
Thanks for this but Ichav the same behaviour
No additional entiy for thé odometer

Le dim. 10 avr. 2022 à 19:08, Rene Nulsch ***@***.***> a
écrit :

**Comment by vincentsticky** [comment]
Sorry. I have activated the debug mode but I'm not sure where the log file is stored ?
