### ISSUE TITLE
Binary Sensor doesn't get updated (windows_closed)

### ISSUE THREAD

**Issue by Couto** [ReneNulschDE/mbapi2020#47]
Not sure if I'm the only one, but in my homeassistant instance the `binary_sensor.xxxx_windows_closed` doesn't get updated, the interesting part is that its attributes do get updated:

So in other words `binary_sensor.xxxx_windows_closed` shows the value of `on` while its attributes are:
- windowstatusrearright: 1
- windowstatusfrontright: 1
- windowstatusrearleft: 1
- windowstatusfrontleft: 1

I can provide more info if you need, I'm just not sure what else is useful right now.

**Comment by ReneNulschDE** [comment]
Thanks for reporting this issue. I can reproduce this with my car too. Looks like the MBapi does not report the overall window status anymore. Let me check this.

**Comment by ReneNulschDE** [comment]
Could you check again? Today the MBapi reports the overall window status again.

**Comment by Couto** [comment]
Totally forgot to answer your question, truly sorry. 
After your comment, everything worked again! Thanks
