### ISSUE TITLE
Charging power Updates only after restart. 

### ISSUE THREAD

**Issue by srslykev** [ReneNulschDE/mbapi2020#51]
Hi there,

unfortunately, the charging power entity is updating much slower (hours) than the others. Mostly, I need to restart the Integration in order to get the current value.

Since I'm using Riemann sum integral to estimate Power usage, it would be great, If the charging power updated as reliably as the other entities.

Thanks for the great work!

**Comment by ReneNulschDE** [comment]
Hi @srslykev ,

sorry for the late answer. In which country do you live? I can't see any delayed message from the MB Message Bus in Germany. This component has no influence on the update performance. I get messages from MB same like the MB-MobileApp. Do you see the same behavior in the app too?

BR
Rene

**Comment by srslykev** [comment]
Hi, thanks for your reply. I live in Germany, too and the app shows correct data 🤔. The other entities work fine 🤷🏼‍♂️

**Comment by ReneNulschDE** [comment]
Could you enable the debug log (see readme)?  You should see every 1-2min a incoming message whenever the car is recharging.

**Comment by ReneNulschDE** [comment]
no feedback - closing issue
