### ISSUE TITLE
I can't find the maximum charge level (maxSoc)

### ISSUE THREAD

**Issue by hassio70** [ReneNulschDE/mbapi2020#52]
![image](https://user-images.githubusercontent.com/63094549/167299285-987562b6-3252-490e-b6cc-bcc20feb6f13.png)
Thanks for your help

**Comment by ReneNulschDE** [comment]
What car do you have? Should be available for EQxxx

![2DDA34A3-875F-48D9-A4EA-1F7E5BF31CDC](https://user-images.githubusercontent.com/33263735/167300841-1683e799-dd52-41cd-acc8-50955ac31023.jpeg)

**Comment by hassio70** [comment]
![image](https://user-images.githubusercontent.com/63094549/167301618-7c180172-4481-42f6-95fb-8e776cca5268.png)

**Comment by ReneNulschDE** [comment]
Let me ask in the HA [Community](https://community.home-assistant.io/t/mercedes-me-component/41911/1245)  thread if another EQA driver can check this. I have access to an EQC only.

**Comment by ReneNulschDE** [comment]
No reference car to check. I assume that an EQA has not this attribute.

**Comment by ReneNulschDE** [comment]
This is fixed in the master branch and will be part of the next release. EQA/B have a different handling of this attribute. special handling added.
