### ISSUE TITLE
Service call not working

### ISSUE THREAD

**Issue by juite** [ReneNulschDE/mbapi2020#56]
Hi, 

Thanks for the nice HA Integration.

I'm struggeling a bit with caling services. When caling services like Roof Open, Unlock they don't work (locking the car works). I have configured the integration with VIN and PIN. When i.e. caling service "MercedesME 2020: sunroof_open", it does not open de sun roof. 

![image](https://user-images.githubusercontent.com/365238/171169302-7f39ed5a-a8c3-4545-a7bb-975c3ffa511c.png)

Message:

JSON:
`{
  "apptwin_command_status_updates_by_vin": {
    "updates_by_vin": {
      "Wxxxxxxxxxx": {
        "vin": "W1xxxxxxxxxxxxxxxx",
        "updates_by_pid": {
          "58xxxx3": {
            "process_id": "58xxxx3",
            "request_id": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx",
            "timestamp_in_ms": "-1",
            "type": "ROOFOPEN",
            "state": "INITIATION"
          }
        }
      }
    }
  }
}`

Message:

'utf-8' codec can't decode byte 0x8a in position 0: invalid start byte

What can that be?

**Comment by ReneNulschDE** [comment]
Hi, can you enable the debug log and share the complete error message? I’m on vacation in Italy right now. Please expect some delays from my side

**Comment by juite** [comment]
Hi, enjoy your vacation in Italy!
I made a brand new installation of the integration and its working  without the problem. Until restarting Home Assistant. All sensors became unavailable.  I restarted HA because it was not updating status information for the sensors. In the messages folder  I see that it receives a JSON with correct information. It looks like it has problem in parsing the JSON. Would jou like to receive the messages from the messages folder? and how would you like to receive them?

**Comment by ReneNulschDE** [comment]
Could you send the logs + messages via email to mb.dev.issue.56 (@) Nulsch.de?
