### ISSUE TITLE
After upgrade to HA 2022.6 warning appears in log

### ISSUE THREAD

**Issue by czornikk** [ReneNulschDE/mbapi2020#57]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 22:25:41
Last logged: 22:25:41

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for mbapi2020 using this method at custom_components/mbapi2020/__init__.py, line 115: dev_reg = await hass.helpers.device_registry.async_get_registry()

**Comment by ReneNulschDE** [comment]
Thanks. This is fixed in themaster branch since last week. Next release will be published after my vacation.

**Comment by ReneNulschDE** [comment]
Fixed in release v0.6.7
