### ISSUE TITLE
Door lock fails, VIN not associated with user

### ISSUE THREAD

**Issue by brockkopp** [ReneNulschDE/mbapi2020#59]
New setup mbapi2020 is generally working: receiving door, window, ignition, etc sensor updates. Located in US. Integrating with a VS30 Sprinter.

When attempting to lock, command fails. Debug message log below, but message is "VIN does not belong to user". VIN is correct in all sensor updates.

Resolved issue by changing __init__.py, lines 164,165

was:
- current_car.finorvin = car.get('fin')
- current_car.licenseplate = car.get('licensePlate', car.get('fin'))

now:
- current_car.finorvin = car.get('vin')
- current_car.licenseplate = car.get('licensePlate', car.get('vin'))

It appears that integration was sending FIN instead of VIN when commanding doors locked. Mercedes was expecting VIN. I know very little on the subject, but looks like FIN and VIN aren't equivalent in US. I'm not sure what else the lines above break, but this appears to be stable for me in the US.

Debug log message:

> {
>   "apptwin_command_status_updates_by_vin": {
>     "sequence_number": 2,
>     "updates_by_vin": {
>       ""#####",": {
>         "vin": "#####",
>         "updates_by_pid": {
>           "-#####": {
>             "process_id": "-#####",
>             "request_id": "#####",
>             "timestamp_in_ms": "#####",
>             "errors": [
>               {
>                 "code": "RIS_FORBIDDEN_VIN",
>                 "message": "VIN does not belong to user"
>               }
>             ],
>             "type": "DOORSLOCK",
>             "state": "FAILED"
>           }
>         }
>       }
>     }
>   }
> }

**Comment by ReneNulschDE** [comment]
hi, took a while to get this integrated. However the Master Branch has this code change now. Will release a new version in few days after some testing.
