### ISSUE TITLE
Failed with the latest update v0.6.8

### ISSUE THREAD

**Issue by jcorreaes** [ReneNulschDE/mbapi2020#76]
Logger: homeassistant.setup
Source: setup.py:192
First occurred: 14:43:05 (1 occurrences)
Last logged: 14:43:05

Setup failed for custom integration mbapi2020: Unable to import component: cannot import name 'US_CUSTOMARY_SYSTEM' from 'homeassistant.util.unit_system'

**Comment by ReneNulschDE** [comment]
Hi, the latest version requires HA version 2022.11.
