### ISSUE TITLE
Unable to start: cannot import name 'US_CUSTOMARY_SYSTEM'

### ISSUE THREAD

**Issue by dimaguy** [ReneNulschDE/mbapi2020#80]
Logger: homeassistant.setup
Source: setup.py:192
First occurred: 9:00:10 PM (1 occurrences)
Last logged: 9:00:10 PM

Setup failed for custom integration mbapi2020: Unable to import component: cannot import name 'US_CUSTOMARY_SYSTEM' from 'homeassistant.util.unit_system' (/usr/src/homeassistant/homeassistant/util/unit_system.py)

**Comment by ReneNulschDE** [comment]
Hi, you use an older HA version. Minimum version is 2022.11

**Comment by dimaguy** [comment]
thanks for the quick reply, it had occurred to me just as I was posting this issue that I run HA on a docker container whose image is not auto updated just yet, I'm pulling the latest image and will close this issue if it gets fixed, sorry to bother you
