### ISSUE TITLE
MB API After Backup restoration

### ISSUE THREAD

**Issue by sweti3** [ReneNulschDE/mbapi2020#81]
Hei, 

I was restoring my HA recently, then MB Integration stopped working:

Logger: custom_components.mbapi2020.oauth
Source: custom_components/mbapi2020/oauth.py:139
Integration: MercedesME 2020 ([documentation](https://github.com/ReneNulschDE/mbapi2020), [issues](https://github.com/ReneNulschDE/mbapi2020/issues))
First occurred: 09:23:06 (7 occurrences)
Last logged: 09:25:30
ClientError requesting data from https://id.mercedes-benz.com/as/token.oauth2: 400, message='Bad Request', url=URL('https://id.mercedes-benz.com/as/token.oauth2')

Is this normal? What can I do against that? Do I have to reinstall everything again? 

Thanks!

**Comment by ReneNulschDE** [comment]
I would propose that you stop HA, delete the file .mercedesme-token-cache in your HA-config folder. Then start HA and reonboard the integration.

**Comment by coolekatze11** [comment]
Hi @ReneNulschDE ,
thank you for this solution, it solved my problem after restoring on a new RasberryPi. You might consider to include this as a hint in the general installation instructions. I have spent some time trying to re-connect and was not successful. New installation resulted in "unknown error", only removing this file helped. So it might be worth noting that resetting access to requires removal of this file.

Thank you for the great MB integration! I do really like it.
Best wishes,
CooleKatze11

**Comment by ReneNulschDE** [comment]
thx, I added a note to the readme
