### ISSUE TITLE
Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by olialth1979** [ReneNulschDE/mbapi2020#89]
Getting "Configuration Flow could not be loaded, invalid handler".
Manually installed the Mbapi 2020  into custom_components (inside docker container).
Rebooted Home Assistant, then trying to add the integration:

![image](https://user-images.githubusercontent.com/44643667/206909916-acdfd256-fcc1-4add-827a-601b6a4d2f5f.png)

**Comment by ReneNulschDE** [comment]
Could you please share more information about your HA environment? And check the logs for the detailed error message.

**Comment by ReneNulschDE** [comment]
Hi, could you please update to the prerelease v0.7.0b2 and check again. MB changed some api endpoints last week.

**Comment by ReneNulschDE** [comment]
Hi, this should be solved with version >v0.7.0

**Comment by olialth1979** [comment]
Hi, sorry, did not have time during christmas holidays. Will test now.

**Comment by olialth1979** [comment]
Works perfectly now with my EQB. Thanks for the fixes @ReneNulschDE !
