### ISSUE TITLE
websocket connection had an error

### ISSUE THREAD

**Issue by gavinpbennett** [ReneNulschDE/mbapi2020#92]
Only noticed this since 2022.12.8 update, but could have been before the update. I have also updated mbapi2020 to 0.7.2.

This error originated from a custom integration.

Logger: custom_components.mbapi2020.websocket
Source: custom_components/mbapi2020/websocket.py:197
Integration: MercedesME 2020 (documentation, issues)
First occurred: 10:48:15 (144 occurrences)
Last logged: 10:54:38

websocket connection had an error

**Comment by gavinpbennett** [comment]
I tried deleting and re-adding the integration, and got the following error:

ClientError requesting data from https://bff.amap-prod.mobilesdk.mercedes-benz.com/v1/login: 418, message="I'm a teapot", url=URL('https://bff.amap-prod.mobilesdk.mercedes-benz.com/v1/login')

**Comment by ReneNulschDE** [comment]
Did you selected Asia-Pacific as your region?

**Comment by ReneNulschDE** [comment]
Hi, This should be fixed in the new release v0.7.3. Please check.

**Comment by ReneNulschDE** [comment]
Now it should be fixed in version v0.7.4

**Comment by gavinpbennett** [comment]
I did select APAC, & can confirm this is working 👍
