### ISSUE TITLE
country: Thailand Region: Asia-Pacific - no car found

### ISSUE THREAD

**Issue by GauntPT** [ReneNulschDE/mbapi2020#95]
Hi everyone,

I am living in Thailand and if I select "Asia-Pacific" as Region, no car will be found.
Login is possible and als o PIN is OK.

If I switch to Europe, the car will be shown and the addon is working. 
Not sure if this is an issue. Is there any benefit/limitations for the regions?

**Comment by ReneNulschDE** [comment]
Hi,

thanks for the feedback. Looks like that Thailand is using the "ece"-region. Let me add a note the readme.

BR
Rene

**Comment by ReneNulschDE** [comment]
solved, note added. Thx again for reporting
