### ISSUE TITLE
ClientError requesting data

### ISSUE THREAD

**Issue by carlos1oliveir** [ReneNulschDE/mbapi2020#96]
My HA stop connect to my Mercedes.

ClientError requesting data from https://id.mercedes-benz.com/as/token.oauth2: Cannot connect to host id.mercedes-benz.com:443 ssl:default [Name does not resolve]
ClientError requesting data from https://id.mercedes-benz.com/as/token.oauth2: 400, message='Bad Request', url=URL('https://id.mercedes-benz.com/as/token.oauth2')

**Comment by ReneNulschDE** [comment]
Hi,

Make sure you are running on >=HA2022.11 and MBAPI2020 =v0.7.4

Then:
- please delete the .Mercedes token file in your HA folder
- Restart HA
- Reauthenticate the component

**Comment by carlos1oliveir** [comment]
It works. thank you.
